---@meta
-- Auto-generated overloads and table accessors for multi-version DbcWorkspace. Do not edit.

---@class DbcWorkspace
---@field build? string Configured target client build
---@field source_dir string Input directory
---@field output_dir string Output directory

---Workspace for WoW Build 3.3.5.12340 (3.3.5).
---@class DbcWorkspace_v335 : DbcWorkspace
---@field Achievement dbc.Table.v335.Achievement
---@field Achievement_Category dbc.Table.v335.Achievement_Category
---@field Achievement_Criteria dbc.Table.v335.Achievement_Criteria
---@field AnimationData dbc.Table.v335.AnimationData
---@field AreaGroup dbc.Table.v335.AreaGroup
---@field AreaPOI dbc.Table.v335.AreaPOI
---@field AreaTable dbc.Table.v335.AreaTable
---@field AreaTrigger dbc.Table.v335.AreaTrigger
---@field AttackAnimKits dbc.Table.v335.AttackAnimKits
---@field AttackAnimTypes dbc.Table.v335.AttackAnimTypes
---@field AuctionHouse dbc.Table.v335.AuctionHouse
---@field BankBagSlotPrices dbc.Table.v335.BankBagSlotPrices
---@field BannedAddons dbc.Table.v335.BannedAddons
---@field BarberShopStyle dbc.Table.v335.BarberShopStyle
---@field BattlemasterList dbc.Table.v335.BattlemasterList
---@field CameraShakes dbc.Table.v335.CameraShakes
---@field Cfg_Categories dbc.Table.v335.Cfg_Categories
---@field Cfg_Configs dbc.Table.v335.Cfg_Configs
---@field CharBaseInfo dbc.Table.v335.CharBaseInfo
---@field CharHairGeosets dbc.Table.v335.CharHairGeosets
---@field CharHairTextures dbc.Table.v335.CharHairTextures
---@field CharSections dbc.Table.v335.CharSections
---@field CharStartOutfit dbc.Table.v335.CharStartOutfit
---@field CharTitles dbc.Table.v335.CharTitles
---@field CharVariations dbc.Table.v335.CharVariations
---@field CharacterFacialHairStyles dbc.Table.v335.CharacterFacialHairStyles
---@field ChatChannels dbc.Table.v335.ChatChannels
---@field ChatProfanity dbc.Table.v335.ChatProfanity
---@field ChrClasses dbc.Table.v335.ChrClasses
---@field ChrRaces dbc.Table.v335.ChrRaces
---@field CinematicCamera dbc.Table.v335.CinematicCamera
---@field CinematicSequences dbc.Table.v335.CinematicSequences
---@field CreatureDisplayInfo dbc.Table.v335.CreatureDisplayInfo
---@field CreatureDisplayInfoExtra dbc.Table.v335.CreatureDisplayInfoExtra
---@field CreatureFamily dbc.Table.v335.CreatureFamily
---@field CreatureModelData dbc.Table.v335.CreatureModelData
---@field CreatureMovementInfo dbc.Table.v335.CreatureMovementInfo
---@field CreatureSoundData dbc.Table.v335.CreatureSoundData
---@field CreatureSpellData dbc.Table.v335.CreatureSpellData
---@field CreatureType dbc.Table.v335.CreatureType
---@field CurrencyCategory dbc.Table.v335.CurrencyCategory
---@field CurrencyTypes dbc.Table.v335.CurrencyTypes
---@field DanceMoves dbc.Table.v335.DanceMoves
---@field DeathThudLookups dbc.Table.v335.DeathThudLookups
---@field DeclinedWord dbc.Table.v335.DeclinedWord
---@field DeclinedWordCases dbc.Table.v335.DeclinedWordCases
---@field DestructibleModelData dbc.Table.v335.DestructibleModelData
---@field DungeonEncounter dbc.Table.v335.DungeonEncounter
---@field DungeonMap dbc.Table.v335.DungeonMap
---@field DungeonMapChunk dbc.Table.v335.DungeonMapChunk
---@field DurabilityCosts dbc.Table.v335.DurabilityCosts
---@field DurabilityQuality dbc.Table.v335.DurabilityQuality
---@field Emotes dbc.Table.v335.Emotes
---@field EmotesText dbc.Table.v335.EmotesText
---@field EmotesTextData dbc.Table.v335.EmotesTextData
---@field EmotesTextSound dbc.Table.v335.EmotesTextSound
---@field EnvironmentalDamage dbc.Table.v335.EnvironmentalDamage
---@field Exhaustion dbc.Table.v335.Exhaustion
---@field Faction dbc.Table.v335.Faction
---@field FactionGroup dbc.Table.v335.FactionGroup
---@field FactionTemplate dbc.Table.v335.FactionTemplate
---@field FileData dbc.Table.v335.FileData
---@field FootprintTextures dbc.Table.v335.FootprintTextures
---@field FootstepTerrainLookup dbc.Table.v335.FootstepTerrainLookup
---@field GMSurveyAnswers dbc.Table.v335.GMSurveyAnswers
---@field GMSurveyCurrentSurvey dbc.Table.v335.GMSurveyCurrentSurvey
---@field GMSurveyQuestions dbc.Table.v335.GMSurveyQuestions
---@field GMSurveySurveys dbc.Table.v335.GMSurveySurveys
---@field GMTicketCategory dbc.Table.v335.GMTicketCategory
---@field GameObjectArtKit dbc.Table.v335.GameObjectArtKit
---@field GameObjectDisplayInfo dbc.Table.v335.GameObjectDisplayInfo
---@field GameTables dbc.Table.v335.GameTables
---@field GameTips dbc.Table.v335.GameTips
---@field GemProperties dbc.Table.v335.GemProperties
---@field GlyphProperties dbc.Table.v335.GlyphProperties
---@field GlyphSlot dbc.Table.v335.GlyphSlot
---@field GroundEffectDoodad dbc.Table.v335.GroundEffectDoodad
---@field GroundEffectTexture dbc.Table.v335.GroundEffectTexture
---@field HelmetGeosetVisData dbc.Table.v335.HelmetGeosetVisData
---@field HolidayDescriptions dbc.Table.v335.HolidayDescriptions
---@field HolidayNames dbc.Table.v335.HolidayNames
---@field Holidays dbc.Table.v335.Holidays
---@field Item dbc.Table.v335.Item
---@field ItemBagFamily dbc.Table.v335.ItemBagFamily
---@field ItemClass dbc.Table.v335.ItemClass
---@field ItemCondExtCosts dbc.Table.v335.ItemCondExtCosts
---@field ItemDisplayInfo dbc.Table.v335.ItemDisplayInfo
---@field ItemExtendedCost dbc.Table.v335.ItemExtendedCost
---@field ItemGroupSounds dbc.Table.v335.ItemGroupSounds
---@field ItemLimitCategory dbc.Table.v335.ItemLimitCategory
---@field ItemPetFood dbc.Table.v335.ItemPetFood
---@field ItemPurchaseGroup dbc.Table.v335.ItemPurchaseGroup
---@field ItemRandomProperties dbc.Table.v335.ItemRandomProperties
---@field ItemRandomSuffix dbc.Table.v335.ItemRandomSuffix
---@field ItemSet dbc.Table.v335.ItemSet
---@field ItemSubClass dbc.Table.v335.ItemSubClass
---@field ItemSubClassMask dbc.Table.v335.ItemSubClassMask
---@field ItemVisualEffects dbc.Table.v335.ItemVisualEffects
---@field ItemVisuals dbc.Table.v335.ItemVisuals
---@field LFGDungeonExpansion dbc.Table.v335.LFGDungeonExpansion
---@field LFGDungeonGroup dbc.Table.v335.LFGDungeonGroup
---@field LFGDungeons dbc.Table.v335.LFGDungeons
---@field LanguageWords dbc.Table.v335.LanguageWords
---@field Languages dbc.Table.v335.Languages
---@field Light dbc.Table.v335.Light
---@field LightFloatBand dbc.Table.v335.LightFloatBand
---@field LightIntBand dbc.Table.v335.LightIntBand
---@field LightParams dbc.Table.v335.LightParams
---@field LightSkybox dbc.Table.v335.LightSkybox
---@field LiquidMaterial dbc.Table.v335.LiquidMaterial
---@field LiquidType dbc.Table.v335.LiquidType
---@field LoadingScreenTaxiSplines dbc.Table.v335.LoadingScreenTaxiSplines
---@field LoadingScreens dbc.Table.v335.LoadingScreens
---@field Lock dbc.Table.v335.Lock
---@field LockType dbc.Table.v335.LockType
---@field MailTemplate dbc.Table.v335.MailTemplate
---@field Map dbc.Table.v335.Map
---@field MapDifficulty dbc.Table.v335.MapDifficulty
---@field Material dbc.Table.v335.Material
---@field Movie dbc.Table.v335.Movie
---@field MovieFileData dbc.Table.v335.MovieFileData
---@field MovieVariation dbc.Table.v335.MovieVariation
---@field NPCSounds dbc.Table.v335.NPCSounds
---@field NameGen dbc.Table.v335.NameGen
---@field NamesProfanity dbc.Table.v335.NamesProfanity
---@field NamesReserved dbc.Table.v335.NamesReserved
---@field ObjectEffect dbc.Table.v335.ObjectEffect
---@field ObjectEffectGroup dbc.Table.v335.ObjectEffectGroup
---@field ObjectEffectModifier dbc.Table.v335.ObjectEffectModifier
---@field ObjectEffectPackage dbc.Table.v335.ObjectEffectPackage
---@field ObjectEffectPackageElem dbc.Table.v335.ObjectEffectPackageElem
---@field OverrideSpellData dbc.Table.v335.OverrideSpellData
---@field PVPDifficulty dbc.Table.v335.PVPDifficulty
---@field Package dbc.Table.v335.Package
---@field PageTextMaterial dbc.Table.v335.PageTextMaterial
---@field PaperDollItemFrame dbc.Table.v335.PaperDollItemFrame
---@field ParticleColor dbc.Table.v335.ParticleColor
---@field PetPersonality dbc.Table.v335.PetPersonality
---@field PetitionType dbc.Table.v335.PetitionType
---@field PowerDisplay dbc.Table.v335.PowerDisplay
---@field QuestFactionReward dbc.Table.v335.QuestFactionReward
---@field QuestInfo dbc.Table.v335.QuestInfo
---@field QuestSort dbc.Table.v335.QuestSort
---@field QuestXP dbc.Table.v335.QuestXP
---@field RandPropPoints dbc.Table.v335.RandPropPoints
---@field Resistances dbc.Table.v335.Resistances
---@field ScalingStatDistribution dbc.Table.v335.ScalingStatDistribution
---@field ScalingStatValues dbc.Table.v335.ScalingStatValues
---@field ScreenEffect dbc.Table.v335.ScreenEffect
---@field ServerMessages dbc.Table.v335.ServerMessages
---@field SheatheSoundLookups dbc.Table.v335.SheatheSoundLookups
---@field SkillCostsData dbc.Table.v335.SkillCostsData
---@field SkillLine dbc.Table.v335.SkillLine
---@field SkillLineAbility dbc.Table.v335.SkillLineAbility
---@field SkillLineCategory dbc.Table.v335.SkillLineCategory
---@field SkillRaceClassInfo dbc.Table.v335.SkillRaceClassInfo
---@field SkillTiers dbc.Table.v335.SkillTiers
---@field SoundAmbience dbc.Table.v335.SoundAmbience
---@field SoundEmitters dbc.Table.v335.SoundEmitters
---@field SoundEntries dbc.Table.v335.SoundEntries
---@field SoundEntriesAdvanced dbc.Table.v335.SoundEntriesAdvanced
---@field SoundFilter dbc.Table.v335.SoundFilter
---@field SoundFilterElem dbc.Table.v335.SoundFilterElem
---@field SoundProviderPreferences dbc.Table.v335.SoundProviderPreferences
---@field SoundSamplePreferences dbc.Table.v335.SoundSamplePreferences
---@field SoundWaterType dbc.Table.v335.SoundWaterType
---@field SpamMessages dbc.Table.v335.SpamMessages
---@field Spell dbc.Table.v335.Spell
---@field SpellCastTimes dbc.Table.v335.SpellCastTimes
---@field SpellCategory dbc.Table.v335.SpellCategory
---@field SpellChainEffects dbc.Table.v335.SpellChainEffects
---@field SpellDescriptionVariables dbc.Table.v335.SpellDescriptionVariables
---@field SpellDifficulty dbc.Table.v335.SpellDifficulty
---@field SpellDispelType dbc.Table.v335.SpellDispelType
---@field SpellDuration dbc.Table.v335.SpellDuration
---@field SpellEffectCameraShakes dbc.Table.v335.SpellEffectCameraShakes
---@field SpellFocusObject dbc.Table.v335.SpellFocusObject
---@field SpellIcon dbc.Table.v335.SpellIcon
---@field SpellItemEnchantment dbc.Table.v335.SpellItemEnchantment
---@field SpellItemEnchantmentCondition dbc.Table.v335.SpellItemEnchantmentCondition
---@field SpellMechanic dbc.Table.v335.SpellMechanic
---@field SpellMissile dbc.Table.v335.SpellMissile
---@field SpellMissileMotion dbc.Table.v335.SpellMissileMotion
---@field SpellRadius dbc.Table.v335.SpellRadius
---@field SpellRange dbc.Table.v335.SpellRange
---@field SpellRuneCost dbc.Table.v335.SpellRuneCost
---@field SpellShapeshiftForm dbc.Table.v335.SpellShapeshiftForm
---@field SpellVisual dbc.Table.v335.SpellVisual
---@field SpellVisualEffectName dbc.Table.v335.SpellVisualEffectName
---@field SpellVisualKit dbc.Table.v335.SpellVisualKit
---@field SpellVisualKitAreaModel dbc.Table.v335.SpellVisualKitAreaModel
---@field SpellVisualKitModelAttach dbc.Table.v335.SpellVisualKitModelAttach
---@field SpellVisualPrecastTransitions dbc.Table.v335.SpellVisualPrecastTransitions
---@field StableSlotPrices dbc.Table.v335.StableSlotPrices
---@field Startup_Strings dbc.Table.v335.Startup_Strings
---@field Stationery dbc.Table.v335.Stationery
---@field StringLookups dbc.Table.v335.StringLookups
---@field SummonProperties dbc.Table.v335.SummonProperties
---@field Talent dbc.Table.v335.Talent
---@field TalentTab dbc.Table.v335.TalentTab
---@field TaxiNodes dbc.Table.v335.TaxiNodes
---@field TaxiPath dbc.Table.v335.TaxiPath
---@field TaxiPathNode dbc.Table.v335.TaxiPathNode
---@field TeamContributionPoints dbc.Table.v335.TeamContributionPoints
---@field TerrainType dbc.Table.v335.TerrainType
---@field TerrainTypeSounds dbc.Table.v335.TerrainTypeSounds
---@field TotemCategory dbc.Table.v335.TotemCategory
---@field TransportAnimation dbc.Table.v335.TransportAnimation
---@field TransportPhysics dbc.Table.v335.TransportPhysics
---@field TransportRotation dbc.Table.v335.TransportRotation
---@field UISoundLookups dbc.Table.v335.UISoundLookups
---@field UnitBlood dbc.Table.v335.UnitBlood
---@field UnitBloodLevels dbc.Table.v335.UnitBloodLevels
---@field Vehicle dbc.Table.v335.Vehicle
---@field VehicleSeat dbc.Table.v335.VehicleSeat
---@field VehicleUIIndSeat dbc.Table.v335.VehicleUIIndSeat
---@field VehicleUIIndicator dbc.Table.v335.VehicleUIIndicator
---@field VideoHardware dbc.Table.v335.VideoHardware
---@field VocalUISounds dbc.Table.v335.VocalUISounds
---@field WMOAreaTable dbc.Table.v335.WMOAreaTable
---@field WeaponImpactSounds dbc.Table.v335.WeaponImpactSounds
---@field WeaponSwingSounds2 dbc.Table.v335.WeaponSwingSounds2
---@field Weather dbc.Table.v335.Weather
---@field WorldChunkSounds dbc.Table.v335.WorldChunkSounds
---@field WorldMapArea dbc.Table.v335.WorldMapArea
---@field WorldMapContinent dbc.Table.v335.WorldMapContinent
---@field WorldMapOverlay dbc.Table.v335.WorldMapOverlay
---@field WorldMapTransforms dbc.Table.v335.WorldMapTransforms
---@field WorldSafeLocs dbc.Table.v335.WorldSafeLocs
---@field WorldStateUI dbc.Table.v335.WorldStateUI
---@field WorldStateZoneSounds dbc.Table.v335.WorldStateZoneSounds
---@field WowError_Strings dbc.Table.v335.WowError_Strings
---@field ZoneIntroMusicTable dbc.Table.v335.ZoneIntroMusicTable
---@field ZoneMusic dbc.Table.v335.ZoneMusic
---@field gtBarberShopCostBase dbc.Table.v335.gtBarberShopCostBase
---@field gtChanceToMeleeCrit dbc.Table.v335.gtChanceToMeleeCrit
---@field gtChanceToMeleeCritBase dbc.Table.v335.gtChanceToMeleeCritBase
---@field gtChanceToSpellCrit dbc.Table.v335.gtChanceToSpellCrit
---@field gtChanceToSpellCritBase dbc.Table.v335.gtChanceToSpellCritBase
---@field gtCombatRatings dbc.Table.v335.gtCombatRatings
---@field gtNPCManaCostScaler dbc.Table.v335.gtNPCManaCostScaler
---@field gtOCTClassCombatRatingScalar dbc.Table.v335.gtOCTClassCombatRatingScalar
---@field gtOCTRegenHP dbc.Table.v335.gtOCTRegenHP
---@field gtOCTRegenMP dbc.Table.v335.gtOCTRegenMP
---@field gtRegenHPPerSpt dbc.Table.v335.gtRegenHPPerSpt
---@field gtRegenMPPerSpt dbc.Table.v335.gtRegenMPPerSpt

---@overload fun(self: DbcWorkspace_v335, name: '"Achievement"'): dbc.Table.v335.Achievement
---@overload fun(self: DbcWorkspace_v335, name: '"Achievement_Category"'): dbc.Table.v335.Achievement_Category
---@overload fun(self: DbcWorkspace_v335, name: '"Achievement_Criteria"'): dbc.Table.v335.Achievement_Criteria
---@overload fun(self: DbcWorkspace_v335, name: '"AnimationData"'): dbc.Table.v335.AnimationData
---@overload fun(self: DbcWorkspace_v335, name: '"AreaGroup"'): dbc.Table.v335.AreaGroup
---@overload fun(self: DbcWorkspace_v335, name: '"AreaPOI"'): dbc.Table.v335.AreaPOI
---@overload fun(self: DbcWorkspace_v335, name: '"AreaTable"'): dbc.Table.v335.AreaTable
---@overload fun(self: DbcWorkspace_v335, name: '"AreaTrigger"'): dbc.Table.v335.AreaTrigger
---@overload fun(self: DbcWorkspace_v335, name: '"AttackAnimKits"'): dbc.Table.v335.AttackAnimKits
---@overload fun(self: DbcWorkspace_v335, name: '"AttackAnimTypes"'): dbc.Table.v335.AttackAnimTypes
---@overload fun(self: DbcWorkspace_v335, name: '"AuctionHouse"'): dbc.Table.v335.AuctionHouse
---@overload fun(self: DbcWorkspace_v335, name: '"BankBagSlotPrices"'): dbc.Table.v335.BankBagSlotPrices
---@overload fun(self: DbcWorkspace_v335, name: '"BannedAddons"'): dbc.Table.v335.BannedAddons
---@overload fun(self: DbcWorkspace_v335, name: '"BarberShopStyle"'): dbc.Table.v335.BarberShopStyle
---@overload fun(self: DbcWorkspace_v335, name: '"BattlemasterList"'): dbc.Table.v335.BattlemasterList
---@overload fun(self: DbcWorkspace_v335, name: '"CameraShakes"'): dbc.Table.v335.CameraShakes
---@overload fun(self: DbcWorkspace_v335, name: '"Cfg_Categories"'): dbc.Table.v335.Cfg_Categories
---@overload fun(self: DbcWorkspace_v335, name: '"Cfg_Configs"'): dbc.Table.v335.Cfg_Configs
---@overload fun(self: DbcWorkspace_v335, name: '"CharBaseInfo"'): dbc.Table.v335.CharBaseInfo
---@overload fun(self: DbcWorkspace_v335, name: '"CharHairGeosets"'): dbc.Table.v335.CharHairGeosets
---@overload fun(self: DbcWorkspace_v335, name: '"CharHairTextures"'): dbc.Table.v335.CharHairTextures
---@overload fun(self: DbcWorkspace_v335, name: '"CharSections"'): dbc.Table.v335.CharSections
---@overload fun(self: DbcWorkspace_v335, name: '"CharStartOutfit"'): dbc.Table.v335.CharStartOutfit
---@overload fun(self: DbcWorkspace_v335, name: '"CharTitles"'): dbc.Table.v335.CharTitles
---@overload fun(self: DbcWorkspace_v335, name: '"CharVariations"'): dbc.Table.v335.CharVariations
---@overload fun(self: DbcWorkspace_v335, name: '"CharacterFacialHairStyles"'): dbc.Table.v335.CharacterFacialHairStyles
---@overload fun(self: DbcWorkspace_v335, name: '"ChatChannels"'): dbc.Table.v335.ChatChannels
---@overload fun(self: DbcWorkspace_v335, name: '"ChatProfanity"'): dbc.Table.v335.ChatProfanity
---@overload fun(self: DbcWorkspace_v335, name: '"ChrClasses"'): dbc.Table.v335.ChrClasses
---@overload fun(self: DbcWorkspace_v335, name: '"ChrRaces"'): dbc.Table.v335.ChrRaces
---@overload fun(self: DbcWorkspace_v335, name: '"CinematicCamera"'): dbc.Table.v335.CinematicCamera
---@overload fun(self: DbcWorkspace_v335, name: '"CinematicSequences"'): dbc.Table.v335.CinematicSequences
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureDisplayInfo"'): dbc.Table.v335.CreatureDisplayInfo
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureDisplayInfoExtra"'): dbc.Table.v335.CreatureDisplayInfoExtra
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureFamily"'): dbc.Table.v335.CreatureFamily
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureModelData"'): dbc.Table.v335.CreatureModelData
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureMovementInfo"'): dbc.Table.v335.CreatureMovementInfo
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureSoundData"'): dbc.Table.v335.CreatureSoundData
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureSpellData"'): dbc.Table.v335.CreatureSpellData
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureType"'): dbc.Table.v335.CreatureType
---@overload fun(self: DbcWorkspace_v335, name: '"CurrencyCategory"'): dbc.Table.v335.CurrencyCategory
---@overload fun(self: DbcWorkspace_v335, name: '"CurrencyTypes"'): dbc.Table.v335.CurrencyTypes
---@overload fun(self: DbcWorkspace_v335, name: '"DanceMoves"'): dbc.Table.v335.DanceMoves
---@overload fun(self: DbcWorkspace_v335, name: '"DeathThudLookups"'): dbc.Table.v335.DeathThudLookups
---@overload fun(self: DbcWorkspace_v335, name: '"DeclinedWord"'): dbc.Table.v335.DeclinedWord
---@overload fun(self: DbcWorkspace_v335, name: '"DeclinedWordCases"'): dbc.Table.v335.DeclinedWordCases
---@overload fun(self: DbcWorkspace_v335, name: '"DestructibleModelData"'): dbc.Table.v335.DestructibleModelData
---@overload fun(self: DbcWorkspace_v335, name: '"DungeonEncounter"'): dbc.Table.v335.DungeonEncounter
---@overload fun(self: DbcWorkspace_v335, name: '"DungeonMap"'): dbc.Table.v335.DungeonMap
---@overload fun(self: DbcWorkspace_v335, name: '"DungeonMapChunk"'): dbc.Table.v335.DungeonMapChunk
---@overload fun(self: DbcWorkspace_v335, name: '"DurabilityCosts"'): dbc.Table.v335.DurabilityCosts
---@overload fun(self: DbcWorkspace_v335, name: '"DurabilityQuality"'): dbc.Table.v335.DurabilityQuality
---@overload fun(self: DbcWorkspace_v335, name: '"Emotes"'): dbc.Table.v335.Emotes
---@overload fun(self: DbcWorkspace_v335, name: '"EmotesText"'): dbc.Table.v335.EmotesText
---@overload fun(self: DbcWorkspace_v335, name: '"EmotesTextData"'): dbc.Table.v335.EmotesTextData
---@overload fun(self: DbcWorkspace_v335, name: '"EmotesTextSound"'): dbc.Table.v335.EmotesTextSound
---@overload fun(self: DbcWorkspace_v335, name: '"EnvironmentalDamage"'): dbc.Table.v335.EnvironmentalDamage
---@overload fun(self: DbcWorkspace_v335, name: '"Exhaustion"'): dbc.Table.v335.Exhaustion
---@overload fun(self: DbcWorkspace_v335, name: '"Faction"'): dbc.Table.v335.Faction
---@overload fun(self: DbcWorkspace_v335, name: '"FactionGroup"'): dbc.Table.v335.FactionGroup
---@overload fun(self: DbcWorkspace_v335, name: '"FactionTemplate"'): dbc.Table.v335.FactionTemplate
---@overload fun(self: DbcWorkspace_v335, name: '"FileData"'): dbc.Table.v335.FileData
---@overload fun(self: DbcWorkspace_v335, name: '"FootprintTextures"'): dbc.Table.v335.FootprintTextures
---@overload fun(self: DbcWorkspace_v335, name: '"FootstepTerrainLookup"'): dbc.Table.v335.FootstepTerrainLookup
---@overload fun(self: DbcWorkspace_v335, name: '"GMSurveyAnswers"'): dbc.Table.v335.GMSurveyAnswers
---@overload fun(self: DbcWorkspace_v335, name: '"GMSurveyCurrentSurvey"'): dbc.Table.v335.GMSurveyCurrentSurvey
---@overload fun(self: DbcWorkspace_v335, name: '"GMSurveyQuestions"'): dbc.Table.v335.GMSurveyQuestions
---@overload fun(self: DbcWorkspace_v335, name: '"GMSurveySurveys"'): dbc.Table.v335.GMSurveySurveys
---@overload fun(self: DbcWorkspace_v335, name: '"GMTicketCategory"'): dbc.Table.v335.GMTicketCategory
---@overload fun(self: DbcWorkspace_v335, name: '"GameObjectArtKit"'): dbc.Table.v335.GameObjectArtKit
---@overload fun(self: DbcWorkspace_v335, name: '"GameObjectDisplayInfo"'): dbc.Table.v335.GameObjectDisplayInfo
---@overload fun(self: DbcWorkspace_v335, name: '"GameTables"'): dbc.Table.v335.GameTables
---@overload fun(self: DbcWorkspace_v335, name: '"GameTips"'): dbc.Table.v335.GameTips
---@overload fun(self: DbcWorkspace_v335, name: '"GemProperties"'): dbc.Table.v335.GemProperties
---@overload fun(self: DbcWorkspace_v335, name: '"GlyphProperties"'): dbc.Table.v335.GlyphProperties
---@overload fun(self: DbcWorkspace_v335, name: '"GlyphSlot"'): dbc.Table.v335.GlyphSlot
---@overload fun(self: DbcWorkspace_v335, name: '"GroundEffectDoodad"'): dbc.Table.v335.GroundEffectDoodad
---@overload fun(self: DbcWorkspace_v335, name: '"GroundEffectTexture"'): dbc.Table.v335.GroundEffectTexture
---@overload fun(self: DbcWorkspace_v335, name: '"HelmetGeosetVisData"'): dbc.Table.v335.HelmetGeosetVisData
---@overload fun(self: DbcWorkspace_v335, name: '"HolidayDescriptions"'): dbc.Table.v335.HolidayDescriptions
---@overload fun(self: DbcWorkspace_v335, name: '"HolidayNames"'): dbc.Table.v335.HolidayNames
---@overload fun(self: DbcWorkspace_v335, name: '"Holidays"'): dbc.Table.v335.Holidays
---@overload fun(self: DbcWorkspace_v335, name: '"Item"'): dbc.Table.v335.Item
---@overload fun(self: DbcWorkspace_v335, name: '"ItemBagFamily"'): dbc.Table.v335.ItemBagFamily
---@overload fun(self: DbcWorkspace_v335, name: '"ItemClass"'): dbc.Table.v335.ItemClass
---@overload fun(self: DbcWorkspace_v335, name: '"ItemCondExtCosts"'): dbc.Table.v335.ItemCondExtCosts
---@overload fun(self: DbcWorkspace_v335, name: '"ItemDisplayInfo"'): dbc.Table.v335.ItemDisplayInfo
---@overload fun(self: DbcWorkspace_v335, name: '"ItemExtendedCost"'): dbc.Table.v335.ItemExtendedCost
---@overload fun(self: DbcWorkspace_v335, name: '"ItemGroupSounds"'): dbc.Table.v335.ItemGroupSounds
---@overload fun(self: DbcWorkspace_v335, name: '"ItemLimitCategory"'): dbc.Table.v335.ItemLimitCategory
---@overload fun(self: DbcWorkspace_v335, name: '"ItemPetFood"'): dbc.Table.v335.ItemPetFood
---@overload fun(self: DbcWorkspace_v335, name: '"ItemPurchaseGroup"'): dbc.Table.v335.ItemPurchaseGroup
---@overload fun(self: DbcWorkspace_v335, name: '"ItemRandomProperties"'): dbc.Table.v335.ItemRandomProperties
---@overload fun(self: DbcWorkspace_v335, name: '"ItemRandomSuffix"'): dbc.Table.v335.ItemRandomSuffix
---@overload fun(self: DbcWorkspace_v335, name: '"ItemSet"'): dbc.Table.v335.ItemSet
---@overload fun(self: DbcWorkspace_v335, name: '"ItemSubClass"'): dbc.Table.v335.ItemSubClass
---@overload fun(self: DbcWorkspace_v335, name: '"ItemSubClassMask"'): dbc.Table.v335.ItemSubClassMask
---@overload fun(self: DbcWorkspace_v335, name: '"ItemVisualEffects"'): dbc.Table.v335.ItemVisualEffects
---@overload fun(self: DbcWorkspace_v335, name: '"ItemVisuals"'): dbc.Table.v335.ItemVisuals
---@overload fun(self: DbcWorkspace_v335, name: '"LFGDungeonExpansion"'): dbc.Table.v335.LFGDungeonExpansion
---@overload fun(self: DbcWorkspace_v335, name: '"LFGDungeonGroup"'): dbc.Table.v335.LFGDungeonGroup
---@overload fun(self: DbcWorkspace_v335, name: '"LFGDungeons"'): dbc.Table.v335.LFGDungeons
---@overload fun(self: DbcWorkspace_v335, name: '"LanguageWords"'): dbc.Table.v335.LanguageWords
---@overload fun(self: DbcWorkspace_v335, name: '"Languages"'): dbc.Table.v335.Languages
---@overload fun(self: DbcWorkspace_v335, name: '"Light"'): dbc.Table.v335.Light
---@overload fun(self: DbcWorkspace_v335, name: '"LightFloatBand"'): dbc.Table.v335.LightFloatBand
---@overload fun(self: DbcWorkspace_v335, name: '"LightIntBand"'): dbc.Table.v335.LightIntBand
---@overload fun(self: DbcWorkspace_v335, name: '"LightParams"'): dbc.Table.v335.LightParams
---@overload fun(self: DbcWorkspace_v335, name: '"LightSkybox"'): dbc.Table.v335.LightSkybox
---@overload fun(self: DbcWorkspace_v335, name: '"LiquidMaterial"'): dbc.Table.v335.LiquidMaterial
---@overload fun(self: DbcWorkspace_v335, name: '"LiquidType"'): dbc.Table.v335.LiquidType
---@overload fun(self: DbcWorkspace_v335, name: '"LoadingScreenTaxiSplines"'): dbc.Table.v335.LoadingScreenTaxiSplines
---@overload fun(self: DbcWorkspace_v335, name: '"LoadingScreens"'): dbc.Table.v335.LoadingScreens
---@overload fun(self: DbcWorkspace_v335, name: '"Lock"'): dbc.Table.v335.Lock
---@overload fun(self: DbcWorkspace_v335, name: '"LockType"'): dbc.Table.v335.LockType
---@overload fun(self: DbcWorkspace_v335, name: '"MailTemplate"'): dbc.Table.v335.MailTemplate
---@overload fun(self: DbcWorkspace_v335, name: '"Map"'): dbc.Table.v335.Map
---@overload fun(self: DbcWorkspace_v335, name: '"MapDifficulty"'): dbc.Table.v335.MapDifficulty
---@overload fun(self: DbcWorkspace_v335, name: '"Material"'): dbc.Table.v335.Material
---@overload fun(self: DbcWorkspace_v335, name: '"Movie"'): dbc.Table.v335.Movie
---@overload fun(self: DbcWorkspace_v335, name: '"MovieFileData"'): dbc.Table.v335.MovieFileData
---@overload fun(self: DbcWorkspace_v335, name: '"MovieVariation"'): dbc.Table.v335.MovieVariation
---@overload fun(self: DbcWorkspace_v335, name: '"NPCSounds"'): dbc.Table.v335.NPCSounds
---@overload fun(self: DbcWorkspace_v335, name: '"NameGen"'): dbc.Table.v335.NameGen
---@overload fun(self: DbcWorkspace_v335, name: '"NamesProfanity"'): dbc.Table.v335.NamesProfanity
---@overload fun(self: DbcWorkspace_v335, name: '"NamesReserved"'): dbc.Table.v335.NamesReserved
---@overload fun(self: DbcWorkspace_v335, name: '"ObjectEffect"'): dbc.Table.v335.ObjectEffect
---@overload fun(self: DbcWorkspace_v335, name: '"ObjectEffectGroup"'): dbc.Table.v335.ObjectEffectGroup
---@overload fun(self: DbcWorkspace_v335, name: '"ObjectEffectModifier"'): dbc.Table.v335.ObjectEffectModifier
---@overload fun(self: DbcWorkspace_v335, name: '"ObjectEffectPackage"'): dbc.Table.v335.ObjectEffectPackage
---@overload fun(self: DbcWorkspace_v335, name: '"ObjectEffectPackageElem"'): dbc.Table.v335.ObjectEffectPackageElem
---@overload fun(self: DbcWorkspace_v335, name: '"OverrideSpellData"'): dbc.Table.v335.OverrideSpellData
---@overload fun(self: DbcWorkspace_v335, name: '"PVPDifficulty"'): dbc.Table.v335.PVPDifficulty
---@overload fun(self: DbcWorkspace_v335, name: '"Package"'): dbc.Table.v335.Package
---@overload fun(self: DbcWorkspace_v335, name: '"PageTextMaterial"'): dbc.Table.v335.PageTextMaterial
---@overload fun(self: DbcWorkspace_v335, name: '"PaperDollItemFrame"'): dbc.Table.v335.PaperDollItemFrame
---@overload fun(self: DbcWorkspace_v335, name: '"ParticleColor"'): dbc.Table.v335.ParticleColor
---@overload fun(self: DbcWorkspace_v335, name: '"PetPersonality"'): dbc.Table.v335.PetPersonality
---@overload fun(self: DbcWorkspace_v335, name: '"PetitionType"'): dbc.Table.v335.PetitionType
---@overload fun(self: DbcWorkspace_v335, name: '"PowerDisplay"'): dbc.Table.v335.PowerDisplay
---@overload fun(self: DbcWorkspace_v335, name: '"QuestFactionReward"'): dbc.Table.v335.QuestFactionReward
---@overload fun(self: DbcWorkspace_v335, name: '"QuestInfo"'): dbc.Table.v335.QuestInfo
---@overload fun(self: DbcWorkspace_v335, name: '"QuestSort"'): dbc.Table.v335.QuestSort
---@overload fun(self: DbcWorkspace_v335, name: '"QuestXP"'): dbc.Table.v335.QuestXP
---@overload fun(self: DbcWorkspace_v335, name: '"RandPropPoints"'): dbc.Table.v335.RandPropPoints
---@overload fun(self: DbcWorkspace_v335, name: '"Resistances"'): dbc.Table.v335.Resistances
---@overload fun(self: DbcWorkspace_v335, name: '"ScalingStatDistribution"'): dbc.Table.v335.ScalingStatDistribution
---@overload fun(self: DbcWorkspace_v335, name: '"ScalingStatValues"'): dbc.Table.v335.ScalingStatValues
---@overload fun(self: DbcWorkspace_v335, name: '"ScreenEffect"'): dbc.Table.v335.ScreenEffect
---@overload fun(self: DbcWorkspace_v335, name: '"ServerMessages"'): dbc.Table.v335.ServerMessages
---@overload fun(self: DbcWorkspace_v335, name: '"SheatheSoundLookups"'): dbc.Table.v335.SheatheSoundLookups
---@overload fun(self: DbcWorkspace_v335, name: '"SkillCostsData"'): dbc.Table.v335.SkillCostsData
---@overload fun(self: DbcWorkspace_v335, name: '"SkillLine"'): dbc.Table.v335.SkillLine
---@overload fun(self: DbcWorkspace_v335, name: '"SkillLineAbility"'): dbc.Table.v335.SkillLineAbility
---@overload fun(self: DbcWorkspace_v335, name: '"SkillLineCategory"'): dbc.Table.v335.SkillLineCategory
---@overload fun(self: DbcWorkspace_v335, name: '"SkillRaceClassInfo"'): dbc.Table.v335.SkillRaceClassInfo
---@overload fun(self: DbcWorkspace_v335, name: '"SkillTiers"'): dbc.Table.v335.SkillTiers
---@overload fun(self: DbcWorkspace_v335, name: '"SoundAmbience"'): dbc.Table.v335.SoundAmbience
---@overload fun(self: DbcWorkspace_v335, name: '"SoundEmitters"'): dbc.Table.v335.SoundEmitters
---@overload fun(self: DbcWorkspace_v335, name: '"SoundEntries"'): dbc.Table.v335.SoundEntries
---@overload fun(self: DbcWorkspace_v335, name: '"SoundEntriesAdvanced"'): dbc.Table.v335.SoundEntriesAdvanced
---@overload fun(self: DbcWorkspace_v335, name: '"SoundFilter"'): dbc.Table.v335.SoundFilter
---@overload fun(self: DbcWorkspace_v335, name: '"SoundFilterElem"'): dbc.Table.v335.SoundFilterElem
---@overload fun(self: DbcWorkspace_v335, name: '"SoundProviderPreferences"'): dbc.Table.v335.SoundProviderPreferences
---@overload fun(self: DbcWorkspace_v335, name: '"SoundSamplePreferences"'): dbc.Table.v335.SoundSamplePreferences
---@overload fun(self: DbcWorkspace_v335, name: '"SoundWaterType"'): dbc.Table.v335.SoundWaterType
---@overload fun(self: DbcWorkspace_v335, name: '"SpamMessages"'): dbc.Table.v335.SpamMessages
---@overload fun(self: DbcWorkspace_v335, name: '"Spell"'): dbc.Table.v335.Spell
---@overload fun(self: DbcWorkspace_v335, name: '"SpellCastTimes"'): dbc.Table.v335.SpellCastTimes
---@overload fun(self: DbcWorkspace_v335, name: '"SpellCategory"'): dbc.Table.v335.SpellCategory
---@overload fun(self: DbcWorkspace_v335, name: '"SpellChainEffects"'): dbc.Table.v335.SpellChainEffects
---@overload fun(self: DbcWorkspace_v335, name: '"SpellDescriptionVariables"'): dbc.Table.v335.SpellDescriptionVariables
---@overload fun(self: DbcWorkspace_v335, name: '"SpellDifficulty"'): dbc.Table.v335.SpellDifficulty
---@overload fun(self: DbcWorkspace_v335, name: '"SpellDispelType"'): dbc.Table.v335.SpellDispelType
---@overload fun(self: DbcWorkspace_v335, name: '"SpellDuration"'): dbc.Table.v335.SpellDuration
---@overload fun(self: DbcWorkspace_v335, name: '"SpellEffectCameraShakes"'): dbc.Table.v335.SpellEffectCameraShakes
---@overload fun(self: DbcWorkspace_v335, name: '"SpellFocusObject"'): dbc.Table.v335.SpellFocusObject
---@overload fun(self: DbcWorkspace_v335, name: '"SpellIcon"'): dbc.Table.v335.SpellIcon
---@overload fun(self: DbcWorkspace_v335, name: '"SpellItemEnchantment"'): dbc.Table.v335.SpellItemEnchantment
---@overload fun(self: DbcWorkspace_v335, name: '"SpellItemEnchantmentCondition"'): dbc.Table.v335.SpellItemEnchantmentCondition
---@overload fun(self: DbcWorkspace_v335, name: '"SpellMechanic"'): dbc.Table.v335.SpellMechanic
---@overload fun(self: DbcWorkspace_v335, name: '"SpellMissile"'): dbc.Table.v335.SpellMissile
---@overload fun(self: DbcWorkspace_v335, name: '"SpellMissileMotion"'): dbc.Table.v335.SpellMissileMotion
---@overload fun(self: DbcWorkspace_v335, name: '"SpellRadius"'): dbc.Table.v335.SpellRadius
---@overload fun(self: DbcWorkspace_v335, name: '"SpellRange"'): dbc.Table.v335.SpellRange
---@overload fun(self: DbcWorkspace_v335, name: '"SpellRuneCost"'): dbc.Table.v335.SpellRuneCost
---@overload fun(self: DbcWorkspace_v335, name: '"SpellShapeshiftForm"'): dbc.Table.v335.SpellShapeshiftForm
---@overload fun(self: DbcWorkspace_v335, name: '"SpellVisual"'): dbc.Table.v335.SpellVisual
---@overload fun(self: DbcWorkspace_v335, name: '"SpellVisualEffectName"'): dbc.Table.v335.SpellVisualEffectName
---@overload fun(self: DbcWorkspace_v335, name: '"SpellVisualKit"'): dbc.Table.v335.SpellVisualKit
---@overload fun(self: DbcWorkspace_v335, name: '"SpellVisualKitAreaModel"'): dbc.Table.v335.SpellVisualKitAreaModel
---@overload fun(self: DbcWorkspace_v335, name: '"SpellVisualKitModelAttach"'): dbc.Table.v335.SpellVisualKitModelAttach
---@overload fun(self: DbcWorkspace_v335, name: '"SpellVisualPrecastTransitions"'): dbc.Table.v335.SpellVisualPrecastTransitions
---@overload fun(self: DbcWorkspace_v335, name: '"StableSlotPrices"'): dbc.Table.v335.StableSlotPrices
---@overload fun(self: DbcWorkspace_v335, name: '"Startup_Strings"'): dbc.Table.v335.Startup_Strings
---@overload fun(self: DbcWorkspace_v335, name: '"Stationery"'): dbc.Table.v335.Stationery
---@overload fun(self: DbcWorkspace_v335, name: '"StringLookups"'): dbc.Table.v335.StringLookups
---@overload fun(self: DbcWorkspace_v335, name: '"SummonProperties"'): dbc.Table.v335.SummonProperties
---@overload fun(self: DbcWorkspace_v335, name: '"Talent"'): dbc.Table.v335.Talent
---@overload fun(self: DbcWorkspace_v335, name: '"TalentTab"'): dbc.Table.v335.TalentTab
---@overload fun(self: DbcWorkspace_v335, name: '"TaxiNodes"'): dbc.Table.v335.TaxiNodes
---@overload fun(self: DbcWorkspace_v335, name: '"TaxiPath"'): dbc.Table.v335.TaxiPath
---@overload fun(self: DbcWorkspace_v335, name: '"TaxiPathNode"'): dbc.Table.v335.TaxiPathNode
---@overload fun(self: DbcWorkspace_v335, name: '"TeamContributionPoints"'): dbc.Table.v335.TeamContributionPoints
---@overload fun(self: DbcWorkspace_v335, name: '"TerrainType"'): dbc.Table.v335.TerrainType
---@overload fun(self: DbcWorkspace_v335, name: '"TerrainTypeSounds"'): dbc.Table.v335.TerrainTypeSounds
---@overload fun(self: DbcWorkspace_v335, name: '"TotemCategory"'): dbc.Table.v335.TotemCategory
---@overload fun(self: DbcWorkspace_v335, name: '"TransportAnimation"'): dbc.Table.v335.TransportAnimation
---@overload fun(self: DbcWorkspace_v335, name: '"TransportPhysics"'): dbc.Table.v335.TransportPhysics
---@overload fun(self: DbcWorkspace_v335, name: '"TransportRotation"'): dbc.Table.v335.TransportRotation
---@overload fun(self: DbcWorkspace_v335, name: '"UISoundLookups"'): dbc.Table.v335.UISoundLookups
---@overload fun(self: DbcWorkspace_v335, name: '"UnitBlood"'): dbc.Table.v335.UnitBlood
---@overload fun(self: DbcWorkspace_v335, name: '"UnitBloodLevels"'): dbc.Table.v335.UnitBloodLevels
---@overload fun(self: DbcWorkspace_v335, name: '"Vehicle"'): dbc.Table.v335.Vehicle
---@overload fun(self: DbcWorkspace_v335, name: '"VehicleSeat"'): dbc.Table.v335.VehicleSeat
---@overload fun(self: DbcWorkspace_v335, name: '"VehicleUIIndSeat"'): dbc.Table.v335.VehicleUIIndSeat
---@overload fun(self: DbcWorkspace_v335, name: '"VehicleUIIndicator"'): dbc.Table.v335.VehicleUIIndicator
---@overload fun(self: DbcWorkspace_v335, name: '"VideoHardware"'): dbc.Table.v335.VideoHardware
---@overload fun(self: DbcWorkspace_v335, name: '"VocalUISounds"'): dbc.Table.v335.VocalUISounds
---@overload fun(self: DbcWorkspace_v335, name: '"WMOAreaTable"'): dbc.Table.v335.WMOAreaTable
---@overload fun(self: DbcWorkspace_v335, name: '"WeaponImpactSounds"'): dbc.Table.v335.WeaponImpactSounds
---@overload fun(self: DbcWorkspace_v335, name: '"WeaponSwingSounds2"'): dbc.Table.v335.WeaponSwingSounds2
---@overload fun(self: DbcWorkspace_v335, name: '"Weather"'): dbc.Table.v335.Weather
---@overload fun(self: DbcWorkspace_v335, name: '"WorldChunkSounds"'): dbc.Table.v335.WorldChunkSounds
---@overload fun(self: DbcWorkspace_v335, name: '"WorldMapArea"'): dbc.Table.v335.WorldMapArea
---@overload fun(self: DbcWorkspace_v335, name: '"WorldMapContinent"'): dbc.Table.v335.WorldMapContinent
---@overload fun(self: DbcWorkspace_v335, name: '"WorldMapOverlay"'): dbc.Table.v335.WorldMapOverlay
---@overload fun(self: DbcWorkspace_v335, name: '"WorldMapTransforms"'): dbc.Table.v335.WorldMapTransforms
---@overload fun(self: DbcWorkspace_v335, name: '"WorldSafeLocs"'): dbc.Table.v335.WorldSafeLocs
---@overload fun(self: DbcWorkspace_v335, name: '"WorldStateUI"'): dbc.Table.v335.WorldStateUI
---@overload fun(self: DbcWorkspace_v335, name: '"WorldStateZoneSounds"'): dbc.Table.v335.WorldStateZoneSounds
---@overload fun(self: DbcWorkspace_v335, name: '"WowError_Strings"'): dbc.Table.v335.WowError_Strings
---@overload fun(self: DbcWorkspace_v335, name: '"ZoneIntroMusicTable"'): dbc.Table.v335.ZoneIntroMusicTable
---@overload fun(self: DbcWorkspace_v335, name: '"ZoneMusic"'): dbc.Table.v335.ZoneMusic
---@overload fun(self: DbcWorkspace_v335, name: '"gtBarberShopCostBase"'): dbc.Table.v335.gtBarberShopCostBase
---@overload fun(self: DbcWorkspace_v335, name: '"gtChanceToMeleeCrit"'): dbc.Table.v335.gtChanceToMeleeCrit
---@overload fun(self: DbcWorkspace_v335, name: '"gtChanceToMeleeCritBase"'): dbc.Table.v335.gtChanceToMeleeCritBase
---@overload fun(self: DbcWorkspace_v335, name: '"gtChanceToSpellCrit"'): dbc.Table.v335.gtChanceToSpellCrit
---@overload fun(self: DbcWorkspace_v335, name: '"gtChanceToSpellCritBase"'): dbc.Table.v335.gtChanceToSpellCritBase
---@overload fun(self: DbcWorkspace_v335, name: '"gtCombatRatings"'): dbc.Table.v335.gtCombatRatings
---@overload fun(self: DbcWorkspace_v335, name: '"gtNPCManaCostScaler"'): dbc.Table.v335.gtNPCManaCostScaler
---@overload fun(self: DbcWorkspace_v335, name: '"gtOCTClassCombatRatingScalar"'): dbc.Table.v335.gtOCTClassCombatRatingScalar
---@overload fun(self: DbcWorkspace_v335, name: '"gtOCTRegenHP"'): dbc.Table.v335.gtOCTRegenHP
---@overload fun(self: DbcWorkspace_v335, name: '"gtOCTRegenMP"'): dbc.Table.v335.gtOCTRegenMP
---@overload fun(self: DbcWorkspace_v335, name: '"gtRegenHPPerSpt"'): dbc.Table.v335.gtRegenHPPerSpt
---@overload fun(self: DbcWorkspace_v335, name: '"gtRegenMPPerSpt"'): dbc.Table.v335.gtRegenMPPerSpt
function DbcWorkspace_v335:Open(name) end

---@overload fun(self: DbcWorkspace_v335, name: '"Achievement"'): dbc.Table.v335.Achievement
---@overload fun(self: DbcWorkspace_v335, name: '"Achievement_Category"'): dbc.Table.v335.Achievement_Category
---@overload fun(self: DbcWorkspace_v335, name: '"Achievement_Criteria"'): dbc.Table.v335.Achievement_Criteria
---@overload fun(self: DbcWorkspace_v335, name: '"AnimationData"'): dbc.Table.v335.AnimationData
---@overload fun(self: DbcWorkspace_v335, name: '"AreaGroup"'): dbc.Table.v335.AreaGroup
---@overload fun(self: DbcWorkspace_v335, name: '"AreaPOI"'): dbc.Table.v335.AreaPOI
---@overload fun(self: DbcWorkspace_v335, name: '"AreaTable"'): dbc.Table.v335.AreaTable
---@overload fun(self: DbcWorkspace_v335, name: '"AreaTrigger"'): dbc.Table.v335.AreaTrigger
---@overload fun(self: DbcWorkspace_v335, name: '"AttackAnimKits"'): dbc.Table.v335.AttackAnimKits
---@overload fun(self: DbcWorkspace_v335, name: '"AttackAnimTypes"'): dbc.Table.v335.AttackAnimTypes
---@overload fun(self: DbcWorkspace_v335, name: '"AuctionHouse"'): dbc.Table.v335.AuctionHouse
---@overload fun(self: DbcWorkspace_v335, name: '"BankBagSlotPrices"'): dbc.Table.v335.BankBagSlotPrices
---@overload fun(self: DbcWorkspace_v335, name: '"BannedAddons"'): dbc.Table.v335.BannedAddons
---@overload fun(self: DbcWorkspace_v335, name: '"BarberShopStyle"'): dbc.Table.v335.BarberShopStyle
---@overload fun(self: DbcWorkspace_v335, name: '"BattlemasterList"'): dbc.Table.v335.BattlemasterList
---@overload fun(self: DbcWorkspace_v335, name: '"CameraShakes"'): dbc.Table.v335.CameraShakes
---@overload fun(self: DbcWorkspace_v335, name: '"Cfg_Categories"'): dbc.Table.v335.Cfg_Categories
---@overload fun(self: DbcWorkspace_v335, name: '"Cfg_Configs"'): dbc.Table.v335.Cfg_Configs
---@overload fun(self: DbcWorkspace_v335, name: '"CharBaseInfo"'): dbc.Table.v335.CharBaseInfo
---@overload fun(self: DbcWorkspace_v335, name: '"CharHairGeosets"'): dbc.Table.v335.CharHairGeosets
---@overload fun(self: DbcWorkspace_v335, name: '"CharHairTextures"'): dbc.Table.v335.CharHairTextures
---@overload fun(self: DbcWorkspace_v335, name: '"CharSections"'): dbc.Table.v335.CharSections
---@overload fun(self: DbcWorkspace_v335, name: '"CharStartOutfit"'): dbc.Table.v335.CharStartOutfit
---@overload fun(self: DbcWorkspace_v335, name: '"CharTitles"'): dbc.Table.v335.CharTitles
---@overload fun(self: DbcWorkspace_v335, name: '"CharVariations"'): dbc.Table.v335.CharVariations
---@overload fun(self: DbcWorkspace_v335, name: '"CharacterFacialHairStyles"'): dbc.Table.v335.CharacterFacialHairStyles
---@overload fun(self: DbcWorkspace_v335, name: '"ChatChannels"'): dbc.Table.v335.ChatChannels
---@overload fun(self: DbcWorkspace_v335, name: '"ChatProfanity"'): dbc.Table.v335.ChatProfanity
---@overload fun(self: DbcWorkspace_v335, name: '"ChrClasses"'): dbc.Table.v335.ChrClasses
---@overload fun(self: DbcWorkspace_v335, name: '"ChrRaces"'): dbc.Table.v335.ChrRaces
---@overload fun(self: DbcWorkspace_v335, name: '"CinematicCamera"'): dbc.Table.v335.CinematicCamera
---@overload fun(self: DbcWorkspace_v335, name: '"CinematicSequences"'): dbc.Table.v335.CinematicSequences
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureDisplayInfo"'): dbc.Table.v335.CreatureDisplayInfo
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureDisplayInfoExtra"'): dbc.Table.v335.CreatureDisplayInfoExtra
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureFamily"'): dbc.Table.v335.CreatureFamily
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureModelData"'): dbc.Table.v335.CreatureModelData
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureMovementInfo"'): dbc.Table.v335.CreatureMovementInfo
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureSoundData"'): dbc.Table.v335.CreatureSoundData
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureSpellData"'): dbc.Table.v335.CreatureSpellData
---@overload fun(self: DbcWorkspace_v335, name: '"CreatureType"'): dbc.Table.v335.CreatureType
---@overload fun(self: DbcWorkspace_v335, name: '"CurrencyCategory"'): dbc.Table.v335.CurrencyCategory
---@overload fun(self: DbcWorkspace_v335, name: '"CurrencyTypes"'): dbc.Table.v335.CurrencyTypes
---@overload fun(self: DbcWorkspace_v335, name: '"DanceMoves"'): dbc.Table.v335.DanceMoves
---@overload fun(self: DbcWorkspace_v335, name: '"DeathThudLookups"'): dbc.Table.v335.DeathThudLookups
---@overload fun(self: DbcWorkspace_v335, name: '"DeclinedWord"'): dbc.Table.v335.DeclinedWord
---@overload fun(self: DbcWorkspace_v335, name: '"DeclinedWordCases"'): dbc.Table.v335.DeclinedWordCases
---@overload fun(self: DbcWorkspace_v335, name: '"DestructibleModelData"'): dbc.Table.v335.DestructibleModelData
---@overload fun(self: DbcWorkspace_v335, name: '"DungeonEncounter"'): dbc.Table.v335.DungeonEncounter
---@overload fun(self: DbcWorkspace_v335, name: '"DungeonMap"'): dbc.Table.v335.DungeonMap
---@overload fun(self: DbcWorkspace_v335, name: '"DungeonMapChunk"'): dbc.Table.v335.DungeonMapChunk
---@overload fun(self: DbcWorkspace_v335, name: '"DurabilityCosts"'): dbc.Table.v335.DurabilityCosts
---@overload fun(self: DbcWorkspace_v335, name: '"DurabilityQuality"'): dbc.Table.v335.DurabilityQuality
---@overload fun(self: DbcWorkspace_v335, name: '"Emotes"'): dbc.Table.v335.Emotes
---@overload fun(self: DbcWorkspace_v335, name: '"EmotesText"'): dbc.Table.v335.EmotesText
---@overload fun(self: DbcWorkspace_v335, name: '"EmotesTextData"'): dbc.Table.v335.EmotesTextData
---@overload fun(self: DbcWorkspace_v335, name: '"EmotesTextSound"'): dbc.Table.v335.EmotesTextSound
---@overload fun(self: DbcWorkspace_v335, name: '"EnvironmentalDamage"'): dbc.Table.v335.EnvironmentalDamage
---@overload fun(self: DbcWorkspace_v335, name: '"Exhaustion"'): dbc.Table.v335.Exhaustion
---@overload fun(self: DbcWorkspace_v335, name: '"Faction"'): dbc.Table.v335.Faction
---@overload fun(self: DbcWorkspace_v335, name: '"FactionGroup"'): dbc.Table.v335.FactionGroup
---@overload fun(self: DbcWorkspace_v335, name: '"FactionTemplate"'): dbc.Table.v335.FactionTemplate
---@overload fun(self: DbcWorkspace_v335, name: '"FileData"'): dbc.Table.v335.FileData
---@overload fun(self: DbcWorkspace_v335, name: '"FootprintTextures"'): dbc.Table.v335.FootprintTextures
---@overload fun(self: DbcWorkspace_v335, name: '"FootstepTerrainLookup"'): dbc.Table.v335.FootstepTerrainLookup
---@overload fun(self: DbcWorkspace_v335, name: '"GMSurveyAnswers"'): dbc.Table.v335.GMSurveyAnswers
---@overload fun(self: DbcWorkspace_v335, name: '"GMSurveyCurrentSurvey"'): dbc.Table.v335.GMSurveyCurrentSurvey
---@overload fun(self: DbcWorkspace_v335, name: '"GMSurveyQuestions"'): dbc.Table.v335.GMSurveyQuestions
---@overload fun(self: DbcWorkspace_v335, name: '"GMSurveySurveys"'): dbc.Table.v335.GMSurveySurveys
---@overload fun(self: DbcWorkspace_v335, name: '"GMTicketCategory"'): dbc.Table.v335.GMTicketCategory
---@overload fun(self: DbcWorkspace_v335, name: '"GameObjectArtKit"'): dbc.Table.v335.GameObjectArtKit
---@overload fun(self: DbcWorkspace_v335, name: '"GameObjectDisplayInfo"'): dbc.Table.v335.GameObjectDisplayInfo
---@overload fun(self: DbcWorkspace_v335, name: '"GameTables"'): dbc.Table.v335.GameTables
---@overload fun(self: DbcWorkspace_v335, name: '"GameTips"'): dbc.Table.v335.GameTips
---@overload fun(self: DbcWorkspace_v335, name: '"GemProperties"'): dbc.Table.v335.GemProperties
---@overload fun(self: DbcWorkspace_v335, name: '"GlyphProperties"'): dbc.Table.v335.GlyphProperties
---@overload fun(self: DbcWorkspace_v335, name: '"GlyphSlot"'): dbc.Table.v335.GlyphSlot
---@overload fun(self: DbcWorkspace_v335, name: '"GroundEffectDoodad"'): dbc.Table.v335.GroundEffectDoodad
---@overload fun(self: DbcWorkspace_v335, name: '"GroundEffectTexture"'): dbc.Table.v335.GroundEffectTexture
---@overload fun(self: DbcWorkspace_v335, name: '"HelmetGeosetVisData"'): dbc.Table.v335.HelmetGeosetVisData
---@overload fun(self: DbcWorkspace_v335, name: '"HolidayDescriptions"'): dbc.Table.v335.HolidayDescriptions
---@overload fun(self: DbcWorkspace_v335, name: '"HolidayNames"'): dbc.Table.v335.HolidayNames
---@overload fun(self: DbcWorkspace_v335, name: '"Holidays"'): dbc.Table.v335.Holidays
---@overload fun(self: DbcWorkspace_v335, name: '"Item"'): dbc.Table.v335.Item
---@overload fun(self: DbcWorkspace_v335, name: '"ItemBagFamily"'): dbc.Table.v335.ItemBagFamily
---@overload fun(self: DbcWorkspace_v335, name: '"ItemClass"'): dbc.Table.v335.ItemClass
---@overload fun(self: DbcWorkspace_v335, name: '"ItemCondExtCosts"'): dbc.Table.v335.ItemCondExtCosts
---@overload fun(self: DbcWorkspace_v335, name: '"ItemDisplayInfo"'): dbc.Table.v335.ItemDisplayInfo
---@overload fun(self: DbcWorkspace_v335, name: '"ItemExtendedCost"'): dbc.Table.v335.ItemExtendedCost
---@overload fun(self: DbcWorkspace_v335, name: '"ItemGroupSounds"'): dbc.Table.v335.ItemGroupSounds
---@overload fun(self: DbcWorkspace_v335, name: '"ItemLimitCategory"'): dbc.Table.v335.ItemLimitCategory
---@overload fun(self: DbcWorkspace_v335, name: '"ItemPetFood"'): dbc.Table.v335.ItemPetFood
---@overload fun(self: DbcWorkspace_v335, name: '"ItemPurchaseGroup"'): dbc.Table.v335.ItemPurchaseGroup
---@overload fun(self: DbcWorkspace_v335, name: '"ItemRandomProperties"'): dbc.Table.v335.ItemRandomProperties
---@overload fun(self: DbcWorkspace_v335, name: '"ItemRandomSuffix"'): dbc.Table.v335.ItemRandomSuffix
---@overload fun(self: DbcWorkspace_v335, name: '"ItemSet"'): dbc.Table.v335.ItemSet
---@overload fun(self: DbcWorkspace_v335, name: '"ItemSubClass"'): dbc.Table.v335.ItemSubClass
---@overload fun(self: DbcWorkspace_v335, name: '"ItemSubClassMask"'): dbc.Table.v335.ItemSubClassMask
---@overload fun(self: DbcWorkspace_v335, name: '"ItemVisualEffects"'): dbc.Table.v335.ItemVisualEffects
---@overload fun(self: DbcWorkspace_v335, name: '"ItemVisuals"'): dbc.Table.v335.ItemVisuals
---@overload fun(self: DbcWorkspace_v335, name: '"LFGDungeonExpansion"'): dbc.Table.v335.LFGDungeonExpansion
---@overload fun(self: DbcWorkspace_v335, name: '"LFGDungeonGroup"'): dbc.Table.v335.LFGDungeonGroup
---@overload fun(self: DbcWorkspace_v335, name: '"LFGDungeons"'): dbc.Table.v335.LFGDungeons
---@overload fun(self: DbcWorkspace_v335, name: '"LanguageWords"'): dbc.Table.v335.LanguageWords
---@overload fun(self: DbcWorkspace_v335, name: '"Languages"'): dbc.Table.v335.Languages
---@overload fun(self: DbcWorkspace_v335, name: '"Light"'): dbc.Table.v335.Light
---@overload fun(self: DbcWorkspace_v335, name: '"LightFloatBand"'): dbc.Table.v335.LightFloatBand
---@overload fun(self: DbcWorkspace_v335, name: '"LightIntBand"'): dbc.Table.v335.LightIntBand
---@overload fun(self: DbcWorkspace_v335, name: '"LightParams"'): dbc.Table.v335.LightParams
---@overload fun(self: DbcWorkspace_v335, name: '"LightSkybox"'): dbc.Table.v335.LightSkybox
---@overload fun(self: DbcWorkspace_v335, name: '"LiquidMaterial"'): dbc.Table.v335.LiquidMaterial
---@overload fun(self: DbcWorkspace_v335, name: '"LiquidType"'): dbc.Table.v335.LiquidType
---@overload fun(self: DbcWorkspace_v335, name: '"LoadingScreenTaxiSplines"'): dbc.Table.v335.LoadingScreenTaxiSplines
---@overload fun(self: DbcWorkspace_v335, name: '"LoadingScreens"'): dbc.Table.v335.LoadingScreens
---@overload fun(self: DbcWorkspace_v335, name: '"Lock"'): dbc.Table.v335.Lock
---@overload fun(self: DbcWorkspace_v335, name: '"LockType"'): dbc.Table.v335.LockType
---@overload fun(self: DbcWorkspace_v335, name: '"MailTemplate"'): dbc.Table.v335.MailTemplate
---@overload fun(self: DbcWorkspace_v335, name: '"Map"'): dbc.Table.v335.Map
---@overload fun(self: DbcWorkspace_v335, name: '"MapDifficulty"'): dbc.Table.v335.MapDifficulty
---@overload fun(self: DbcWorkspace_v335, name: '"Material"'): dbc.Table.v335.Material
---@overload fun(self: DbcWorkspace_v335, name: '"Movie"'): dbc.Table.v335.Movie
---@overload fun(self: DbcWorkspace_v335, name: '"MovieFileData"'): dbc.Table.v335.MovieFileData
---@overload fun(self: DbcWorkspace_v335, name: '"MovieVariation"'): dbc.Table.v335.MovieVariation
---@overload fun(self: DbcWorkspace_v335, name: '"NPCSounds"'): dbc.Table.v335.NPCSounds
---@overload fun(self: DbcWorkspace_v335, name: '"NameGen"'): dbc.Table.v335.NameGen
---@overload fun(self: DbcWorkspace_v335, name: '"NamesProfanity"'): dbc.Table.v335.NamesProfanity
---@overload fun(self: DbcWorkspace_v335, name: '"NamesReserved"'): dbc.Table.v335.NamesReserved
---@overload fun(self: DbcWorkspace_v335, name: '"ObjectEffect"'): dbc.Table.v335.ObjectEffect
---@overload fun(self: DbcWorkspace_v335, name: '"ObjectEffectGroup"'): dbc.Table.v335.ObjectEffectGroup
---@overload fun(self: DbcWorkspace_v335, name: '"ObjectEffectModifier"'): dbc.Table.v335.ObjectEffectModifier
---@overload fun(self: DbcWorkspace_v335, name: '"ObjectEffectPackage"'): dbc.Table.v335.ObjectEffectPackage
---@overload fun(self: DbcWorkspace_v335, name: '"ObjectEffectPackageElem"'): dbc.Table.v335.ObjectEffectPackageElem
---@overload fun(self: DbcWorkspace_v335, name: '"OverrideSpellData"'): dbc.Table.v335.OverrideSpellData
---@overload fun(self: DbcWorkspace_v335, name: '"PVPDifficulty"'): dbc.Table.v335.PVPDifficulty
---@overload fun(self: DbcWorkspace_v335, name: '"Package"'): dbc.Table.v335.Package
---@overload fun(self: DbcWorkspace_v335, name: '"PageTextMaterial"'): dbc.Table.v335.PageTextMaterial
---@overload fun(self: DbcWorkspace_v335, name: '"PaperDollItemFrame"'): dbc.Table.v335.PaperDollItemFrame
---@overload fun(self: DbcWorkspace_v335, name: '"ParticleColor"'): dbc.Table.v335.ParticleColor
---@overload fun(self: DbcWorkspace_v335, name: '"PetPersonality"'): dbc.Table.v335.PetPersonality
---@overload fun(self: DbcWorkspace_v335, name: '"PetitionType"'): dbc.Table.v335.PetitionType
---@overload fun(self: DbcWorkspace_v335, name: '"PowerDisplay"'): dbc.Table.v335.PowerDisplay
---@overload fun(self: DbcWorkspace_v335, name: '"QuestFactionReward"'): dbc.Table.v335.QuestFactionReward
---@overload fun(self: DbcWorkspace_v335, name: '"QuestInfo"'): dbc.Table.v335.QuestInfo
---@overload fun(self: DbcWorkspace_v335, name: '"QuestSort"'): dbc.Table.v335.QuestSort
---@overload fun(self: DbcWorkspace_v335, name: '"QuestXP"'): dbc.Table.v335.QuestXP
---@overload fun(self: DbcWorkspace_v335, name: '"RandPropPoints"'): dbc.Table.v335.RandPropPoints
---@overload fun(self: DbcWorkspace_v335, name: '"Resistances"'): dbc.Table.v335.Resistances
---@overload fun(self: DbcWorkspace_v335, name: '"ScalingStatDistribution"'): dbc.Table.v335.ScalingStatDistribution
---@overload fun(self: DbcWorkspace_v335, name: '"ScalingStatValues"'): dbc.Table.v335.ScalingStatValues
---@overload fun(self: DbcWorkspace_v335, name: '"ScreenEffect"'): dbc.Table.v335.ScreenEffect
---@overload fun(self: DbcWorkspace_v335, name: '"ServerMessages"'): dbc.Table.v335.ServerMessages
---@overload fun(self: DbcWorkspace_v335, name: '"SheatheSoundLookups"'): dbc.Table.v335.SheatheSoundLookups
---@overload fun(self: DbcWorkspace_v335, name: '"SkillCostsData"'): dbc.Table.v335.SkillCostsData
---@overload fun(self: DbcWorkspace_v335, name: '"SkillLine"'): dbc.Table.v335.SkillLine
---@overload fun(self: DbcWorkspace_v335, name: '"SkillLineAbility"'): dbc.Table.v335.SkillLineAbility
---@overload fun(self: DbcWorkspace_v335, name: '"SkillLineCategory"'): dbc.Table.v335.SkillLineCategory
---@overload fun(self: DbcWorkspace_v335, name: '"SkillRaceClassInfo"'): dbc.Table.v335.SkillRaceClassInfo
---@overload fun(self: DbcWorkspace_v335, name: '"SkillTiers"'): dbc.Table.v335.SkillTiers
---@overload fun(self: DbcWorkspace_v335, name: '"SoundAmbience"'): dbc.Table.v335.SoundAmbience
---@overload fun(self: DbcWorkspace_v335, name: '"SoundEmitters"'): dbc.Table.v335.SoundEmitters
---@overload fun(self: DbcWorkspace_v335, name: '"SoundEntries"'): dbc.Table.v335.SoundEntries
---@overload fun(self: DbcWorkspace_v335, name: '"SoundEntriesAdvanced"'): dbc.Table.v335.SoundEntriesAdvanced
---@overload fun(self: DbcWorkspace_v335, name: '"SoundFilter"'): dbc.Table.v335.SoundFilter
---@overload fun(self: DbcWorkspace_v335, name: '"SoundFilterElem"'): dbc.Table.v335.SoundFilterElem
---@overload fun(self: DbcWorkspace_v335, name: '"SoundProviderPreferences"'): dbc.Table.v335.SoundProviderPreferences
---@overload fun(self: DbcWorkspace_v335, name: '"SoundSamplePreferences"'): dbc.Table.v335.SoundSamplePreferences
---@overload fun(self: DbcWorkspace_v335, name: '"SoundWaterType"'): dbc.Table.v335.SoundWaterType
---@overload fun(self: DbcWorkspace_v335, name: '"SpamMessages"'): dbc.Table.v335.SpamMessages
---@overload fun(self: DbcWorkspace_v335, name: '"Spell"'): dbc.Table.v335.Spell
---@overload fun(self: DbcWorkspace_v335, name: '"SpellCastTimes"'): dbc.Table.v335.SpellCastTimes
---@overload fun(self: DbcWorkspace_v335, name: '"SpellCategory"'): dbc.Table.v335.SpellCategory
---@overload fun(self: DbcWorkspace_v335, name: '"SpellChainEffects"'): dbc.Table.v335.SpellChainEffects
---@overload fun(self: DbcWorkspace_v335, name: '"SpellDescriptionVariables"'): dbc.Table.v335.SpellDescriptionVariables
---@overload fun(self: DbcWorkspace_v335, name: '"SpellDifficulty"'): dbc.Table.v335.SpellDifficulty
---@overload fun(self: DbcWorkspace_v335, name: '"SpellDispelType"'): dbc.Table.v335.SpellDispelType
---@overload fun(self: DbcWorkspace_v335, name: '"SpellDuration"'): dbc.Table.v335.SpellDuration
---@overload fun(self: DbcWorkspace_v335, name: '"SpellEffectCameraShakes"'): dbc.Table.v335.SpellEffectCameraShakes
---@overload fun(self: DbcWorkspace_v335, name: '"SpellFocusObject"'): dbc.Table.v335.SpellFocusObject
---@overload fun(self: DbcWorkspace_v335, name: '"SpellIcon"'): dbc.Table.v335.SpellIcon
---@overload fun(self: DbcWorkspace_v335, name: '"SpellItemEnchantment"'): dbc.Table.v335.SpellItemEnchantment
---@overload fun(self: DbcWorkspace_v335, name: '"SpellItemEnchantmentCondition"'): dbc.Table.v335.SpellItemEnchantmentCondition
---@overload fun(self: DbcWorkspace_v335, name: '"SpellMechanic"'): dbc.Table.v335.SpellMechanic
---@overload fun(self: DbcWorkspace_v335, name: '"SpellMissile"'): dbc.Table.v335.SpellMissile
---@overload fun(self: DbcWorkspace_v335, name: '"SpellMissileMotion"'): dbc.Table.v335.SpellMissileMotion
---@overload fun(self: DbcWorkspace_v335, name: '"SpellRadius"'): dbc.Table.v335.SpellRadius
---@overload fun(self: DbcWorkspace_v335, name: '"SpellRange"'): dbc.Table.v335.SpellRange
---@overload fun(self: DbcWorkspace_v335, name: '"SpellRuneCost"'): dbc.Table.v335.SpellRuneCost
---@overload fun(self: DbcWorkspace_v335, name: '"SpellShapeshiftForm"'): dbc.Table.v335.SpellShapeshiftForm
---@overload fun(self: DbcWorkspace_v335, name: '"SpellVisual"'): dbc.Table.v335.SpellVisual
---@overload fun(self: DbcWorkspace_v335, name: '"SpellVisualEffectName"'): dbc.Table.v335.SpellVisualEffectName
---@overload fun(self: DbcWorkspace_v335, name: '"SpellVisualKit"'): dbc.Table.v335.SpellVisualKit
---@overload fun(self: DbcWorkspace_v335, name: '"SpellVisualKitAreaModel"'): dbc.Table.v335.SpellVisualKitAreaModel
---@overload fun(self: DbcWorkspace_v335, name: '"SpellVisualKitModelAttach"'): dbc.Table.v335.SpellVisualKitModelAttach
---@overload fun(self: DbcWorkspace_v335, name: '"SpellVisualPrecastTransitions"'): dbc.Table.v335.SpellVisualPrecastTransitions
---@overload fun(self: DbcWorkspace_v335, name: '"StableSlotPrices"'): dbc.Table.v335.StableSlotPrices
---@overload fun(self: DbcWorkspace_v335, name: '"Startup_Strings"'): dbc.Table.v335.Startup_Strings
---@overload fun(self: DbcWorkspace_v335, name: '"Stationery"'): dbc.Table.v335.Stationery
---@overload fun(self: DbcWorkspace_v335, name: '"StringLookups"'): dbc.Table.v335.StringLookups
---@overload fun(self: DbcWorkspace_v335, name: '"SummonProperties"'): dbc.Table.v335.SummonProperties
---@overload fun(self: DbcWorkspace_v335, name: '"Talent"'): dbc.Table.v335.Talent
---@overload fun(self: DbcWorkspace_v335, name: '"TalentTab"'): dbc.Table.v335.TalentTab
---@overload fun(self: DbcWorkspace_v335, name: '"TaxiNodes"'): dbc.Table.v335.TaxiNodes
---@overload fun(self: DbcWorkspace_v335, name: '"TaxiPath"'): dbc.Table.v335.TaxiPath
---@overload fun(self: DbcWorkspace_v335, name: '"TaxiPathNode"'): dbc.Table.v335.TaxiPathNode
---@overload fun(self: DbcWorkspace_v335, name: '"TeamContributionPoints"'): dbc.Table.v335.TeamContributionPoints
---@overload fun(self: DbcWorkspace_v335, name: '"TerrainType"'): dbc.Table.v335.TerrainType
---@overload fun(self: DbcWorkspace_v335, name: '"TerrainTypeSounds"'): dbc.Table.v335.TerrainTypeSounds
---@overload fun(self: DbcWorkspace_v335, name: '"TotemCategory"'): dbc.Table.v335.TotemCategory
---@overload fun(self: DbcWorkspace_v335, name: '"TransportAnimation"'): dbc.Table.v335.TransportAnimation
---@overload fun(self: DbcWorkspace_v335, name: '"TransportPhysics"'): dbc.Table.v335.TransportPhysics
---@overload fun(self: DbcWorkspace_v335, name: '"TransportRotation"'): dbc.Table.v335.TransportRotation
---@overload fun(self: DbcWorkspace_v335, name: '"UISoundLookups"'): dbc.Table.v335.UISoundLookups
---@overload fun(self: DbcWorkspace_v335, name: '"UnitBlood"'): dbc.Table.v335.UnitBlood
---@overload fun(self: DbcWorkspace_v335, name: '"UnitBloodLevels"'): dbc.Table.v335.UnitBloodLevels
---@overload fun(self: DbcWorkspace_v335, name: '"Vehicle"'): dbc.Table.v335.Vehicle
---@overload fun(self: DbcWorkspace_v335, name: '"VehicleSeat"'): dbc.Table.v335.VehicleSeat
---@overload fun(self: DbcWorkspace_v335, name: '"VehicleUIIndSeat"'): dbc.Table.v335.VehicleUIIndSeat
---@overload fun(self: DbcWorkspace_v335, name: '"VehicleUIIndicator"'): dbc.Table.v335.VehicleUIIndicator
---@overload fun(self: DbcWorkspace_v335, name: '"VideoHardware"'): dbc.Table.v335.VideoHardware
---@overload fun(self: DbcWorkspace_v335, name: '"VocalUISounds"'): dbc.Table.v335.VocalUISounds
---@overload fun(self: DbcWorkspace_v335, name: '"WMOAreaTable"'): dbc.Table.v335.WMOAreaTable
---@overload fun(self: DbcWorkspace_v335, name: '"WeaponImpactSounds"'): dbc.Table.v335.WeaponImpactSounds
---@overload fun(self: DbcWorkspace_v335, name: '"WeaponSwingSounds2"'): dbc.Table.v335.WeaponSwingSounds2
---@overload fun(self: DbcWorkspace_v335, name: '"Weather"'): dbc.Table.v335.Weather
---@overload fun(self: DbcWorkspace_v335, name: '"WorldChunkSounds"'): dbc.Table.v335.WorldChunkSounds
---@overload fun(self: DbcWorkspace_v335, name: '"WorldMapArea"'): dbc.Table.v335.WorldMapArea
---@overload fun(self: DbcWorkspace_v335, name: '"WorldMapContinent"'): dbc.Table.v335.WorldMapContinent
---@overload fun(self: DbcWorkspace_v335, name: '"WorldMapOverlay"'): dbc.Table.v335.WorldMapOverlay
---@overload fun(self: DbcWorkspace_v335, name: '"WorldMapTransforms"'): dbc.Table.v335.WorldMapTransforms
---@overload fun(self: DbcWorkspace_v335, name: '"WorldSafeLocs"'): dbc.Table.v335.WorldSafeLocs
---@overload fun(self: DbcWorkspace_v335, name: '"WorldStateUI"'): dbc.Table.v335.WorldStateUI
---@overload fun(self: DbcWorkspace_v335, name: '"WorldStateZoneSounds"'): dbc.Table.v335.WorldStateZoneSounds
---@overload fun(self: DbcWorkspace_v335, name: '"WowError_Strings"'): dbc.Table.v335.WowError_Strings
---@overload fun(self: DbcWorkspace_v335, name: '"ZoneIntroMusicTable"'): dbc.Table.v335.ZoneIntroMusicTable
---@overload fun(self: DbcWorkspace_v335, name: '"ZoneMusic"'): dbc.Table.v335.ZoneMusic
---@overload fun(self: DbcWorkspace_v335, name: '"gtBarberShopCostBase"'): dbc.Table.v335.gtBarberShopCostBase
---@overload fun(self: DbcWorkspace_v335, name: '"gtChanceToMeleeCrit"'): dbc.Table.v335.gtChanceToMeleeCrit
---@overload fun(self: DbcWorkspace_v335, name: '"gtChanceToMeleeCritBase"'): dbc.Table.v335.gtChanceToMeleeCritBase
---@overload fun(self: DbcWorkspace_v335, name: '"gtChanceToSpellCrit"'): dbc.Table.v335.gtChanceToSpellCrit
---@overload fun(self: DbcWorkspace_v335, name: '"gtChanceToSpellCritBase"'): dbc.Table.v335.gtChanceToSpellCritBase
---@overload fun(self: DbcWorkspace_v335, name: '"gtCombatRatings"'): dbc.Table.v335.gtCombatRatings
---@overload fun(self: DbcWorkspace_v335, name: '"gtNPCManaCostScaler"'): dbc.Table.v335.gtNPCManaCostScaler
---@overload fun(self: DbcWorkspace_v335, name: '"gtOCTClassCombatRatingScalar"'): dbc.Table.v335.gtOCTClassCombatRatingScalar
---@overload fun(self: DbcWorkspace_v335, name: '"gtOCTRegenHP"'): dbc.Table.v335.gtOCTRegenHP
---@overload fun(self: DbcWorkspace_v335, name: '"gtOCTRegenMP"'): dbc.Table.v335.gtOCTRegenMP
---@overload fun(self: DbcWorkspace_v335, name: '"gtRegenHPPerSpt"'): dbc.Table.v335.gtRegenHPPerSpt
---@overload fun(self: DbcWorkspace_v335, name: '"gtRegenMPPerSpt"'): dbc.Table.v335.gtRegenMPPerSpt
function DbcWorkspace_v335:Create(name) end

---@class dbc
---@overload fun(options: { build: '"3.3.5.12340"'|'"3.3.5"', source?: string, out?: string }): DbcWorkspace_v335
---@overload fun(build_or_source: '"3.3.5.12340"'|'"3.3.5"'): DbcWorkspace_v335
function dbc.Workspace(options_or_source, output_dir) end

return {}
