---@meta
-- Core API definitions for LuaLS.

---@class RowProxy
---@field _file DbcFile
---@field _table DbcTable|nil
---@field _row integer
---@field _schema table
---@field GetID fun(self: RowProxy): integer
---@field SetID fun(self: RowProxy, id: integer): RowProxy
---@field GetIndex fun(self: RowProxy): integer
---@field GetFile fun(self: RowProxy): DbcFile
---@field GetTable fun(self: RowProxy): DbcTable|nil
---@field GetSchema fun(self: RowProxy): table
---@field IsValid fun(self: RowProxy): boolean
---@field Clone fun(self: RowProxy, new_id?: integer): RowProxy
---@field ToTable fun(self: RowProxy): table<string, any>
---@field FromTable fun(self: RowProxy, data: table<string, any>): RowProxy
---@field Resolve fun(self: RowProxy, field_name: string): RowProxy|nil
---@field ResolveRelation fun(self: RowProxy, target_table: string, foreign_id: integer): RowProxy|nil
---@field GetRelations fun(self: RowProxy): table[]
---@field GetRelated fun(self: RowProxy, target_table_or_field: string): RowProxy|nil
---@field CreateRelated fun(self: RowProxy, target_table_or_field: string, row_data_or_id?: table|integer): RowProxy
---@field GetChildren fun(self: RowProxy, child_table_name: string, child_field_name?: string): RowProxy[]

---@class DbcFile
---@field origin string
---@field record_count integer
---@field field_count integer
---@field record_size integer
---@field records any
---@field str_orig string
---@field str_extra string[]
---@field str_extra_len integer
---@field dirty boolean
---@field schema table
---@field capacity integer
---@field by_name table<string, table>
---@field _workspace DbcWorkspace|nil
---@field _session DbcWorkspace|nil
---@field GetString fun(self: DbcFile, offset: integer): string
---@field InternString fun(self: DbcFile, text: string): integer
---@field GetAddress fun(self: DbcFile, row: integer, offset: integer): any
---@field GetField fun(self: DbcFile, name: string): table
---@field GetIdOffset fun(self: DbcFile): integer
---@field Reserve fun(self: DbcFile, want: integer)
---@field AppendRow fun(self: DbcFile): integer
---@field Serialize fun(self: DbcFile): string
---@field Save fun(self: DbcFile, path: string): integer

---@class DbcTable
---@field _file DbcFile
---@field _workspace DbcWorkspace|nil
---@field _session DbcWorkspace|nil
---@field _proxies table<integer, RowProxy>
---@field _id_map table<integer, integer>
---@field RebuildIndex fun(self: DbcTable)
---@field GetFile fun(self: DbcTable): DbcFile
---@field GetSchema fun(self: DbcTable): table
---@field GetWorkspace fun(self: DbcTable): DbcWorkspace|nil
---@field Count fun(self: DbcTable): integer
---@field GetMaxId fun(self: DbcTable): integer
---@field GetNextId fun(self: DbcTable): integer
---@field GetRow fun(self: DbcTable, row_index: integer): RowProxy
---@field FindById fun(self: DbcTable, id: integer): RowProxy|nil
---@field GetById fun(self: DbcTable, id: integer): RowProxy|nil
---@field NewRow fun(self: DbcTable, id?: integer): RowProxy
---@field Create fun(self: DbcTable, id?: integer): RowProxy
---@field CreateNext fun(self: DbcTable, data?: table): RowProxy
---@field CloneRow fun(self: DbcTable, row_or_id: integer|RowProxy, new_id?: integer): RowProxy
---@field GetAllRows fun(self: DbcTable): RowProxy[]
---@field Query fun(self: DbcTable): dbc.Query<RowProxy>
---@field Rows fun(self: DbcTable): fun(): integer, RowProxy
---@field Save fun(self: DbcTable, path?: string): integer
---@field GetRelations fun(self: DbcTable): table[]
---@field GetInboundRelations fun(self: DbcTable): table[]

---@class DbcWorkspace
---@field source_dir string
---@field output_dir string
---@field tables table<string, DbcTable>
---@field GetSourceDir fun(self: DbcWorkspace): string
---@field SetSourceDir fun(self: DbcWorkspace, path: string): DbcWorkspace
---@field GetOutputDir fun(self: DbcWorkspace): string
---@field SetOutputDir fun(self: DbcWorkspace, path: string): DbcWorkspace
---@field GetTable fun(self: DbcWorkspace, name: dbc.TableName|string): DbcTable|nil
---@field Open fun(self: DbcWorkspace, path_or_name: dbc.TableName|string, schema_name?: dbc.TableName|string): DbcTable
---@field Create fun(self: DbcWorkspace, schema_name: dbc.TableName|string): DbcTable
---@field Save fun(self: DbcWorkspace, name_or_table: string|DbcTable, custom_path?: string): integer
---@field SaveAll fun(self: DbcWorkspace, destination_dir?: string): string[]
---@field GetAllTables fun(self: DbcWorkspace): table<string, DbcTable>

---@alias DbcSession DbcWorkspace

---@class DbcRelations
---@field Get fun(table_name: string): table[]
---@field GetInbound fun(table_name: string): table[]
---@field Find fun(source_table: string, target_table_or_field: string): table|nil
---@field Define fun(source_table: string, field: string, target_table: string, target_field?: string)
---@field GetCatalog fun(): table

---@class dbc
---@field File DbcFile
---@field Table DbcTable
---@field RowProxy RowProxy
---@field Query fun(source: any): dbc.Query<any>
---@field Schemas table<string, table>
---@field Enums dbc.EnumsRegistry
---@field Relations DbcRelations
---@field Workspace fun(options_or_source?: table|string, output_dir?: string): DbcWorkspace
---@field Database fun(options_or_source?: table|string, output_dir?: string): DbcWorkspace
---@field Session fun(options_or_source?: table|string, output_dir?: string): DbcWorkspace
---@field Open fun(path: string, schema_name?: dbc.TableName|string): DbcTable
---@field Create fun(schema_name: dbc.TableName|string): DbcTable
---@field GetRelations fun(schema_name: dbc.TableName|string): table[]

---@class dbc.Query<T>
---@field Where fun(self: dbc.Query<T>, predicate: fun(item: T, index: integer): boolean): dbc.Query<T>
---@field Select fun(self: dbc.Query<T>, selector: fun(item: T, index: integer): any): dbc.Query<any>
---@field OrderBy fun(self: dbc.Query<T>, key_selector: fun(item: T): any, descending?: boolean): dbc.Query<T>
---@field OrderByDescending fun(self: dbc.Query<T>, key_selector: fun(item: T): any): dbc.Query<T>
---@field Skip fun(self: dbc.Query<T>, count: integer): dbc.Query<T>
---@field Take fun(self: dbc.Query<T>, count: integer): dbc.Query<T>
---@field Distinct fun(self: dbc.Query<T>, key_selector?: fun(item: T): any): dbc.Query<T>
---@field ToList fun(self: dbc.Query<T>): T[]
---@field First fun(self: dbc.Query<T>, predicate?: fun(item: T): boolean): T
---@field FirstOrDefault fun(self: dbc.Query<T>, predicate?: fun(item: T): boolean, default_val?: any): T|any
---@field Last fun(self: dbc.Query<T>, predicate?: fun(item: T): boolean): T
---@field LastOrDefault fun(self: dbc.Query<T>, predicate?: fun(item: T): boolean, default_val?: any): T|any
---@field Single fun(self: dbc.Query<T>, predicate?: fun(item: T): boolean): T
---@field Any fun(self: dbc.Query<T>, predicate?: fun(item: T): boolean): boolean
---@field All fun(self: dbc.Query<T>, predicate: fun(item: T): boolean): boolean
---@field Count fun(self: dbc.Query<T>, predicate?: fun(item: T): boolean): integer
---@field Sum fun(self: dbc.Query<T>, selector?: fun(item: T): number): number
---@field Average fun(self: dbc.Query<T>, selector?: fun(item: T): number): number
---@field Min fun(self: dbc.Query<T>, selector?: fun(item: T): any): any
---@field Max fun(self: dbc.Query<T>, selector?: fun(item: T): any): any
---@field Contains fun(self: dbc.Query<T>, target: any): boolean
---@field ForEach fun(self: dbc.Query<T>, action: fun(item: T, index: integer)): dbc.Query<T>
---@field ToDictionary fun(self: dbc.Query<T>, key_selector: fun(item: T): any, value_selector?: fun(item: T): any): table
---@field GroupBy fun(self: dbc.Query<T>, key_selector: fun(item: T): any): table[]
