return {
  name = "CreatureType",
  kind = "enum",
  values = {
    NONE = 0,
    BEAST = 1,
    DRAGONKIN = 2,
    DEMON = 3,
    ELEMENTAL = 4,
    GIANT = 5,
    UNDEAD = 6,
    HUMANOID = 7,
    CRITTER = 8,
    MECHANICAL = 9,
    NOT_SPECIFIED = 10,
    TOTEM = 11,
    NON_COMBAT_PET = 12,
    GAS_CLOUD = 13,
    WILD_PET = 14,
    ABERRATION = 15,
  },
  names = {
    [0] = "NONE",
    [1] = "BEAST",
    [2] = "DRAGONKIN",
    [3] = "DEMON",
    [4] = "ELEMENTAL",
    [5] = "GIANT",
    [6] = "UNDEAD",
    [7] = "HUMANOID",
    [8] = "CRITTER",
    [9] = "MECHANICAL",
    [10] = "NOT_SPECIFIED",
    [11] = "TOTEM",
    [12] = "NON_COMBAT_PET",
    [13] = "GAS_CLOUD",
    [14] = "WILD_PET",
    [15] = "ABERRATION",
  },
}
