return {
  name = "DispelType",
  kind = "enum",
  values = {
    DISPEL_NONE = 0,
    DISPEL_MAGIC = 1,
    DISPEL_CURSE = 2,
    DISPEL_DISEASE = 3,
    DISPEL_POISON = 4,
    DISPEL_STEALTH = 5,
    DISPEL_INVISIBILITY = 6,
    DISPEL_ALL = 7,
    DISPEL_SPE_NPC_ONLY = 8,
    DISPEL_ENRAGE = 9,
    DISPEL_ZG_TICKET = 10,
    DESPEL_OLD_UNUSED = 11,
  },
  names = {
    [0] = "DISPEL_NONE",
    [1] = "DISPEL_MAGIC",
    [2] = "DISPEL_CURSE",
    [3] = "DISPEL_DISEASE",
    [4] = "DISPEL_POISON",
    [5] = "DISPEL_STEALTH",
    [6] = "DISPEL_INVISIBILITY",
    [7] = "DISPEL_ALL",
    [8] = "DISPEL_SPE_NPC_ONLY",
    [9] = "DISPEL_ENRAGE",
    [10] = "DISPEL_ZG_TICKET",
    [11] = "DESPEL_OLD_UNUSED",
  },
}
