return {
  name = "FactionTemplateValues",
  kind = "enum",
  values = {
    NEUTRAL_NON_AGGRESSIVE = 7,
    STORMWIND = 11,
    NEUTRAL_HOSTILE = 21,
    NEUTRAL_PASSIVE = 35,
    IRONFORGE = 57,
    GNOMEREGAN = 64,
    RATCHET = 69,
    UNDERCITY = 71,
    DARNASSUS = 79,
    ORGRIMMAR = 85,
    THUNDER_BLUFF = 105,
    BLOODSAIL_BUCCANEERS = 119,
    BOOTY_BAY = 121,
    DARKSPEAR_TROLLS = 126,
    GADGETZAN = 474,
    CENARION_CIRCLE = 994,
    SILVERMOON = 1604,
    EXODAR = 1639,
    SHATAR = 1741,
    KIRIN_TOR = 2007,
  },
  names = {
    [7] = "NEUTRAL_NON_AGGRESSIVE",
    [11] = "STORMWIND",
    [21] = "NEUTRAL_HOSTILE",
    [35] = "NEUTRAL_PASSIVE",
    [57] = "IRONFORGE",
    [64] = "GNOMEREGAN",
    [69] = "RATCHET",
    [71] = "UNDERCITY",
    [79] = "DARNASSUS",
    [85] = "ORGRIMMAR",
    [105] = "THUNDER_BLUFF",
    [119] = "BLOODSAIL_BUCCANEERS",
    [121] = "BOOTY_BAY",
    [126] = "DARKSPEAR_TROLLS",
    [474] = "GADGETZAN",
    [994] = "CENARION_CIRCLE",
    [1604] = "SILVERMOON",
    [1639] = "EXODAR",
    [1741] = "SHATAR",
    [2007] = "KIRIN_TOR",
  },
}
