return {
  name = "GossipIcon",
  kind = "enum",
  values = {
    CHAT = 0,
    VENDOR = 1,
    TAXI = 2,
    TRAINER = 3,
    COGWHEEL = 4,
    COGWHEEL2 = 5,
    MONEY_BAG = 6,
    TALK_BUBBLE = 7,
    TABARD = 8,
    CROSSED_SWORDS = 9,
    YELLOW_DOT = 10,
  },
  names = {
    [0] = "CHAT",
    [1] = "VENDOR",
    [2] = "TAXI",
    [3] = "TRAINER",
    [4] = "COGWHEEL",
    [5] = "COGWHEEL2",
    [6] = "MONEY_BAG",
    [7] = "TALK_BUBBLE",
    [8] = "TABARD",
    [9] = "CROSSED_SWORDS",
    [10] = "YELLOW_DOT",
  },
}
