return {
  name = "QuestInfoTypes",
  kind = "enum",
  values = {
    GROUP = 1,
    LIFE = 21,
    PVP = 41,
    RAID = 62,
    DUNGEON = 81,
    WORLD_EVENT = 82,
    LEGENDARY = 83,
    ESCORT = 84,
    HEROIC = 85,
    RAID_10 = 88,
    RAID_25 = 89,
  },
  names = {
    [1] = "GROUP",
    [21] = "LIFE",
    [41] = "PVP",
    [62] = "RAID",
    [81] = "DUNGEON",
    [82] = "WORLD_EVENT",
    [83] = "LEGENDARY",
    [84] = "ESCORT",
    [85] = "HEROIC",
    [88] = "RAID_10",
    [89] = "RAID_25",
  },
}
