return {
  name = "SpellFamilyName",
  kind = "enum",
  values = {
    GENERIC = 0,
    MAGE = 3,
    WARRIOR = 4,
    WARLOCK = 5,
    PRIEST = 6,
    DRUID = 7,
    ROGUE = 8,
    HUNTER = 9,
    PALADIN = 10,
    SHAMAN = 11,
    POTION = 13,
    DEATH_KNIGHT = 15,
  },
  names = {
    [0] = "GENERIC",
    [3] = "MAGE",
    [4] = "WARRIOR",
    [5] = "WARLOCK",
    [6] = "PRIEST",
    [7] = "DRUID",
    [8] = "ROGUE",
    [9] = "HUNTER",
    [10] = "PALADIN",
    [11] = "SHAMAN",
    [13] = "POTION",
    [15] = "DEATH_KNIGHT",
  },
}
