return {
  name = "SpellCreatureTarget",
  kind = "enum",
  values = {
    BEAST = 1,
    DRAGONKIN = 2,
    DEMON = 4,
    ELEMENTAL = 8,
    GIANT = 16,
    UNDEAD = 32,
    HUMANOID = 64,
    CRITTER = 128,
    MECHANICAL = 256,
    UNSPECIED = 512,
    TOTEM = 1024,
    NON_COMBAT_PET = 2048,
    GAS_CLOUD = 4096,
  },
  names = {
    [1] = "BEAST",
    [2] = "DRAGONKIN",
    [4] = "DEMON",
    [8] = "ELEMENTAL",
    [16] = "GIANT",
    [32] = "UNDEAD",
    [64] = "HUMANOID",
    [128] = "CRITTER",
    [256] = "MECHANICAL",
    [512] = "UNSPECIED",
    [1024] = "TOTEM",
    [2048] = "NON_COMBAT_PET",
    [4096] = "GAS_CLOUD",
  },
}
