-- Generated from TSWoW's ChrRaces.ts. Do not edit.
return {
  name = "ChrRaces",
  record_size = 276,
  field_count = 69,
  fields = {
    { name = "ID", kind = "key", offset = 0, count = 1 },
    { name = "Flags", kind = "i32", offset = 4, count = 1 },
    { name = "FactionID", kind = "i32", offset = 8, count = 1 },
    { name = "ExplorationSoundID", kind = "i32", offset = 12, count = 1 },
    { name = "MaleDisplayId", kind = "i32", offset = 16, count = 1 },
    { name = "FemaleDisplayId", kind = "i32", offset = 20, count = 1 },
    { name = "ClientPrefix", kind = "str", offset = 24, count = 1 },
    { name = "BaseLanguage", kind = "i32", offset = 28, count = 1 },
    { name = "CreatureType", kind = "i32", offset = 32, count = 1 },
    { name = "ResSicknessSpellID", kind = "i32", offset = 36, count = 1 },
    { name = "SplashSoundID", kind = "i32", offset = 40, count = 1 },
    { name = "ClientFilestring", kind = "str", offset = 44, count = 1 },
    { name = "CinematicSequenceID", kind = "i32", offset = 48, count = 1 },
    { name = "Alliance", kind = "i32", offset = 52, count = 1 },
    { name = "Name", kind = "loc", offset = 56, count = 1 },
    { name = "Name_Female", kind = "loc", offset = 124, count = 1 },
    { name = "Name_Male", kind = "loc", offset = 192, count = 1 },
    { name = "FacialHairCustomization", kind = "str", offset = 260, count = 2 },
    { name = "HairCustomization", kind = "str", offset = 268, count = 1 },
    { name = "Required_Expansion", kind = "i32", offset = 272, count = 1 },
  },
}
