-- Generated from TSWoW's CreatureModelData.ts. Do not edit.
return {
  name = "CreatureModelData",
  record_size = 112,
  field_count = 28,
  fields = {
    { name = "ID", kind = "key", offset = 0, count = 1 },
    { name = "Flags", kind = "i32", offset = 4, count = 1 },
    { name = "ModelName", kind = "str", offset = 8, count = 1 },
    { name = "SizeClass", kind = "i32", offset = 12, count = 1 },
    { name = "ModelScale", kind = "f32", offset = 16, count = 1 },
    { name = "BloodID", kind = "i32", offset = 20, count = 1 },
    { name = "FootprintTextureID", kind = "i32", offset = 24, count = 1 },
    { name = "FootprintTextureLength", kind = "f32", offset = 28, count = 1 },
    { name = "FootprintTextureWidth", kind = "f32", offset = 32, count = 1 },
    { name = "FootprintParticleScale", kind = "f32", offset = 36, count = 1 },
    { name = "FoleyMaterialID", kind = "i32", offset = 40, count = 1 },
    { name = "FootstepShakeSize", kind = "i32", offset = 44, count = 1 },
    { name = "DeathThudShakeSize", kind = "i32", offset = 48, count = 1 },
    { name = "SoundID", kind = "i32", offset = 52, count = 1 },
    { name = "CollisionWidth", kind = "f32", offset = 56, count = 1 },
    { name = "CollisionHeight", kind = "f32", offset = 60, count = 1 },
    { name = "MountHeight", kind = "f32", offset = 64, count = 1 },
    { name = "GeoBoxMinX", kind = "f32", offset = 68, count = 1 },
    { name = "GeoBoxMinY", kind = "f32", offset = 72, count = 1 },
    { name = "GeoBoxMinZ", kind = "f32", offset = 76, count = 1 },
    { name = "GeoBoxMaxX", kind = "f32", offset = 80, count = 1 },
    { name = "GeoBoxMaxY", kind = "f32", offset = 84, count = 1 },
    { name = "GeoBoxMaxZ", kind = "f32", offset = 88, count = 1 },
    { name = "WorldEffectScale", kind = "f32", offset = 92, count = 1 },
    { name = "AttachedEffectScale", kind = "f32", offset = 96, count = 1 },
    { name = "MissileCollisionRadius", kind = "f32", offset = 100, count = 1 },
    { name = "MissileCollisionPush", kind = "f32", offset = 104, count = 1 },
    { name = "MissileCollisionRaise", kind = "f32", offset = 108, count = 1 },
  },
}
