-- Generated from TSWoW's CreatureSoundData.ts. Do not edit.
return {
  name = "CreatureSoundData",
  record_size = 152,
  field_count = 38,
  fields = {
    { name = "ID", kind = "key", offset = 0, count = 1 },
    { name = "SoundExertionID", kind = "i32", offset = 4, count = 1 },
    { name = "SoundExertionCriticalID", kind = "i32", offset = 8, count = 1 },
    { name = "SoundInjuryID", kind = "i32", offset = 12, count = 1 },
    { name = "SoundInjuryCriticalID", kind = "i32", offset = 16, count = 1 },
    { name = "SoundInjuryCrushingBlowID", kind = "i32", offset = 20, count = 1 },
    { name = "SoundDeathID", kind = "i32", offset = 24, count = 1 },
    { name = "SoundStunID", kind = "i32", offset = 28, count = 1 },
    { name = "SoundStandID", kind = "i32", offset = 32, count = 1 },
    { name = "SoundFootstepID", kind = "i32", offset = 36, count = 1 },
    { name = "SoundAggroID", kind = "i32", offset = 40, count = 1 },
    { name = "SoundWingFlapID", kind = "i32", offset = 44, count = 1 },
    { name = "SoundWingGlideID", kind = "i32", offset = 48, count = 1 },
    { name = "SoundAlertID", kind = "i32", offset = 52, count = 1 },
    { name = "SoundFidget", kind = "i32", offset = 56, count = 5 },
    { name = "CustomAttack", kind = "i32", offset = 76, count = 4 },
    { name = "NPCSoundID", kind = "i32", offset = 92, count = 1 },
    { name = "LoopSoundID", kind = "i32", offset = 96, count = 1 },
    { name = "CreatureImpactType", kind = "i32", offset = 100, count = 1 },
    { name = "SoundJumpStartID", kind = "i32", offset = 104, count = 1 },
    { name = "SoundJumpEndID", kind = "i32", offset = 108, count = 1 },
    { name = "SoundPetAttackID", kind = "i32", offset = 112, count = 1 },
    { name = "SoundPetOrderID", kind = "i32", offset = 116, count = 1 },
    { name = "SoundPetDismissID", kind = "i32", offset = 120, count = 1 },
    { name = "FidgetDelaySecondsMin", kind = "f32", offset = 124, count = 1 },
    { name = "FidgetDelaySecondsMax", kind = "f32", offset = 128, count = 1 },
    { name = "BirthSoundID", kind = "i32", offset = 132, count = 1 },
    { name = "SpellCastDirectedSoundID", kind = "i32", offset = 136, count = 1 },
    { name = "SubmergeSoundID", kind = "i32", offset = 140, count = 1 },
    { name = "SubmergedSoundID", kind = "i32", offset = 144, count = 1 },
    { name = "CreatureSoundDataIDPet", kind = "i32", offset = 148, count = 1 },
  },
}
