-- Generated from TSWoW's LiquidType.ts. Do not edit.
return {
  name = "LiquidType",
  record_size = 180,
  field_count = 45,
  fields = {
    { name = "ID", kind = "key", offset = 0, count = 1 },
    { name = "Name", kind = "str", offset = 4, count = 1 },
    { name = "Flags", kind = "i32", offset = 8, count = 1 },
    { name = "Type", kind = "i32", offset = 12, count = 1 },
    { name = "SoundID", kind = "i32", offset = 16, count = 1 },
    { name = "SpellID", kind = "i32", offset = 20, count = 1 },
    { name = "MaxDarkenDepth", kind = "f32", offset = 24, count = 1 },
    { name = "FogDarkenintensity", kind = "f32", offset = 28, count = 1 },
    { name = "AmbDarkenintensity", kind = "f32", offset = 32, count = 1 },
    { name = "DirDarkenintensity", kind = "f32", offset = 36, count = 1 },
    { name = "LightID", kind = "i32", offset = 40, count = 1 },
    { name = "ParticleScale", kind = "f32", offset = 44, count = 1 },
    { name = "ParticleMovement", kind = "i32", offset = 48, count = 1 },
    { name = "ParticleTexSlots", kind = "i32", offset = 52, count = 1 },
    { name = "MaterialID", kind = "i32", offset = 56, count = 1 },
    { name = "Texture", kind = "str", offset = 60, count = 6 },
    { name = "Color", kind = "i32", offset = 84, count = 2 },
    { name = "Float", kind = "f32", offset = 92, count = 18 },
    { name = "Int", kind = "i32", offset = 164, count = 4 },
  },
}
