-- Generated from TSWoW's ScalingStatValues.ts. Do not edit.
return {
  name = "ScalingStatValues",
  record_size = 96,
  field_count = 24,
  fields = {
    { name = "ID", kind = "key", offset = 0, count = 1 },
    { name = "Charlevel", kind = "i32", offset = 4, count = 1 },
    { name = "ShoulderBudget", kind = "i32", offset = 8, count = 1 },
    { name = "TrinketBudget", kind = "i32", offset = 12, count = 1 },
    { name = "WeaponBudget1H", kind = "i32", offset = 16, count = 1 },
    { name = "RangedBudget", kind = "i32", offset = 20, count = 1 },
    { name = "ClothShoulderArmor", kind = "i32", offset = 24, count = 1 },
    { name = "LeatherShoulderArmor", kind = "i32", offset = 28, count = 1 },
    { name = "MailShoulderArmor", kind = "i32", offset = 32, count = 1 },
    { name = "PlateShoulderArmor", kind = "i32", offset = 36, count = 1 },
    { name = "WeaponDPS1H", kind = "i32", offset = 40, count = 1 },
    { name = "WeaponDPS2H", kind = "i32", offset = 44, count = 1 },
    { name = "SpellcasterDPS1H", kind = "i32", offset = 48, count = 1 },
    { name = "SpellcasterDPS2H", kind = "i32", offset = 52, count = 1 },
    { name = "RangedDPS", kind = "i32", offset = 56, count = 1 },
    { name = "WandDPS", kind = "i32", offset = 60, count = 1 },
    { name = "SpellPower", kind = "i32", offset = 64, count = 1 },
    { name = "PrimaryBudget", kind = "i32", offset = 68, count = 1 },
    { name = "TertiaryBudget", kind = "i32", offset = 72, count = 1 },
    { name = "ClothCloakArmor", kind = "i32", offset = 76, count = 1 },
    { name = "ClothChestArmor", kind = "i32", offset = 80, count = 1 },
    { name = "LeatherChestArmor", kind = "i32", offset = 84, count = 1 },
    { name = "MailChestArmor", kind = "i32", offset = 88, count = 1 },
    { name = "PlateChestArmor", kind = "i32", offset = 92, count = 1 },
  },
}
