-- Generated from TSWoW's SoundSamplePreferences.ts. Do not edit.
return {
  name = "SoundSamplePreferences",
  record_size = 68,
  field_count = 17,
  fields = {
    { name = "ID", kind = "key", offset = 0, count = 1 },
    { name = "Field01", kind = "i32", offset = 4, count = 1 },
    { name = "Field02", kind = "i32", offset = 8, count = 1 },
    { name = "Field03", kind = "i32", offset = 12, count = 1 },
    { name = "Field04", kind = "i32", offset = 16, count = 1 },
    { name = "Field05", kind = "i32", offset = 20, count = 1 },
    { name = "Field06", kind = "i32", offset = 24, count = 1 },
    { name = "Field07", kind = "i32", offset = 28, count = 1 },
    { name = "Field08", kind = "f32", offset = 32, count = 1 },
    { name = "Field09", kind = "f32", offset = 36, count = 1 },
    { name = "Field10", kind = "i32", offset = 40, count = 1 },
    { name = "Field11", kind = "i32", offset = 44, count = 1 },
    { name = "Field12", kind = "i32", offset = 48, count = 1 },
    { name = "Field13", kind = "f32", offset = 52, count = 1 },
    { name = "Field14", kind = "i32", offset = 56, count = 1 },
    { name = "Field15", kind = "f32", offset = 60, count = 1 },
    { name = "Field16", kind = "i32", offset = 64, count = 1 },
  },
}
