-- Generated from TSWoW's SoundProviderPreferences.ts. Do not edit.
return {
  name = "SoundProviderPreferences",
  record_size = 96,
  field_count = 24,
  fields = {
    { name = "ID", kind = "key", offset = 0, count = 1 },
    { name = "Description", kind = "str", offset = 4, count = 1 },
    { name = "Flags", kind = "i32", offset = 8, count = 1 },
    { name = "EAXEnvironmentSelection", kind = "i32", offset = 12, count = 1 },
    { name = "EAXDecayTime", kind = "f32", offset = 16, count = 1 },
    { name = "EAX2EnvironmentSize", kind = "f32", offset = 20, count = 1 },
    { name = "EAX2EnvironmentDiffusion", kind = "f32", offset = 24, count = 1 },
    { name = "EAX2Room", kind = "i32", offset = 28, count = 1 },
    { name = "EAX2RoomHF", kind = "i32", offset = 32, count = 1 },
    { name = "EAX2DecayHFRatio", kind = "f32", offset = 36, count = 1 },
    { name = "EAX2Reflections", kind = "i32", offset = 40, count = 1 },
    { name = "EAX2ReflectionsDelay", kind = "f32", offset = 44, count = 1 },
    { name = "EAX2Reverb", kind = "i32", offset = 48, count = 1 },
    { name = "EAX2ReverbDelay", kind = "f32", offset = 52, count = 1 },
    { name = "EAX2RoomRolloff", kind = "f32", offset = 56, count = 1 },
    { name = "EAX2AirAbsorption", kind = "f32", offset = 60, count = 1 },
    { name = "EAX3RoomLF", kind = "i32", offset = 64, count = 1 },
    { name = "EAX3DecayLFRatio", kind = "f32", offset = 68, count = 1 },
    { name = "EAX3EchoTime", kind = "f32", offset = 72, count = 1 },
    { name = "EAX3EchoDepth", kind = "f32", offset = 76, count = 1 },
    { name = "EAX3ModulationTime", kind = "f32", offset = 80, count = 1 },
    { name = "EAX3ModulationDepth", kind = "f32", offset = 84, count = 1 },
    { name = "EAX3HFReference", kind = "f32", offset = 88, count = 1 },
    { name = "EAX3LFReference", kind = "f32", offset = 92, count = 1 },
  },
}
