-- Generated from TSWoW's SoundEntriesAdvanced.ts. Do not edit.
return {
  name = "SoundEntriesAdvanced",
  record_size = 96,
  field_count = 24,
  fields = {
    { name = "ID", kind = "key", offset = 0, count = 1 },
    { name = "SoundEntryID", kind = "i32", offset = 4, count = 1 },
    { name = "InnerRadius2D", kind = "f32", offset = 8, count = 1 },
    { name = "TimeA", kind = "i32", offset = 12, count = 1 },
    { name = "TimeB", kind = "i32", offset = 16, count = 1 },
    { name = "TimeC", kind = "i32", offset = 20, count = 1 },
    { name = "TimeD", kind = "i32", offset = 24, count = 1 },
    { name = "RandomOffsetRange", kind = "i32", offset = 28, count = 1 },
    { name = "Usage", kind = "i32", offset = 32, count = 1 },
    { name = "TimeintervalMin", kind = "i32", offset = 36, count = 1 },
    { name = "TimeintervalMax", kind = "i32", offset = 40, count = 1 },
    { name = "VolumeSliderCategory", kind = "i32", offset = 44, count = 1 },
    { name = "DuckToSFX", kind = "f32", offset = 48, count = 1 },
    { name = "DuckToMusic", kind = "f32", offset = 52, count = 1 },
    { name = "DuckToAmbience", kind = "f32", offset = 56, count = 1 },
    { name = "InnerRadiusOfInfluence", kind = "f32", offset = 60, count = 1 },
    { name = "OuterRadiusOfInfluence", kind = "f32", offset = 64, count = 1 },
    { name = "TimeToDuck", kind = "i32", offset = 68, count = 1 },
    { name = "TimeToUnduck", kind = "i32", offset = 72, count = 1 },
    { name = "InsideAngle", kind = "f32", offset = 76, count = 1 },
    { name = "OutsideAngle", kind = "f32", offset = 80, count = 1 },
    { name = "OutsideVolume", kind = "f32", offset = 84, count = 1 },
    { name = "OuterRadius2D", kind = "f32", offset = 88, count = 1 },
    { name = "Name", kind = "str", offset = 92, count = 1 },
  },
}
