-- Generated from TSWoW's SpellVisual.ts. Do not edit.
return {
  name = "SpellVisual",
  record_size = 128,
  field_count = 32,
  fields = {
    { name = "ID", kind = "key", offset = 0, count = 1 },
    { name = "PrecastKit", kind = "i32", offset = 4, count = 1 },
    { name = "CastKit", kind = "i32", offset = 8, count = 1 },
    { name = "ImpactKit", kind = "i32", offset = 12, count = 1 },
    { name = "StateKit", kind = "i32", offset = 16, count = 1 },
    { name = "StateDoneKit", kind = "i32", offset = 20, count = 1 },
    { name = "ChannelKit", kind = "i32", offset = 24, count = 1 },
    { name = "HasMissile", kind = "i32", offset = 28, count = 1 },
    { name = "MissileModel", kind = "i32", offset = 32, count = 1 },
    { name = "MissilePathType", kind = "i32", offset = 36, count = 1 },
    { name = "MissileDestinationAttachment", kind = "i32", offset = 40, count = 1 },
    { name = "MissileSound", kind = "i32", offset = 44, count = 1 },
    { name = "AnimEventSoundID", kind = "i32", offset = 48, count = 1 },
    { name = "Flags", kind = "i32", offset = 52, count = 1 },
    { name = "CasterImpactKit", kind = "i32", offset = 56, count = 1 },
    { name = "TargetImpactKit", kind = "i32", offset = 60, count = 1 },
    { name = "MissileAttachment", kind = "i32", offset = 64, count = 1 },
    { name = "MissileFollowGroundHeight", kind = "i32", offset = 68, count = 1 },
    { name = "MissileFollowGroundDropSpeed", kind = "i32", offset = 72, count = 1 },
    { name = "MissileFollowGroundApproach", kind = "i32", offset = 76, count = 1 },
    { name = "MissileFollowGroundFlags", kind = "i32", offset = 80, count = 1 },
    { name = "MissileMotion", kind = "i32", offset = 84, count = 1 },
    { name = "MissileTargetingKit", kind = "i32", offset = 88, count = 1 },
    { name = "InstantAreaKit", kind = "i32", offset = 92, count = 1 },
    { name = "ImpactAreaKit", kind = "i32", offset = 96, count = 1 },
    { name = "PersistentAreaKit", kind = "i32", offset = 100, count = 1 },
    { name = "MissileCastOffsetX", kind = "f32", offset = 104, count = 1 },
    { name = "MissileCastOffsetY", kind = "f32", offset = 108, count = 1 },
    { name = "MissileCastOffsetZ", kind = "f32", offset = 112, count = 1 },
    { name = "MissileImpactOffsetX", kind = "f32", offset = 116, count = 1 },
    { name = "MissileImpactOffsetY", kind = "f32", offset = 120, count = 1 },
    { name = "MissileImpactOffsetZ", kind = "f32", offset = 124, count = 1 },
  },
}
