-- Generated from TSWoW's SpellVisualKit.ts. Do not edit.
return {
  name = "SpellVisualKit",
  record_size = 152,
  field_count = 38,
  fields = {
    { name = "ID", kind = "key", offset = 0, count = 1 },
    { name = "StartAnimID", kind = "i32", offset = 4, count = 1 },
    { name = "AnimID", kind = "i32", offset = 8, count = 1 },
    { name = "HeadEffect", kind = "i32", offset = 12, count = 1 },
    { name = "ChestEffect", kind = "i32", offset = 16, count = 1 },
    { name = "BaseEffect", kind = "i32", offset = 20, count = 1 },
    { name = "LeftHandEffect", kind = "i32", offset = 24, count = 1 },
    { name = "RightHandEffect", kind = "i32", offset = 28, count = 1 },
    { name = "BreathEffect", kind = "i32", offset = 32, count = 1 },
    { name = "LeftWeaponEffect", kind = "i32", offset = 36, count = 1 },
    { name = "RightWeaponEffect", kind = "i32", offset = 40, count = 1 },
    { name = "SpecialEffect", kind = "i32", offset = 44, count = 3 },
    { name = "WorldEffect", kind = "i32", offset = 56, count = 1 },
    { name = "SoundID", kind = "i32", offset = 60, count = 1 },
    { name = "ShakeID", kind = "i32", offset = 64, count = 1 },
    { name = "CharProc", kind = "i32", offset = 68, count = 4 },
    { name = "CharParamZero", kind = "f32", offset = 84, count = 4 },
    { name = "CharParamOne", kind = "f32", offset = 100, count = 4 },
    { name = "CharParamTwo", kind = "f32", offset = 116, count = 4 },
    { name = "CharParamThree", kind = "f32", offset = 132, count = 4 },
    { name = "Flags", kind = "u32", offset = 148, count = 1 },
  },
}
