-- Generated from TSWoW's SpellChainEffects.ts. Do not edit.
return {
  name = "SpellChainEffects",
  record_size = 177,
  field_count = 48,
  fields = {
    { name = "ID", kind = "key", offset = 0, count = 1 },
    { name = "AvgSegLen", kind = "f32", offset = 4, count = 1 },
    { name = "Width", kind = "f32", offset = 8, count = 1 },
    { name = "NoiseScale", kind = "f32", offset = 12, count = 1 },
    { name = "TexCoordScale", kind = "f32", offset = 16, count = 1 },
    { name = "SegDuration", kind = "i32", offset = 20, count = 1 },
    { name = "SegDelay", kind = "i32", offset = 24, count = 1 },
    { name = "Texture", kind = "str", offset = 28, count = 1 },
    { name = "Flags", kind = "i32", offset = 32, count = 1 },
    { name = "JointCount", kind = "i32", offset = 36, count = 1 },
    { name = "JointOffsetRadius", kind = "f32", offset = 40, count = 1 },
    { name = "JointsPerMinorJoint", kind = "i32", offset = 44, count = 1 },
    { name = "MinorJointsPerMajorJoint", kind = "i32", offset = 48, count = 1 },
    { name = "MinorJointScale", kind = "f32", offset = 52, count = 1 },
    { name = "MajorJointScale", kind = "f32", offset = 56, count = 1 },
    { name = "JointMoveSpeed", kind = "f32", offset = 60, count = 1 },
    { name = "JointSmoothness", kind = "f32", offset = 64, count = 1 },
    { name = "MinDurationBetweenJointJumps", kind = "f32", offset = 68, count = 1 },
    { name = "MaxDurationBetweenJointJumps", kind = "f32", offset = 72, count = 1 },
    { name = "WaveHeight", kind = "f32", offset = 76, count = 1 },
    { name = "WaveFreq", kind = "f32", offset = 80, count = 1 },
    { name = "WaveSpeed", kind = "f32", offset = 84, count = 1 },
    { name = "MinWaveAngle", kind = "f32", offset = 88, count = 1 },
    { name = "MaxWaveAngle", kind = "f32", offset = 92, count = 1 },
    { name = "MinWaveSpin", kind = "f32", offset = 96, count = 1 },
    { name = "MaxWaveSpin", kind = "f32", offset = 100, count = 1 },
    { name = "ArcHeight", kind = "f32", offset = 104, count = 1 },
    { name = "MinArcAngle", kind = "f32", offset = 108, count = 1 },
    { name = "MaxArcAngle", kind = "f32", offset = 112, count = 1 },
    { name = "MinArcSpin", kind = "f32", offset = 116, count = 1 },
    { name = "MaxArcSpin", kind = "f32", offset = 120, count = 1 },
    { name = "DelayBetweenEffects", kind = "f32", offset = 124, count = 1 },
    { name = "MinFlickerOnDuration", kind = "f32", offset = 128, count = 1 },
    { name = "MaxFlickerOnDuration", kind = "f32", offset = 132, count = 1 },
    { name = "MinFlickerOffDuration", kind = "f32", offset = 136, count = 1 },
    { name = "MaxFlickerOffDuration", kind = "f32", offset = 140, count = 1 },
    { name = "PulseSpeed", kind = "f32", offset = 144, count = 1 },
    { name = "PulseOnLength", kind = "f32", offset = 148, count = 1 },
    { name = "PulseFadeLength", kind = "f32", offset = 152, count = 1 },
    { name = "Alpha", kind = "byte", offset = 156, count = 1 },
    { name = "Red", kind = "byte", offset = 157, count = 1 },
    { name = "Green", kind = "byte", offset = 158, count = 1 },
    { name = "Blue", kind = "byte", offset = 159, count = 1 },
    { name = "BlendMode", kind = "byte", offset = 160, count = 1 },
    { name = "Combo", kind = "str", offset = 161, count = 1 },
    { name = "RenderLayer", kind = "i32", offset = 165, count = 1 },
    { name = "TextureLength", kind = "f32", offset = 169, count = 1 },
    { name = "WavePhase", kind = "f32", offset = 173, count = 1 },
  },
}
