-- Generated from TSWoW's VehicleSeat.ts. Do not edit.
return {
  name = "VehicleSeat",
  record_size = 232,
  field_count = 58,
  fields = {
    { name = "ID", kind = "key", offset = 0, count = 1 },
    { name = "Flags", kind = "u32", offset = 4, count = 1 },
    { name = "AttachmentID", kind = "i32", offset = 8, count = 1 },
    { name = "AttachmentOffsetX", kind = "f32", offset = 12, count = 1 },
    { name = "AttachmentOffsetY", kind = "f32", offset = 16, count = 1 },
    { name = "AttachmentOffsetZ", kind = "f32", offset = 20, count = 1 },
    { name = "EnterPreDelay", kind = "f32", offset = 24, count = 1 },
    { name = "EnterSpeed", kind = "f32", offset = 28, count = 1 },
    { name = "EnterGravity", kind = "f32", offset = 32, count = 1 },
    { name = "EnterMinDuration", kind = "f32", offset = 36, count = 1 },
    { name = "EnterMaxDuration", kind = "f32", offset = 40, count = 1 },
    { name = "EnterMinArcHeight", kind = "f32", offset = 44, count = 1 },
    { name = "EnterMaxArcHeight", kind = "f32", offset = 48, count = 1 },
    { name = "EnterAnimStart", kind = "i32", offset = 52, count = 1 },
    { name = "EnterAnimLoop", kind = "i32", offset = 56, count = 1 },
    { name = "RideAnimStart", kind = "i32", offset = 60, count = 1 },
    { name = "RideAnimLoop", kind = "i32", offset = 64, count = 1 },
    { name = "RideUpperAnimStart", kind = "i32", offset = 68, count = 1 },
    { name = "RideUpperAnimLoop", kind = "i32", offset = 72, count = 1 },
    { name = "ExitPreDelay", kind = "f32", offset = 76, count = 1 },
    { name = "ExitSpeed", kind = "f32", offset = 80, count = 1 },
    { name = "ExitGravity", kind = "f32", offset = 84, count = 1 },
    { name = "ExitMinDuration", kind = "f32", offset = 88, count = 1 },
    { name = "ExitMaxDuration", kind = "f32", offset = 92, count = 1 },
    { name = "ExitMinArcHeight", kind = "f32", offset = 96, count = 1 },
    { name = "ExitMaxArcHeight", kind = "f32", offset = 100, count = 1 },
    { name = "ExitAnimStart", kind = "i32", offset = 104, count = 1 },
    { name = "ExitAnimLoop", kind = "i32", offset = 108, count = 1 },
    { name = "ExitAnimEnd", kind = "i32", offset = 112, count = 1 },
    { name = "PassengerYaw", kind = "f32", offset = 116, count = 1 },
    { name = "PassengerPitch", kind = "f32", offset = 120, count = 1 },
    { name = "PassengerRoll", kind = "f32", offset = 124, count = 1 },
    { name = "PassengerAttachmentID", kind = "i32", offset = 128, count = 1 },
    { name = "VehicleEnterAnim", kind = "i32", offset = 132, count = 1 },
    { name = "VehicleExitAnim", kind = "i32", offset = 136, count = 1 },
    { name = "VehicleRideAnimLoop", kind = "i32", offset = 140, count = 1 },
    { name = "VehicleEnterAnimBone", kind = "i32", offset = 144, count = 1 },
    { name = "VehicleExitAnimBone", kind = "i32", offset = 148, count = 1 },
    { name = "VehicleRideAnimLoopBone", kind = "i32", offset = 152, count = 1 },
    { name = "VehicleEnterAnimDelay", kind = "f32", offset = 156, count = 1 },
    { name = "VehicleExitAnimDelay", kind = "f32", offset = 160, count = 1 },
    { name = "VehicleAbilityDisplay", kind = "i32", offset = 164, count = 1 },
    { name = "EnterUISoundID", kind = "i32", offset = 168, count = 1 },
    { name = "ExitUISoundID", kind = "i32", offset = 172, count = 1 },
    { name = "UiSkin", kind = "i32", offset = 176, count = 1 },
    { name = "FlagsB", kind = "u32", offset = 180, count = 1 },
    { name = "CameraEnteringDelay", kind = "f32", offset = 184, count = 1 },
    { name = "CameraEnteringDuration", kind = "f32", offset = 188, count = 1 },
    { name = "CameraExitingDelay", kind = "f32", offset = 192, count = 1 },
    { name = "CameraExitingDuration", kind = "f32", offset = 196, count = 1 },
    { name = "CameraOffsetX", kind = "f32", offset = 200, count = 1 },
    { name = "CameraOffsetY", kind = "f32", offset = 204, count = 1 },
    { name = "CameraOffsetZ", kind = "f32", offset = 208, count = 1 },
    { name = "CameraPosChaseRate", kind = "f32", offset = 212, count = 1 },
    { name = "CameraFacingChaseRate", kind = "f32", offset = 216, count = 1 },
    { name = "CameraEnteringZoom", kind = "f32", offset = 220, count = 1 },
    { name = "CameraSeatZoomMin", kind = "f32", offset = 224, count = 1 },
    { name = "CameraSeatZoomMax", kind = "f32", offset = 228, count = 1 },
  },
}
