-- Generated from TSWoW's Vehicle.ts. Do not edit.
return {
  name = "Vehicle",
  record_size = 160,
  field_count = 40,
  fields = {
    { name = "ID", kind = "key", offset = 0, count = 1 },
    { name = "Flags", kind = "i32", offset = 4, count = 1 },
    { name = "TurnSpeed", kind = "f32", offset = 8, count = 1 },
    { name = "PitchSpeed", kind = "f32", offset = 12, count = 1 },
    { name = "PitchMin", kind = "f32", offset = 16, count = 1 },
    { name = "PitchMax", kind = "f32", offset = 20, count = 1 },
    { name = "SeatID", kind = "i32", offset = 24, count = 8 },
    { name = "MouseLookOffsetPitch", kind = "f32", offset = 56, count = 1 },
    { name = "CameraFadeDistScalarMin", kind = "f32", offset = 60, count = 1 },
    { name = "CameraFadeDistScalarMax", kind = "f32", offset = 64, count = 1 },
    { name = "CameraPitchOffset", kind = "f32", offset = 68, count = 1 },
    { name = "FacingLimitRight", kind = "f32", offset = 72, count = 1 },
    { name = "FacingLimitLeft", kind = "f32", offset = 76, count = 1 },
    { name = "MsslTrgtTurnLingering", kind = "f32", offset = 80, count = 1 },
    { name = "MsslTrgtPitchLingering", kind = "f32", offset = 84, count = 1 },
    { name = "MsslTrgtMouseLingering", kind = "f32", offset = 88, count = 1 },
    { name = "MsslTrgtEndOpacity", kind = "f32", offset = 92, count = 1 },
    { name = "MsslTrgtArcSpeed", kind = "f32", offset = 96, count = 1 },
    { name = "MsslTrgtArcRepeat", kind = "f32", offset = 100, count = 1 },
    { name = "MsslTrgtArcWidth", kind = "f32", offset = 104, count = 1 },
    { name = "MsslTrgtImpactRadius", kind = "f32", offset = 108, count = 2 },
    { name = "MsslTrgtArcTexture", kind = "str", offset = 116, count = 1 },
    { name = "MsslTrgtImpactTexture", kind = "str", offset = 120, count = 1 },
    { name = "MsslTrgtImpactModel", kind = "str", offset = 124, count = 2 },
    { name = "CameraYawOffset", kind = "f32", offset = 132, count = 1 },
    { name = "UilocomotionType", kind = "i32", offset = 136, count = 1 },
    { name = "MsslTrgtImpactTexRadius", kind = "f32", offset = 140, count = 1 },
    { name = "VehicleUIIndicatorID", kind = "i32", offset = 144, count = 1 },
    { name = "PowerDisplayID", kind = "i32", offset = 148, count = 3 },
  },
}
