-- Generated from TSWoW's VideoHardware.ts. Do not edit.
return {
  name = "VideoHardware",
  record_size = 92,
  field_count = 23,
  fields = {
    { name = "ID", kind = "key", offset = 0, count = 1 },
    { name = "VendorID", kind = "i32", offset = 4, count = 1 },
    { name = "DeviceID", kind = "i32", offset = 8, count = 1 },
    { name = "FarclipIdx", kind = "i32", offset = 12, count = 1 },
    { name = "TerrainLODDistIdx", kind = "i32", offset = 16, count = 1 },
    { name = "TerrainShadowLOD", kind = "i32", offset = 20, count = 1 },
    { name = "DetailDoodadDensityIdx", kind = "i32", offset = 24, count = 1 },
    { name = "DetailDoodadAlpha", kind = "i32", offset = 28, count = 1 },
    { name = "AnimatingDoodadIdx", kind = "i32", offset = 32, count = 1 },
    { name = "Trilinear", kind = "i32", offset = 36, count = 1 },
    { name = "NumLights", kind = "i32", offset = 40, count = 1 },
    { name = "Specularity", kind = "i32", offset = 44, count = 1 },
    { name = "WaterLODIdx", kind = "i32", offset = 48, count = 1 },
    { name = "ParticleDensityIdx", kind = "i32", offset = 52, count = 1 },
    { name = "UnitDrawDistIdx", kind = "i32", offset = 56, count = 1 },
    { name = "SmallCullDistIdx", kind = "i32", offset = 60, count = 1 },
    { name = "ResolutionIdx", kind = "i32", offset = 64, count = 1 },
    { name = "BaseMipLevel", kind = "i32", offset = 68, count = 1 },
    { name = "OglOverrides", kind = "str", offset = 72, count = 1 },
    { name = "D3dOverrides", kind = "str", offset = 76, count = 1 },
    { name = "FixLag", kind = "i32", offset = 80, count = 1 },
    { name = "Multisample", kind = "i32", offset = 84, count = 1 },
    { name = "Atlasdisable", kind = "i32", offset = 88, count = 1 },
  },
}
