--[[
    tools/generate_meta.lua
    Generates LuaLS (EmmyLua) annotations for lua-dbc.

    Output layout:
        meta/
        ├── _workspace.lua         # dbc.Workspace overloads + DbcWorkspace_<build>
        ├── _tables.lua            # dbc.TableName alias (all known table names)
        ├── _enums.lua             # dbc.Enums field accessors and enum classes
        └── dbc/
            └── v<tag>/
                ├── Spell.lua      # dbc.row.v335.Spell and dbc.Table.v335.Spell
                └── ...

    The enum metadata is generated by scanning src/enums/*.lua. Each enum
    file is loaded in isolation to introspect its `values` and `bits` tables,
    then a compact `---@class dbc.enums.<Name>` block is emitted.

    Usage:
        luajit tools/generate_meta.lua [definitions_dir] [meta_dir] [--builds auto|3.3.5.12340,...]
]]

-- ---------------------------------------------------------------------------
-- Path setup
-- ---------------------------------------------------------------------------

package.path = "?.lua;src/?.lua;src/?/init.lua;tools/?.lua;" .. package.path

-- ---------------------------------------------------------------------------
-- Dependencies
-- ---------------------------------------------------------------------------

local json       = require("tools.json_pretty")
local fs         = require("tools.fs")
local cli        = require("tools.cli")
local dbd_common = require("tools.dbd_common")

local LOG = "LuaLS Generator"

cli.log(LOG, "JSON backend: %s", json.backend_name())

-- ---------------------------------------------------------------------------
-- Shared constants
-- ---------------------------------------------------------------------------

-- Maps DBDefs column types to LuaLS primitive types.
local LUA_TYPE_MAP = {
    locstring = "string",
    string    = "string",
    float     = "number",
    bool      = "boolean",
    int       = "integer",
    uint      = "integer",
}

-- Cross-platform `load` (LuaJIT provides `loadstring`; Lua 5.2+ has `load`).
local loadstring_fn = loadstring or load

-- ---------------------------------------------------------------------------
-- Small helpers
-- ---------------------------------------------------------------------------

local function pascal_case(name)
    if not name or name == "" then return "" end
    return name:sub(1, 1):upper() .. name:sub(2)
end

--- Returns a sorted list of the keys of a table.
local function sorted_keys(t)
    local keys = {}
    for k in pairs(t) do keys[#keys + 1] = k end
    table.sort(keys)
    return keys
end

-- ===========================================================================
-- Section 1 — Per-table metadata (dbc.row.<build>.<Table> / dbc.Table.<build>.<Table>)
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Field collection
-- ---------------------------------------------------------------------------

--- Extracts the field list for a table from its selected version definition.
--- Applies columnDefinitions metadata (foreignTable, foreignColumn, comment)
--- and falls back to a name-based heuristic for FK detection.
---@param selected table Version definition
---@param col_defs table columnDefinitions from the DBD JSON
---@return table[]
local function collect_fields(selected, col_defs)
    local fields = {}
    local seen = {}

    for _, d in ipairs(selected.definitions or {}) do
        local fname = d.name
        if fname and not seen[fname] then
            seen[fname] = true

            local cmeta = col_defs[fname] or {}
            local base_lua_type = LUA_TYPE_MAP[cmeta.type or "int"] or "any"
            local arr_len = tonumber(d.arrLength) or 0
            local lua_type = arr_len > 0 and (base_lua_type .. "[]") or base_lua_type

            local comment = d.comment or cmeta.comment or ""
            comment = comment:gsub("\n", " "):gsub("^%s+", ""):gsub("%s+$", "")

            local ftarget = cmeta.foreignTable
            if not ftarget and fname:sub(-2) == "ID" and fname ~= "ID" then
                ftarget = fname:sub(1, -3)
            end

            fields[#fields + 1] = {
                name           = fname,
                lua_type       = lua_type,
                base_lua_type  = base_lua_type,
                is_array       = arr_len > 0,
                foreign_table  = ftarget,
                foreign_column = cmeta.foreignColumn or "ID",
                comment        = comment,
            }
        end
    end

    return fields
end

-- ---------------------------------------------------------------------------
-- Emitters for the row class
-- ---------------------------------------------------------------------------

--- Emits `---@field` lines for each collected field.
local function emit_fields(parts, fields)
    for _, f in ipairs(fields) do
        if f.comment ~= "" then
            parts[#parts + 1] = "---@field " .. f.name .. " " .. f.lua_type
                .. " " .. f.comment .. "\n"
        else
            parts[#parts + 1] = "---@field " .. f.name .. " " .. f.lua_type .. "\n"
        end
    end
end

--- Emits getter, setter, array accessor and relation navigator for each field.
local function emit_accessors(parts, fields, row_class, build_tag)
    for _, f in ipairs(fields) do
        local fname = f.name
        local pname = pascal_case(fname)
        local ltype = f.lua_type

        -- Getter
        parts[#parts + 1] = "---Gets the value of field '" .. fname .. "'.\n"
        parts[#parts + 1] = "---@return " .. ltype .. " value\n"
        parts[#parts + 1] = "function row:Get" .. pname .. "() end\n\n"

        -- Setter
        parts[#parts + 1] = "---Sets the value of field '" .. fname .. "'.\n"
        parts[#parts + 1] = "---@param value " .. ltype .. "\n"
        parts[#parts + 1] = "---@return " .. row_class .. " self\n"
        parts[#parts + 1] = "function row:Set" .. pname .. "(value) end\n\n"

        -- Array item accessor
        if f.is_array then
            parts[#parts + 1] = "---Gets element at 1-based index in '" .. fname .. "'.\n"
            parts[#parts + 1] = "---@param index integer\n"
            parts[#parts + 1] = "---@return " .. f.base_lua_type .. " value\n"
            parts[#parts + 1] = "function row:Get" .. pname .. "Item(index) end\n\n"
        end

        -- Foreign key navigation
        if f.foreign_table and f.foreign_table ~= "" then
            local target_row_class = "dbc.row." .. build_tag .. "." .. f.foreign_table

            local rel_name
            if fname:sub(-2) == "ID" and fname ~= "ID" then
                rel_name = fname:sub(1, -3)
            elseif fname:sub(-3) == "_ID" then
                rel_name = fname:sub(1, -4)
            else
                rel_name = fname
            end
            local rel_pname = pascal_case(rel_name)

            parts[#parts + 1] = "---Navigates foreign relationship to '"
                .. f.foreign_table .. "' via '" .. fname .. "'.\n"
            parts[#parts + 1] = "---@return " .. target_row_class .. "|nil\n"
            parts[#parts + 1] = "function row:Get" .. rel_pname .. "() end\n\n"

            parts[#parts + 1] = "---Creates a related '" .. f.foreign_table
                .. "' row and automatically links '" .. fname .. "'.\n"
            parts[#parts + 1] = "---@param data? table\n"
            parts[#parts + 1] = "---@return " .. target_row_class .. "\n"
            parts[#parts + 1] = "function row:CreateRelated(data) end\n\n"
        end
    end
end

-- ---------------------------------------------------------------------------
-- Emitters for the table class
-- ---------------------------------------------------------------------------

--- Emits the DbcTable subclass methods (Create, FindById, Query, ...).
local function emit_table_interface(parts, table_name, row_class, tbl_class, target_build)
    parts[#parts + 1] = "---Table container for " .. table_name
        .. " (Build " .. target_build .. ").\n"
    parts[#parts + 1] = "---@class " .. tbl_class .. " : DbcTable\n"
    parts[#parts + 1] = "---@field [integer] " .. row_class .. "\n"
    parts[#parts + 1] = "local tbl = {}\n\n"

    local methods = {
        {
            name   = "Create",
            params = "id, data",
            doc    = "Creates and appends a new row to the table.",
            lines  = {
                "---@param id? integer Primary key",
                "---@param data? table Optional initial values",
            },
            ret = row_class,
        },
        {
            name   = "FindById",
            params = "id",
            doc    = "Finds a row by primary key (nil if not found).",
            lines  = { "---@param id integer" },
            ret    = row_class .. "|nil",
        },
        {
            name   = "GetRowById",
            params = "id",
            doc    = "Gets a row by primary key (throws if not found).",
            lines  = { "---@param id integer" },
            ret    = row_class,
        },
        {
            name   = "Query",
            params = "",
            doc    = "Creates a LINQ query over rows in this table.",
            lines  = {},
            ret    = "dbc.Query<" .. row_class .. ">",
        },
        {
            name   = "GetByRelation",
            params = "foreign_id",
            doc    = "Returns all rows related to a foreign ID via the relationship block.",
            lines  = { "---@param foreign_id integer" },
            ret    = row_class .. "[]",
        },
    }

    for _, m in ipairs(methods) do
        parts[#parts + 1] = "---" .. m.doc .. "\n"
        for _, line in ipairs(m.lines) do
            parts[#parts + 1] = line .. "\n"
        end
        parts[#parts + 1] = "---@return " .. m.ret .. "\n"
        parts[#parts + 1] = "function tbl:" .. m.name .. "(" .. m.params .. ") end\n\n"
    end
end

-- ---------------------------------------------------------------------------
-- Table metadata entry point
-- ---------------------------------------------------------------------------

--- Generates the .lua source for one table in one build.
--- Returns nil when the table is absent from the build.
---@param table_name string
---@param db_def table Parsed DBD JSON
---@param target_build string
---@param build_tag string
---@return string|nil
local function generate_table_meta(table_name, db_def, target_build, build_tag)
    local selected = dbd_common.select_version_definition(
        db_def.versionDefinitions or {}, target_build)
    if not selected or not selected.definitions then return nil end

    local col_defs = db_def.columnDefinitions or {}
    local row_class = "dbc.row." .. build_tag .. "." .. table_name
    local tbl_class = "dbc.Table." .. build_tag .. "." .. table_name

    local parts = {}
    parts[#parts + 1] = "---@meta\n"
    parts[#parts + 1] = "-- Generated LuaLS annotations for " .. table_name
        .. " (Build " .. target_build .. " [" .. build_tag .. "]). Do not edit.\n\n"
    parts[#parts + 1] = "---Row representation of " .. table_name
        .. " in build " .. target_build .. ".\n"
    parts[#parts + 1] = "---@class " .. row_class .. " : RowProxy\n"

    local fields = collect_fields(selected, col_defs)
    emit_fields(parts, fields)

    parts[#parts + 1] = "\nlocal row = {}\n\n"
    emit_accessors(parts, fields, row_class, build_tag)
    emit_table_interface(parts, table_name, row_class, tbl_class, target_build)

    parts[#parts + 1] = "return {}\n"
    return table.concat(parts)
end

-- ===========================================================================
-- Section 2 — Workspace metadata (_workspace.lua)
-- ===========================================================================

--- Generates overloads for DbcWorkspace_<build> and dbc.Workspace.
---@param builds_data table<build_tag, {build_str, short_name, tables}>
---@return string
local function generate_workspace_meta(builds_data)
    local parts = {}
    parts[#parts + 1] = "---@meta\n"
    parts[#parts + 1] = "-- Auto-generated overloads and table accessors for multi-version DbcWorkspace. Do not edit.\n\n"
    parts[#parts + 1] = "---@class DbcWorkspace\n"
    parts[#parts + 1] = "---@field build? string Configured target client build\n"
    parts[#parts + 1] = "---@field source_dir string Input directory\n"
    parts[#parts + 1] = "---@field output_dir string Output directory\n\n"

    local sorted_btags = sorted_keys(builds_data)

    for _, btag in ipairs(sorted_btags) do
        local binfo = builds_data[btag]
        local ws_class = "DbcWorkspace_" .. btag

        parts[#parts + 1] = "---Workspace for WoW Build " .. binfo.build_str
            .. " (" .. binfo.short_name .. ").\n"
        parts[#parts + 1] = "---@class " .. ws_class .. " : DbcWorkspace\n"

        local sorted_tables = sorted_keys(binfo.tables)

        for _, t in ipairs(sorted_tables) do
            parts[#parts + 1] = "---@field " .. t .. " dbc.Table." .. btag .. "." .. t .. "\n"
        end
        parts[#parts + 1] = "\n"

        for _, t in ipairs(sorted_tables) do
            parts[#parts + 1] = "---@overload fun(self: " .. ws_class
                .. ", name: '\"" .. t .. "\"'): dbc.Table." .. btag .. "." .. t .. "\n"
        end
        parts[#parts + 1] = "function " .. ws_class .. ":Open(name) end\n\n"

        for _, t in ipairs(sorted_tables) do
            parts[#parts + 1] = "---@overload fun(self: " .. ws_class
                .. ", name: '\"" .. t .. "\"'): dbc.Table." .. btag .. "." .. t .. "\n"
        end
        parts[#parts + 1] = "function " .. ws_class .. ":Create(name) end\n\n"
    end

    parts[#parts + 1] = "---@class dbc\n"
    for _, btag in ipairs(sorted_btags) do
        local binfo = builds_data[btag]
        local ws_class = "DbcWorkspace_" .. btag
        local bstr = binfo.build_str
        local sname = binfo.short_name
        parts[#parts + 1] = "---@overload fun(options: { build: '\"" .. bstr
            .. "\"'|'\"" .. sname .. "\"', source?: string, out?: string }): "
            .. ws_class .. "\n"
        parts[#parts + 1] = "---@overload fun(build_or_source: '\"" .. bstr
            .. "\"'|'\"" .. sname .. "\"'): " .. ws_class .. "\n"
    end
    parts[#parts + 1] = "function dbc.Workspace(options_or_source, output_dir) end\n\n"
    parts[#parts + 1] = "return {}\n"

    return table.concat(parts)
end

-- ===========================================================================
-- Section 3 — Table name alias (_tables.lua)
-- ===========================================================================

--- Generates the dbc.TableName alias listing every known table.
---@param builds_data table
---@return string
local function generate_tables_meta(builds_data)
    local all_tables = {}
    for _, info in pairs(builds_data) do
        for t in pairs(info.tables) do
            all_tables[t] = true
        end
    end

    local parts = {}
    parts[#parts + 1] = "---@meta\n"
    parts[#parts + 1] = "-- Auto-generated table name aliases for LuaLS. Do not edit.\n\n"
    parts[#parts + 1] = "---Every DBC/DB2 table supported by lua-dbc.\n"
    parts[#parts + 1] = "---@alias dbc.TableName\n"

    for _, t in ipairs(sorted_keys(all_tables)) do
        parts[#parts + 1] = "---| '\"" .. t .. "\"'\n"
    end

    return table.concat(parts)
end

-- ===========================================================================
-- Section 4 — Enum metadata (_enums.lua)
-- ===========================================================================

--- Loads a single enum file in isolation and returns its table.
--- Returns nil when the file is missing or fails to load.
---@param path string
---@return table|nil enum_def
---@return string|nil err
local function load_enum_file(path)
    local content = fs.read(path)
    if not content then
        return nil, "cannot read file"
    end

    local chunk, err = loadstring_fn(content, "@" .. path)
    if not chunk then
        return nil, "syntax error: " .. tostring(err)
    end

    local ok, result = pcall(chunk)
    if not ok then
        return nil, "runtime error: " .. tostring(result)
    end
    if type(result) ~= "table" then
        return nil, "module did not return a table"
    end

    return result
end

--- Emits a `---@class dbc.enums.<Name>` block for a single enum.
---@param parts table Output buffer
---@param enum_name string
---@param enum_def table
local function emit_enum_class(parts, enum_name, enum_def)
    parts[#parts + 1] = "---The " .. enum_name .. " enumeration.\n"
    parts[#parts + 1] = "---@class dbc.enums." .. enum_name .. "\n"

    if type(enum_def.values) == "table" then
        for _, k in ipairs(sorted_keys(enum_def.values)) do
            parts[#parts + 1] = "---@field " .. k .. " integer\n"
        end
    end

    if type(enum_def.bits) == "table" then
        for _, k in ipairs(sorted_keys(enum_def.bits)) do
            parts[#parts + 1] = "---@field " .. k .. " integer\n"
        end
        parts[#parts + 1] = "---@field flags table<string, integer>\n"
    end

    parts[#parts + 1] = "\n"
end

--- Generates _enums.lua by scanning src/enums/*.lua.
---@param enums_dir string
---@return string|nil content
---@return integer count
local function generate_enums_meta(enums_dir)
    if not fs.isdir(enums_dir) then
        return nil, 0
    end

    local files = fs.listdir(enums_dir, ".lua")
    if #files == 0 then
        return nil, 0
    end

    local parts = {}
    parts[#parts + 1] = "---@meta\n"
    parts[#parts + 1] = "-- Auto-generated enum stubs for LuaLS. Do not edit.\n"
    parts[#parts + 1] = "-- Generated from src/enums/*.lua\n\n"

    local enum_names = {}
    local failed = {}

    for _, jf in ipairs(files) do
        local enum_name = jf:gsub("%.lua$", "")
        local path = fs.join(enums_dir, jf)

        local enum_def, err = load_enum_file(path)
        if enum_def then
            enum_names[enum_name] = true
            emit_enum_class(parts, enum_name, enum_def)
        else
            failed[#failed + 1] = enum_name .. " (" .. tostring(err) .. ")"
        end
    end

    -- Emit the dbc.Enums registry class so `dbc.Enums.` autocompletes.
    parts[#parts + 1] = "---Registry for accessing enums by name.\n"
    parts[#parts + 1] = "---Example: dbc.Enums.ItemQuality.PURPLE\n"
    parts[#parts + 1] = "---@class dbc.Enums\n"

    for _, name in ipairs(sorted_keys(enum_names)) do
        parts[#parts + 1] = "---@field " .. name .. " dbc.enums." .. name .. "\n"
    end

    return table.concat(parts), #failed
end

-- ===========================================================================
-- Section 5 — Main pipeline
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Per-build processing
-- ---------------------------------------------------------------------------

--- Processes all JSON definitions for one target build.
--- Writes one .lua file per table into meta/dbc/<build_tag>/.
--- Returns the list of successfully written tables plus counters.
---@param def_dir string
---@param meta_dir string
---@param json_files string[]
---@param bstr string
---@return table result { build_str, short_name, tables, skipped, errors }
local function process_build(def_dir, meta_dir, json_files, bstr)
    local timer = cli.timer()
    local btag = dbd_common.get_build_tag(bstr)
    local short_name = bstr:match("^(%d+%.%d+%.%d+)") or bstr

    local v_meta_dir = fs.join(meta_dir, "dbc", btag)
    fs.mkdir(v_meta_dir)

    local tables  = {}
    local skipped = 0
    local errors  = 0

    for _, jf in ipairs(json_files) do
        local table_name = jf:gsub("%.json$", "")

        local content = fs.read(fs.join(def_dir, jf))
        if not content then
            errors = errors + 1
            cli.log(LOG, "  [read-fail] %s", jf)
            goto continue
        end

        local ok_decode, db_def = pcall(json.decode, content)
        if not ok_decode then
            errors = errors + 1
            cli.log(LOG, "  [json-fail] %s: %s", jf, tostring(db_def))
            goto continue
        end

        local ok_gen, output = pcall(generate_table_meta,
            table_name, db_def, bstr, btag)
        if not ok_gen then
            errors = errors + 1
            cli.log(LOG, "  [gen-fail] %s: %s", jf, tostring(output))
            goto continue
        end

        if not output then
            skipped = skipped + 1
            goto continue
        end

        local out_path = fs.join(v_meta_dir, table_name .. ".lua")
        if not fs.write(out_path, output) then
            errors = errors + 1
            cli.log(LOG, "  [write-fail] %s", table_name .. ".lua")
        else
            tables[table_name] = true
        end

        ::continue::
    end

    local table_count = 0
    for _ in pairs(tables) do table_count = table_count + 1 end

    cli.log(LOG, "  %-16s %d tables, %d skipped, %d errors (%s)",
        bstr, table_count, skipped, errors, cli.format_duration(timer()))

    return {
        build_str  = bstr,
        short_name = short_name,
        tables     = tables,
        skipped    = skipped,
        errors     = errors,
    }
end

-- ---------------------------------------------------------------------------
-- Argument parsing
-- ---------------------------------------------------------------------------

-- ===========================================================================
-- Section 5 — Core Library API metadata (_core.lua)
-- ===========================================================================

local function generate_core_meta()
    return [[---@meta
-- Auto-generated LuaLS annotations for lua-dbc core library API. Do not edit.

---@class dbc
---@field File table Low-level DbcFile interface
---@field Table DbcTable Table class
---@field RowProxy RowProxy Record wrapper class
---@field Query dbc.Query LINQ query constructor
---@field Schemas dbc.Schemas Schema registry
---@field Enums dbc.Enums Enum registry
---@field Workspace DbcWorkspace Workspace constructor
---@field Database DbcWorkspace Workspace alias
---@field Session DbcWorkspace Legacy workspace alias
---@field Relations dbc.Relations Relations catalog
---@field Formats table Formats dispatcher & drivers
---@field JSON table JSON encoder/decoder
local dbc = {}

---Opens a single DBC or DB2 file from disk with automatic format detection.
---@param path string Path to the .dbc or .db2 file on disk
---@param schema_name? string Optional schema name (e.g. "Spell"). Inferred from filename if omitted.
---@param build? string Optional client build (e.g. "3.3.5.12340")
---@return DbcTable table Opened table instance
function dbc.Open(path, schema_name, build) end

---Creates a blank in-memory database table.
---@param schema_name string Schema name (e.g. "Spell", "Item")
---@param format_name? string Format identifier (defaults to "WDBC"). Supports "WDBC", "WDB2".
---@param build? string Optional client build (e.g. "3.3.5.12340")
---@return DbcTable table Blank table instance
function dbc.Create(schema_name, format_name, build) end

---Creates a new build-scoped workspace.
---@param options_or_source? table|string Options table `{ source = "...", out = "...", build = "..." }` or source directory path
---@param output_dir? string Output directory path (if first argument was a string)
---@return DbcWorkspace workspace
function dbc.Workspace(options_or_source, output_dir) end

---Creates a new build-scoped workspace (legacy alias).
---@param options_or_source? table|string
---@param output_dir? string
---@return DbcWorkspace
function dbc.NewSession(options_or_source, output_dir) end

---Wraps any table, array, or iterator function into a LINQ query pipeline.
---@generic T
---@param source T[]|fun():T|DbcTable
---@return dbc.Query<T>
function dbc.Query(source) end

---Overrides the primary definitions search directory.
---@param path string Directory path
function dbc.SetDefinitionsDir(path) end

---Adds a fallback definitions search directory.
---@param path string Directory path
function dbc.AddDefinitionsDir(path) end

---Adds an additional directory to search for relation indexes.
---@param path string Directory path
function dbc.AddRelationsIndexDir(path) end

---Fetches outbound relations declared for a given table and build.
---@param schema_name string Table name
---@param build? string Client build
---@return table[]
function dbc.GetRelations(schema_name, build) end

-- ---------------------------------------------------------------------------
-- DbcTable
-- ---------------------------------------------------------------------------

---High-level DBC/DB2 table wrapper around binary records.
---@class DbcTable
---@field _file table Low-level DbcFile driver
---@field _workspace? DbcWorkspace Owning workspace, if any
---@field [integer] RowProxy Direct primary-key row access (e.g. tbl[133])
local DbcTable = {}

---Returns the total number of records in the table.
---@return integer count
function DbcTable:Count() end

---Returns a cached RowProxy for a 1-based physical row index.
---@param row integer 1-based index (1..Count())
---@return RowProxy
function DbcTable:GetRowByIndex(row) end

---Fetches a row by primary key (ID). Raises an error if the ID does not exist.
---@param id integer Primary key
---@return RowProxy
function DbcTable:GetRowById(id) end

---Fetches a row by primary key (ID). Returns nil if not found.
---@param id integer Primary key
---@return RowProxy|nil
function DbcTable:FindById(id) end

---Checks whether a record with the given primary key exists in the table.
---@param id integer Primary key
---@return boolean exists
function DbcTable:Has(id) end

---Returns the highest primary key ID currently in the table (0 if empty).
---@return integer max_id
function DbcTable:GetMaxID() end

---Creates a new row with an explicit numeric primary key.
---@param id integer Primary key
---@param data? table Optional field values table
---@return RowProxy created_row
function DbcTable:Create(id, data) end

---Creates a new row with an auto-incremented primary key (max_id + 1).
---@param data? table Optional field values table
---@return RowProxy created_row
function DbcTable:NewRow(data) end

---Appends an existing row copy into this table.
---@param row RowProxy|table Row object to clone into this table
---@param new_id? integer Optional new primary key ID
---@return RowProxy inserted_row
function DbcTable:AddRow(row, new_id) end

---Deletes a record by primary key ID.
---@param id integer Primary key
---@return boolean success
function DbcTable:DeleteRow(id) end

---Deletes a record by 1-based physical index.
---@param row integer 1-based index
---@return boolean success
function DbcTable:DeleteRowByIndex(row) end

---Saves the table back to its original file or explicit path.
---@param path? string Optional target path
---@return boolean success
function DbcTable:Save(path) end

---Saves the table to a specified file path.
---@param path string Target file path
---@return boolean success
function DbcTable:SaveAs(path) end

---Reloads the table data from its underlying file.
---@return boolean success
function DbcTable:Reload() end

---Exports records as an array of plain Lua tables.
---@param start_index? integer 1-based start index (default 1)
---@param count? integer Number of records to extract
---@return table[]
function DbcTable:Extract(start_index, count) end

---Converts all records to an array of plain Lua tables.
---@return table[]
function DbcTable:ToTable() end

---Prints a formatted summary of table records to stdout.
---@param limit? integer Maximum rows to dump
---@param columns? string[] Optional subset of column names
function DbcTable:DumpRows(limit, columns) end

---Returns an array of field names declared in the schema.
---@return string[]
function DbcTable:GetColumnNames() end

---Returns the 32-bit layout hash of the table schema if defined.
---@return string|nil
function DbcTable:GetLayoutHash() end

---Returns the byte size of a field by column index or name.
---@param col integer|string Column index or name
---@return integer bytes
function DbcTable:GetFieldSize(col) end

---Returns the raw header structure of the table format.
---@return table
function DbcTable:GetHeader() end

---Returns the format identifier string (e.g. "WDBC", "WDB2", "WDC1").
---@return string
function DbcTable:GetFormatName() end

---Returns the file path from which the table was loaded, if any.
---@return string|nil
function DbcTable:GetFileName() end

---Returns the schema definition attached to this table.
---@return table|nil
function DbcTable:GetSchema() end

---Returns the parent workspace, if this table belongs to one.
---@return DbcWorkspace|nil
function DbcTable:GetWorkspace() end

---Filters table rows matching a predicate.
---@param predicate fun(row: RowProxy, index: integer): boolean
---@return dbc.Query<RowProxy>
function DbcTable:Where(predicate) end

---Projects table rows into a new sequence.
---@generic R
---@param selector fun(row: RowProxy, index: integer): R
---@return dbc.Query<R>
function DbcTable:Select(selector) end

---Returns the first row matching an optional predicate. Raises if not found.
---@param predicate? fun(row: RowProxy): boolean
---@return RowProxy
function DbcTable:First(predicate) end

---Returns the first row matching an optional predicate, or default.
---@param predicate? fun(row: RowProxy): boolean
---@param default_val? any
---@return RowProxy|any
function DbcTable:FirstOrDefault(predicate, default_val) end

---Returns the single matching row. Raises if 0 or >1 rows match.
---@param predicate? fun(row: RowProxy): boolean
---@return RowProxy
function DbcTable:Single(predicate) end

---Checks if any row matches an optional predicate.
---@param predicate? fun(row: RowProxy): boolean
---@return boolean
function DbcTable:Any(predicate) end

---Checks if all rows match a predicate.
---@param predicate fun(row: RowProxy): boolean
---@return boolean
function DbcTable:All(predicate) end

---Sorts table rows in ascending order by key.
---@param key_selector? fun(row: RowProxy): any
---@return dbc.Query<RowProxy>
function DbcTable:OrderBy(key_selector) end

---Sorts table rows in descending order by key.
---@param key_selector? fun(row: RowProxy): any
---@return dbc.Query<RowProxy>
function DbcTable:OrderByDescending(key_selector) end

---Bypasses count records.
---@param count integer
---@return dbc.Query<RowProxy>
function DbcTable:Skip(count) end

---Takes count records.
---@param count integer
---@return dbc.Query<RowProxy>
function DbcTable:Take(count) end

---Returns unique rows by key selector.
---@param key_selector? fun(row: RowProxy): any
---@return dbc.Query<RowProxy>
function DbcTable:Distinct(key_selector) end

---Executes an action on each row.
---@param action fun(row: RowProxy, index: integer)
function DbcTable:ForEach(action) end

---Groups rows by a key selector.
---@param key_selector fun(row: RowProxy): any
---@return table<any, RowProxy[]>
function DbcTable:GroupBy(key_selector) end

---Computes the sum of sequence values extracted by selector.
---@param selector? fun(row: RowProxy): number
---@return number
function DbcTable:Sum(selector) end

---Computes the average of sequence values extracted by selector.
---@param selector? fun(row: RowProxy): number
---@return number
function DbcTable:Average(selector) end

---Returns the minimum value extracted by selector.
---@param selector? fun(row: RowProxy): number
---@return number
function DbcTable:Min(selector) end

---Returns the maximum value extracted by selector.
---@param selector? fun(row: RowProxy): number
---@return number
function DbcTable:Max(selector) end

---Sets the output format for subsequent Save operations.
---@param format_name string E.g. "WDBC", "WDB2"
---@return DbcTable self
function DbcTable:SetFormat(format_name) end

---Converts this table into a new format, returning a new DbcTable instance.
---@param format_name string E.g. "WDBC", "WDB2"
---@return DbcTable
function DbcTable:ToFormat(format_name) end

---Begins a batch modification transaction.
---@return table batch
function DbcTable:BeginBatch() end

---Returns outbound relations declared for this table's schema.
---@return table[]
function DbcTable:GetRelations() end

---Returns the underlying DbcFile driver.
---@return table
function DbcTable:GetFile() end

---Returns an iterator over all records: `for id, row in tbl:iter() do ... end`.
---@return fun(): integer, RowProxy
function DbcTable:iter() end

-- ---------------------------------------------------------------------------
-- RowProxy
-- ---------------------------------------------------------------------------

---Dynamic flyweight proxy wrapping a binary record inside a DbcTable.
---@class RowProxy
---@field ID integer Primary key of the record
---@field [string] any Dynamic field read/write access (e.g. row.SpellName, row.MinRange)
local RowProxy = {}

---Gets a field value by column name or 1-based index.
---@param field string|integer
---@return any
function RowProxy:Get(field) end

---Sets a field value by column name or 1-based index.
---@param field string|integer
---@param value any
function RowProxy:Set(field, value) end

---Checks if a field exists in the schema.
---@param field string
---@return boolean
function RowProxy:HasField(field) end

---Gets a field value by column name or 1-based index.
---@param field string|integer
---@return any
function RowProxy:GetField(field) end

---Sets a field value by column name or 1-based index.
---@param field string|integer
---@param value any
function RowProxy:SetField(field, value) end

---Copies the record into a plain Lua key-value table.
---@return table<string, any>
function RowProxy:ToTable() end

---Creates a detached clone of this record's field values.
---@return table<string, any>
function RowProxy:Clone() end

---Populates multiple fields from a key-value table.
---@param values table<string, any>
---@return RowProxy self
function RowProxy:Populate(values) end

---Resolves a foreign key to a record in another table.
---@param target_table string Foreign table name
---@param foreign_id integer Foreign ID
---@param target_column? string Target column name (defaults to "ID")
---@return RowProxy|nil
function RowProxy:ResolveRelation(target_table, foreign_id, target_column) end

---Resolves a foreign key using the column name on this record (e.g. "SpellIconID").
---@param field_name string Field name containing the foreign key
---@return RowProxy|nil
function RowProxy:Resolve(field_name) end

---Resolves a relation by target table name or field name.
---@param target_table_or_field string
---@return RowProxy|nil
function RowProxy:GetRelated(target_table_or_field) end

---Creates a related row in the target table and automatically assigns this row's foreign key.
---@param target_table_or_field string Target table name (e.g. "SpellIcon")
---@param row_data_or_id? table|integer Data table for the new row or specific ID
---@return RowProxy created_row
function RowProxy:CreateRelated(target_table_or_field, row_data_or_id) end

---Returns child rows from other tables referencing this record's primary key.
---@param child_table_name? string Specific child table name
---@param child_field_name? string Specific foreign key field name on child
---@return RowProxy[] children
function RowProxy:GetChildren(child_table_name, child_field_name) end

---Returns all relations currently declared for this record.
---@return table[]
function RowProxy:GetRelations() end

---Returns true if the record pointer and row index are valid.
---@return boolean
function RowProxy:IsValid() end

---Returns the 1-based physical row index of this record.
---@return integer
function RowProxy:GetIndex() end

---Returns the attached schema for this record's table.
---@return table|nil
function RowProxy:GetSchema() end

---Returns the parent DbcTable.
---@return DbcTable|nil
function RowProxy:GetTable() end

---Returns the parent DbcFile driver.
---@return table
function RowProxy:GetFile() end

-- ---------------------------------------------------------------------------
-- dbc.Query<T>
-- ---------------------------------------------------------------------------

---LINQ-style query pipeline engine.
---@class dbc.Query<T>
local Query = {}

---Filters elements by a predicate function.
---@param predicate fun(item: T, index: integer): boolean
---@return dbc.Query<T>
function Query:Where(predicate) end

---Projects each element into a new form.
---@generic R
---@param selector fun(item: T, index: integer): R
---@return dbc.Query<R>
function Query:Select(selector) end

---Sorts elements in ascending order by key.
---@param key_selector? fun(item: T): any Key extractor function
---@param descending? boolean Set true for descending order
---@return dbc.Query<T>
function Query:OrderBy(key_selector, descending) end

---Sorts elements in descending order by key.
---@param key_selector? fun(item: T): any Key extractor function
---@return dbc.Query<T>
function Query:OrderByDescending(key_selector) end

---Bypasses a specified number of elements and returns the remaining elements.
---@param count integer Elements to skip
---@return dbc.Query<T>
function Query:Skip(count) end

---Returns a specified number of contiguous elements from the start of a sequence.
---@param count integer Elements to take
---@return dbc.Query<T>
function Query:Take(count) end

---Returns distinct elements from a sequence based on an optional key selector.
---@param key_selector? fun(item: T): any
---@return dbc.Query<T>
function Query:Distinct(key_selector) end

---Materializes the query into an array table.
---@return T[]
function Query:ToList() end

---Creates a lookup dictionary grouped by key.
---@param key_selector fun(item: T): any
---@param element_selector? fun(item: T): any
---@return table<any, any[]>
function Query:ToLookup(key_selector, element_selector) end

---Returns the first element matching an optional predicate. Raises if none.
---@param predicate? fun(item: T): boolean
---@return T
function Query:First(predicate) end

---Returns the first element matching an optional predicate, or default value.
---@generic D
---@param predicate? fun(item: T): boolean|nil
---@param default_value? D
---@return T|D
function Query:FirstOrDefault(predicate, default_value) end

---Returns the last element matching an optional predicate. Raises if none.
---@param predicate? fun(item: T): boolean
---@return T
function Query:Last(predicate) end

---Returns the last element matching an optional predicate, or default value.
---@generic D
---@param predicate? fun(item: T): boolean|nil
---@param default_value? D
---@return T|D
function Query:LastOrDefault(predicate, default_value) end

---Returns the single, specific element of a sequence. Raises if sequence contains 0 or >1 elements.
---@param predicate? fun(item: T): boolean
---@return T
function Query:Single(predicate) end

---Determines whether any element satisfies a condition.
---@param predicate? fun(item: T): boolean
---@return boolean
function Query:Any(predicate) end

---Determines whether all elements satisfy a condition.
---@param predicate fun(item: T): boolean
---@return boolean
function Query:All(predicate) end

---Returns the number of elements matching an optional predicate.
---@param predicate? fun(item: T): boolean
---@return integer
function Query:Count(predicate) end

---Returns the maximum value extracted by selector.
---@param selector? fun(item: T): number
---@return number
function Query:Max(selector) end

---Returns the minimum value extracted by selector.
---@param selector? fun(item: T): number
---@return number
function Query:Min(selector) end

---Computes the sum of sequence values extracted by selector.
---@param selector? fun(item: T): number
---@return number
function Query:Sum(selector) end

---Computes the average of sequence values extracted by selector.
---@param selector? fun(item: T): number
---@return number
function Query:Average(selector) end

---Groups elements by key.
---@param key_selector fun(item: T): any
---@return table<any, T[]>
function Query:GroupBy(key_selector) end

---Performs an action on each element of the materialized sequence.
---@param action fun(item: T, index: integer)
function Query:ForEach(action) end

-- ---------------------------------------------------------------------------
-- dbc.Schemas
-- ---------------------------------------------------------------------------

---WoWDBDefs schema registry.
---@class dbc.Schemas
---@field [string] table Dynamic schema access via dot syntax (e.g. Schemas.Spell)
local Schemas = {}

---Retrieves and caches a schema definition for a table and build.
---@param name string Table name (e.g. "Spell")
---@param build_or_hash? string Client build or layout hash
---@return table schema
function Schemas.Get(name, build_or_hash) end

---Checks if a schema definition exists for a table and build.
---@param name string Table name
---@param build_or_hash? string Client build or layout hash
---@return boolean exists
function Schemas.Has(name, build_or_hash) end

---Returns all foreign key relations declared in a schema.
---@param schema_or_name string|table
---@param build_or_hash? string
---@return table[]
function Schemas.GetRelations(schema_or_name, build_or_hash) end

---Sets the primary directory for definitions JSON files.
---@param path string
function Schemas.SetDefinitionsDir(path) end

---Registers an additional definitions search directory.
---@param path string
function Schemas.AddDefinitionsDir(path) end

---Sets the fallback build used when none is specified.
---@param build string
function Schemas.SetDefaultBuild(build) end

---Returns the configured fallback client build.
---@return string build
function Schemas.GetDefaultBuild() end

-- ---------------------------------------------------------------------------
-- dbc.Relations
-- ---------------------------------------------------------------------------

---Bidirectional foreign-key relations catalog.
---@class dbc.Relations
local Relations = {}

---Returns outbound relations from a given table for a client build.
---@param table_name string Table name
---@param build_str? string Client build
---@return table[]
function Relations.Get(table_name, build_str) end

---Returns inbound relations (tables pointing to this target table).
---@param target_table string Target table name
---@param build_str? string Client build
---@return table[]
function Relations.GetInbound(target_table, build_str) end

---Finds a specific relation by source table and target or field name.
---@param table_name string Source table name
---@param target_or_field string Target table or foreign key field name
---@param build_str? string Client build
---@return table|nil
function Relations.Find(table_name, target_or_field, build_str) end

---Adds a search directory for _relations index files.
---@param path string Directory path
function Relations.AddIndexDir(path) end

-- ---------------------------------------------------------------------------
-- dbc.Enums
-- ---------------------------------------------------------------------------

---Enum registry providing lazy loading and bitmask precomputations.
---@class dbc.Enums
---@field [string] table Dynamic enum access via dot syntax (e.g. Enums.ItemQuality)
local Enums = {}

---Retrieves an enum table by name.
---@param name string Enum name
---@return table enum
function Enums.Get(name) end

---Checks if an enum with the given name exists.
---@param name string
---@return boolean
function Enums.Has(name) end

return dbc
]]
end

local function parse_args(argv)
    local opts = dbd_common.parse_cli(argv, {
        positional = { "def_dir", "meta_dir" },
    })
    return {
        def_dir  = opts.positional.def_dir  or "definitions",
        meta_dir = opts.positional.meta_dir or "meta",
        builds   = opts.builds,
    }
end

-- ---------------------------------------------------------------------------
-- Main
-- ---------------------------------------------------------------------------

local function main(argv)
    local opts = parse_args(argv)
    local def_dir  = opts.def_dir
    local meta_dir = opts.meta_dir

    if not fs.isdir(def_dir) then
        cli.log(LOG, "Definitions directory '%s' not found.", def_dir)
        return
    end

    fs.mkdir(meta_dir)

    cli.log(LOG, "def_dir=%s meta_dir=%s builds=%s", def_dir, meta_dir, opts.builds)

    -- Collect JSON files from the definitions directory.
    local json_files = {}
    for _, f in ipairs(fs.listdir(def_dir, ".json")) do
        if f:sub(1, 1) ~= "_" then
            json_files[#json_files + 1] = f
        end
    end

    if #json_files == 0 then
        cli.log(LOG, "No .json file found in %s", def_dir)
        return
    end

    -- Resolve the target build list.
    local build_targets
    if opts.builds == "auto" then
        cli.log(LOG, "Discovering builds...")
        build_targets = dbd_common.discover_builds(def_dir, json_files, fs, json)
        cli.log(LOG, "%d builds found.", #build_targets)
    else
        build_targets = dbd_common.split_builds(opts.builds)
    end

    if #build_targets == 0 then
        cli.log(LOG, "No builds to process.")
        return
    end

    -- Generate per-build metadata.
    local builds_data = {}
    for _, bstr in ipairs(build_targets) do
        local btag = dbd_common.get_build_tag(bstr)
        local result = process_build(def_dir, meta_dir, json_files, bstr)
        builds_data[btag] = {
            build_str  = result.build_str,
            short_name = result.short_name,
            tables     = result.tables,
        }
    end

    -- Core library metadata (dbc, DbcTable, DbcWorkspace, RowProxy, Query).
    fs.write(fs.join(meta_dir, "_core.lua"), generate_core_meta())
    cli.log(LOG, "_core.lua written (Core library LuaLS annotations).")

    -- Shared metadata files.
    fs.write(fs.join(meta_dir, "_workspace.lua"),
        generate_workspace_meta(builds_data))
    cli.log(LOG, "_workspace.lua written.")

    fs.write(fs.join(meta_dir, "_tables.lua"),
        generate_tables_meta(builds_data))
    cli.log(LOG, "_tables.lua written.")

    local enums_dir = fs.isdir("src/dbc/enums") and "src/dbc/enums" or "src/enums"
    local enums_content, failed = generate_enums_meta(enums_dir)
    if enums_content then
        fs.write(fs.join(meta_dir, "_enums.lua"), enums_content)
        if failed and failed > 0 then
            cli.log(LOG, "_enums.lua written (%d enum files failed to load).", failed)
        else
            cli.log(LOG, "_enums.lua written.")
        end
    else
        cli.log(LOG, "_enums.lua skipped: no enums found in %s.", enums_dir)
    end

    cli.log(LOG, "Done: %d builds in '%s/'.", #build_targets, meta_dir)
end

main(arg or {})