--[[
    tools/generate_meta.lua
    Generates LuaLS (EmmyLua) annotations for lua-dbc.

    Output layout:
        meta/
        ├── _workspace.lua         # dbc.Workspace overloads + DbcWorkspace_<build>
        ├── _tables.lua            # dbc.TableName alias (all known table names)
        ├── _enums.lua             # dbc.Enums field accessors and enum classes
        └── dbc/
            └── v<tag>/
                ├── Spell.lua      # dbc.row.v335.Spell and dbc.Table.v335.Spell
                └── ...

    The enum metadata is generated by scanning src/enums/*.lua. Each enum
    file is loaded in isolation to introspect its `values` and `bits` tables,
    then a compact `---@class dbc.enums.<Name>` block is emitted.

    Usage:
        luajit tools/generate_meta.lua [definitions_dir] [meta_dir] [--builds auto|3.3.5.12340,...]
]]

-- ---------------------------------------------------------------------------
-- Path setup
-- ---------------------------------------------------------------------------

package.path = "?.lua;src/?.lua;src/?/init.lua;tools/?.lua;" .. package.path

-- ---------------------------------------------------------------------------
-- Dependencies
-- ---------------------------------------------------------------------------

local json       = require("tools.json_pretty")
local fs         = require("tools.fs")
local cli        = require("tools.cli")
local dbd_common = require("tools.dbd_common")

local LOG = "LuaLS Generator"

cli.log(LOG, "JSON backend: %s", json.backend_name())

-- ---------------------------------------------------------------------------
-- Shared constants
-- ---------------------------------------------------------------------------

-- Maps DBDefs column types to LuaLS primitive types.
local LUA_TYPE_MAP = {
    locstring = "string",
    string    = "string",
    float     = "number",
    bool      = "boolean",
    int       = "integer",
    uint      = "integer",
}

-- Cross-platform `load` (LuaJIT provides `loadstring`; Lua 5.2+ has `load`).
local loadstring_fn = loadstring or load

-- ---------------------------------------------------------------------------
-- Small helpers
-- ---------------------------------------------------------------------------

local function pascal_case(name)
    if not name or name == "" then return "" end
    return name:sub(1, 1):upper() .. name:sub(2)
end

--- Returns a sorted list of the keys of a table.
local function sorted_keys(t)
    local keys = {}
    for k in pairs(t) do keys[#keys + 1] = k end
    table.sort(keys)
    return keys
end

-- ===========================================================================
-- Section 1 — Per-table metadata (dbc.row.<build>.<Table> / dbc.Table.<build>.<Table>)
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Field collection
-- ---------------------------------------------------------------------------

--- Extracts the field list for a table from its selected version definition.
--- Applies columnDefinitions metadata (foreignTable, foreignColumn, comment)
--- and falls back to a name-based heuristic for FK detection.
---@param selected table Version definition
---@param col_defs table columnDefinitions from the DBD JSON
---@return table[]
local function collect_fields(selected, col_defs)
    local fields = {}
    local seen = {}

    for _, d in ipairs(selected.definitions or {}) do
        local fname = d.name
        if fname and not seen[fname] then
            seen[fname] = true

            local cmeta = col_defs[fname] or {}
            local base_lua_type = LUA_TYPE_MAP[cmeta.type or "int"] or "any"
            local arr_len = tonumber(d.arrLength) or 0
            local lua_type = arr_len > 0 and (base_lua_type .. "[]") or base_lua_type

            local comment = d.comment or cmeta.comment or ""
            comment = comment:gsub("\n", " "):gsub("^%s+", ""):gsub("%s+$", "")

            local ftarget = cmeta.foreignTable
            if not ftarget and fname:sub(-2) == "ID" and fname ~= "ID" then
                ftarget = fname:sub(1, -3)
            end

            fields[#fields + 1] = {
                name           = fname,
                lua_type       = lua_type,
                base_lua_type  = base_lua_type,
                is_array       = arr_len > 0,
                foreign_table  = ftarget,
                foreign_column = cmeta.foreignColumn or "ID",
                comment        = comment,
            }
        end
    end

    return fields
end

-- ---------------------------------------------------------------------------
-- Emitters for the row class
-- ---------------------------------------------------------------------------

--- Emits `---@field` lines for each collected field.
local function emit_fields(parts, fields)
    for _, f in ipairs(fields) do
        if f.comment ~= "" then
            parts[#parts + 1] = "---@field " .. f.name .. " " .. f.lua_type
                .. " " .. f.comment .. "\n"
        else
            parts[#parts + 1] = "---@field " .. f.name .. " " .. f.lua_type .. "\n"
        end
    end
end

--- Emits getter, setter, array accessor and relation navigator for each field.
local function emit_accessors(parts, fields, row_class, build_tag)
    for _, f in ipairs(fields) do
        local fname = f.name
        local pname = pascal_case(fname)
        local ltype = f.lua_type

        -- Getter
        parts[#parts + 1] = "---Gets the value of field '" .. fname .. "'.\n"
        parts[#parts + 1] = "---@return " .. ltype .. " value\n"
        parts[#parts + 1] = "function row:Get" .. pname .. "() end\n\n"

        -- Setter
        parts[#parts + 1] = "---Sets the value of field '" .. fname .. "'.\n"
        parts[#parts + 1] = "---@param value " .. ltype .. "\n"
        parts[#parts + 1] = "---@return " .. row_class .. " self\n"
        parts[#parts + 1] = "function row:Set" .. pname .. "(value) end\n\n"

        -- Array item accessor
        if f.is_array then
            parts[#parts + 1] = "---Gets element at 1-based index in '" .. fname .. "'.\n"
            parts[#parts + 1] = "---@param index integer\n"
            parts[#parts + 1] = "---@return " .. f.base_lua_type .. " value\n"
            parts[#parts + 1] = "function row:Get" .. pname .. "Item(index) end\n\n"
        end

        -- Foreign key navigation
        if f.foreign_table and f.foreign_table ~= "" then
            local target_row_class = "dbc.row." .. build_tag .. "." .. f.foreign_table

            local rel_name
            if fname:sub(-2) == "ID" and fname ~= "ID" then
                rel_name = fname:sub(1, -3)
            elseif fname:sub(-3) == "_ID" then
                rel_name = fname:sub(1, -4)
            else
                rel_name = fname
            end
            local rel_pname = pascal_case(rel_name)

            parts[#parts + 1] = "---Navigates foreign relationship to '"
                .. f.foreign_table .. "' via '" .. fname .. "'.\n"
            parts[#parts + 1] = "---@return " .. target_row_class .. "|nil\n"
            parts[#parts + 1] = "function row:Get" .. rel_pname .. "() end\n\n"

            parts[#parts + 1] = "---Creates a related '" .. f.foreign_table
                .. "' row and automatically links '" .. fname .. "'.\n"
            parts[#parts + 1] = "---@param data? table\n"
            parts[#parts + 1] = "---@return " .. target_row_class .. "\n"
            parts[#parts + 1] = "function row:CreateRelated(data) end\n\n"
        end
    end
end

-- ---------------------------------------------------------------------------
-- Emitters for the table class
-- ---------------------------------------------------------------------------

--- Emits the DbcTable subclass methods (Create, FindById, Query, ...).
local function emit_table_interface(parts, table_name, row_class, tbl_class, target_build)
    parts[#parts + 1] = "---Table container for " .. table_name
        .. " (Build " .. target_build .. ").\n"
    parts[#parts + 1] = "---@class " .. tbl_class .. " : DbcTable\n"
    parts[#parts + 1] = "---@field [integer] " .. row_class .. "\n"
    parts[#parts + 1] = "local tbl = {}\n\n"

    local methods = {
        {
            name   = "Create",
            params = "id, data",
            doc    = "Creates and appends a new row to the table.",
            lines  = {
                "---@param id? integer Primary key",
                "---@param data? table Optional initial values",
            },
            ret = row_class,
        },
        {
            name   = "FindById",
            params = "id",
            doc    = "Finds a row by primary key (nil if not found).",
            lines  = { "---@param id integer" },
            ret    = row_class .. "|nil",
        },
        {
            name   = "GetRowById",
            params = "id",
            doc    = "Gets a row by primary key (throws if not found).",
            lines  = { "---@param id integer" },
            ret    = row_class,
        },
        {
            name   = "Query",
            params = "",
            doc    = "Creates a LINQ query over rows in this table.",
            lines  = {},
            ret    = "dbc.Query<" .. row_class .. ">",
        },
        {
            name   = "GetByRelation",
            params = "foreign_id",
            doc    = "Returns all rows related to a foreign ID via the relationship block.",
            lines  = { "---@param foreign_id integer" },
            ret    = row_class .. "[]",
        },
    }

    for _, m in ipairs(methods) do
        parts[#parts + 1] = "---" .. m.doc .. "\n"
        for _, line in ipairs(m.lines) do
            parts[#parts + 1] = line .. "\n"
        end
        parts[#parts + 1] = "---@return " .. m.ret .. "\n"
        parts[#parts + 1] = "function tbl:" .. m.name .. "(" .. m.params .. ") end\n\n"
    end
end

-- ---------------------------------------------------------------------------
-- Table metadata entry point
-- ---------------------------------------------------------------------------

--- Generates the .lua source for one table in one build.
--- Returns nil when the table is absent from the build.
---@param table_name string
---@param db_def table Parsed DBD JSON
---@param target_build string
---@param build_tag string
---@return string|nil
local function generate_table_meta(table_name, db_def, target_build, build_tag)
    local selected = dbd_common.select_version_definition(
        db_def.versionDefinitions or {}, target_build)
    if not selected or not selected.definitions then return nil end

    local col_defs = db_def.columnDefinitions or {}
    local row_class = "dbc.row." .. build_tag .. "." .. table_name
    local tbl_class = "dbc.Table." .. build_tag .. "." .. table_name

    local parts = {}
    parts[#parts + 1] = "---@meta\n"
    parts[#parts + 1] = "-- Generated LuaLS annotations for " .. table_name
        .. " (Build " .. target_build .. " [" .. build_tag .. "]). Do not edit.\n\n"
    parts[#parts + 1] = "---Row representation of " .. table_name
        .. " in build " .. target_build .. ".\n"
    parts[#parts + 1] = "---@class " .. row_class .. " : RowProxy\n"

    local fields = collect_fields(selected, col_defs)
    emit_fields(parts, fields)

    parts[#parts + 1] = "\nlocal row = {}\n\n"
    emit_accessors(parts, fields, row_class, build_tag)
    emit_table_interface(parts, table_name, row_class, tbl_class, target_build)

    parts[#parts + 1] = "return {}\n"
    return table.concat(parts)
end

-- ===========================================================================
-- Section 2 — Workspace metadata (_workspace.lua)
-- ===========================================================================

--- Generates overloads for DbcWorkspace_<build> and dbc.Workspace.
---@param builds_data table<build_tag, {build_str, short_name, tables}>
---@return string
local function generate_workspace_meta(builds_data)
    local parts = {}
    parts[#parts + 1] = "---@meta\n"
    parts[#parts + 1] = "-- Auto-generated overloads and table accessors for multi-version DbcWorkspace. Do not edit.\n\n"
    parts[#parts + 1] = "---@class DbcWorkspace\n"
    parts[#parts + 1] = "---@field build? string Configured target client build\n"
    parts[#parts + 1] = "---@field source_dir string Input directory\n"
    parts[#parts + 1] = "---@field output_dir string Output directory\n\n"

    local sorted_btags = sorted_keys(builds_data)

    for _, btag in ipairs(sorted_btags) do
        local binfo = builds_data[btag]
        local ws_class = "DbcWorkspace_" .. btag

        parts[#parts + 1] = "---Workspace for WoW Build " .. binfo.build_str
            .. " (" .. binfo.short_name .. ").\n"
        parts[#parts + 1] = "---@class " .. ws_class .. " : DbcWorkspace\n"

        local sorted_tables = sorted_keys(binfo.tables)

        for _, t in ipairs(sorted_tables) do
            parts[#parts + 1] = "---@field " .. t .. " dbc.Table." .. btag .. "." .. t .. "\n"
        end
        parts[#parts + 1] = "\n"

        for _, t in ipairs(sorted_tables) do
            parts[#parts + 1] = "---@overload fun(self: " .. ws_class
                .. ", name: '\"" .. t .. "\"'): dbc.Table." .. btag .. "." .. t .. "\n"
        end
        parts[#parts + 1] = "function " .. ws_class .. ":Open(name) end\n\n"

        for _, t in ipairs(sorted_tables) do
            parts[#parts + 1] = "---@overload fun(self: " .. ws_class
                .. ", name: '\"" .. t .. "\"'): dbc.Table." .. btag .. "." .. t .. "\n"
        end
        parts[#parts + 1] = "function " .. ws_class .. ":Create(name) end\n\n"
    end

    parts[#parts + 1] = "---@class dbc\n"
    for _, btag in ipairs(sorted_btags) do
        local binfo = builds_data[btag]
        local ws_class = "DbcWorkspace_" .. btag
        local bstr = binfo.build_str
        local sname = binfo.short_name
        parts[#parts + 1] = "---@overload fun(options: { build: '\"" .. bstr
            .. "\"'|'\"" .. sname .. "\"', source?: string, out?: string }): "
            .. ws_class .. "\n"
        parts[#parts + 1] = "---@overload fun(build_or_source: '\"" .. bstr
            .. "\"'|'\"" .. sname .. "\"'): " .. ws_class .. "\n"
    end
    parts[#parts + 1] = "function dbc.Workspace(options_or_source, output_dir) end\n\n"
    parts[#parts + 1] = "return {}\n"

    return table.concat(parts)
end

-- ===========================================================================
-- Section 3 — Table name alias (_tables.lua)
-- ===========================================================================

--- Generates the dbc.TableName alias listing every known table.
---@param builds_data table
---@return string
local function generate_tables_meta(builds_data)
    local all_tables = {}
    for _, info in pairs(builds_data) do
        for t in pairs(info.tables) do
            all_tables[t] = true
        end
    end

    local parts = {}
    parts[#parts + 1] = "---@meta\n"
    parts[#parts + 1] = "-- Auto-generated table name aliases for LuaLS. Do not edit.\n\n"
    parts[#parts + 1] = "---Every DBC/DB2 table supported by lua-dbc.\n"
    parts[#parts + 1] = "---@alias dbc.TableName\n"

    for _, t in ipairs(sorted_keys(all_tables)) do
        parts[#parts + 1] = "---| '\"" .. t .. "\"'\n"
    end

    return table.concat(parts)
end

-- ===========================================================================
-- Section 4 — Enum metadata (_enums.lua)
-- ===========================================================================

--- Loads a single enum file in isolation and returns its table.
--- Returns nil when the file is missing or fails to load.
---@param path string
---@return table|nil enum_def
---@return string|nil err
local function load_enum_file(path)
    local content = fs.read(path)
    if not content then
        return nil, "cannot read file"
    end

    local chunk, err = loadstring_fn(content, "@" .. path)
    if not chunk then
        return nil, "syntax error: " .. tostring(err)
    end

    local ok, result = pcall(chunk)
    if not ok then
        return nil, "runtime error: " .. tostring(result)
    end
    if type(result) ~= "table" then
        return nil, "module did not return a table"
    end

    return result
end

--- Emits a `---@class dbc.enums.<Name>` block for a single enum.
---@param parts table Output buffer
---@param enum_name string
---@param enum_def table
local function emit_enum_class(parts, enum_name, enum_def)
    parts[#parts + 1] = "---The " .. enum_name .. " enumeration.\n"
    parts[#parts + 1] = "---@class dbc.enums." .. enum_name .. "\n"

    if type(enum_def.values) == "table" then
        for _, k in ipairs(sorted_keys(enum_def.values)) do
            parts[#parts + 1] = "---@field " .. k .. " integer\n"
        end
    end

    if type(enum_def.bits) == "table" then
        for _, k in ipairs(sorted_keys(enum_def.bits)) do
            parts[#parts + 1] = "---@field " .. k .. " integer\n"
        end
        parts[#parts + 1] = "---@field flags table<string, integer>\n"
    end

    parts[#parts + 1] = "\n"
end

--- Generates _enums.lua by scanning src/enums/*.lua.
---@param enums_dir string
---@return string|nil content
---@return integer count
local function generate_enums_meta(enums_dir)
    if not fs.isdir(enums_dir) then
        return nil, 0
    end

    local files = fs.listdir(enums_dir, ".lua")
    if #files == 0 then
        return nil, 0
    end

    local parts = {}
    parts[#parts + 1] = "---@meta\n"
    parts[#parts + 1] = "-- Auto-generated enum stubs for LuaLS. Do not edit.\n"
    parts[#parts + 1] = "-- Generated from src/enums/*.lua\n\n"

    local enum_names = {}
    local failed = {}

    for _, jf in ipairs(files) do
        local enum_name = jf:gsub("%.lua$", "")
        local path = fs.join(enums_dir, jf)

        local enum_def, err = load_enum_file(path)
        if enum_def then
            enum_names[enum_name] = true
            emit_enum_class(parts, enum_name, enum_def)
        else
            failed[#failed + 1] = enum_name .. " (" .. tostring(err) .. ")"
        end
    end

    -- Emit the dbc.Enums registry class so `dbc.Enums.` autocompletes.
    parts[#parts + 1] = "---Registry for accessing enums by name.\n"
    parts[#parts + 1] = "---Example: dbc.Enums.ItemQuality.PURPLE\n"
    parts[#parts + 1] = "---@class dbc.Enums\n"

    for _, name in ipairs(sorted_keys(enum_names)) do
        parts[#parts + 1] = "---@field " .. name .. " dbc.enums." .. name .. "\n"
    end

    return table.concat(parts), #failed
end

-- ===========================================================================
-- Section 5 — Main pipeline
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Per-build processing
-- ---------------------------------------------------------------------------

--- Processes all JSON definitions for one target build.
--- Writes one .lua file per table into meta/dbc/<build_tag>/.
--- Returns the list of successfully written tables plus counters.
---@param def_dir string
---@param meta_dir string
---@param json_files string[]
---@param bstr string
---@return table result { build_str, short_name, tables, skipped, errors }
local function process_build(def_dir, meta_dir, json_files, bstr)
    local timer = cli.timer()
    local btag = dbd_common.get_build_tag(bstr)
    local short_name = bstr:match("^(%d+%.%d+%.%d+)") or bstr

    local v_meta_dir = fs.join(meta_dir, "dbc", btag)
    fs.mkdir(v_meta_dir)

    local tables  = {}
    local skipped = 0
    local errors  = 0

    for _, jf in ipairs(json_files) do
        local table_name = jf:gsub("%.json$", "")

        local content = fs.read(fs.join(def_dir, jf))
        if not content then
            errors = errors + 1
            cli.log(LOG, "  [read-fail] %s", jf)
            goto continue
        end

        local ok_decode, db_def = pcall(json.decode, content)
        if not ok_decode then
            errors = errors + 1
            cli.log(LOG, "  [json-fail] %s: %s", jf, tostring(db_def))
            goto continue
        end

        local ok_gen, output = pcall(generate_table_meta,
            table_name, db_def, bstr, btag)
        if not ok_gen then
            errors = errors + 1
            cli.log(LOG, "  [gen-fail] %s: %s", jf, tostring(output))
            goto continue
        end

        if not output then
            skipped = skipped + 1
            goto continue
        end

        local out_path = fs.join(v_meta_dir, table_name .. ".lua")
        if not fs.write(out_path, output) then
            errors = errors + 1
            cli.log(LOG, "  [write-fail] %s", table_name .. ".lua")
        else
            tables[table_name] = true
        end

        ::continue::
    end

    local table_count = 0
    for _ in pairs(tables) do table_count = table_count + 1 end

    cli.log(LOG, "  %-16s %d tables, %d skipped, %d errors (%s)",
        bstr, table_count, skipped, errors, cli.format_duration(timer()))

    return {
        build_str  = bstr,
        short_name = short_name,
        tables     = tables,
        skipped    = skipped,
        errors     = errors,
    }
end

-- ---------------------------------------------------------------------------
-- Argument parsing
-- ---------------------------------------------------------------------------

local function parse_args(argv)
    local opts = dbd_common.parse_cli(argv, {
        positional = { "def_dir", "meta_dir" },
    })
    return {
        def_dir  = opts.positional.def_dir  or "definitions",
        meta_dir = opts.positional.meta_dir or "meta",
        builds   = opts.builds,
    }
end

-- ---------------------------------------------------------------------------
-- Main
-- ---------------------------------------------------------------------------

local function main(argv)
    local opts = parse_args(argv)
    local def_dir  = opts.def_dir
    local meta_dir = opts.meta_dir

    cli.log(LOG, "def_dir=%s meta_dir=%s builds=%s", def_dir, meta_dir, opts.builds)

    -- Collect JSON files from the definitions directory.
    local json_files = {}
    for _, f in ipairs(fs.listdir(def_dir, ".json")) do
        if f:sub(1, 1) ~= "_" then
            json_files[#json_files + 1] = f
        end
    end

    if #json_files == 0 then
        cli.log(LOG, "No .json file found in %s", def_dir)
        return
    end

    -- Resolve the target build list.
    local build_targets
    if opts.builds == "auto" then
        cli.log(LOG, "Discovering builds...")
        build_targets = dbd_common.discover_builds(def_dir, json_files, fs, json)
        cli.log(LOG, "%d builds found.", #build_targets)
    else
        build_targets = dbd_common.split_builds(opts.builds)
    end

    if #build_targets == 0 then
        cli.log(LOG, "No builds to process.")
        return
    end

    -- Generate per-build metadata.
    local builds_data = {}
    for _, bstr in ipairs(build_targets) do
        local btag = dbd_common.get_build_tag(bstr)
        local result = process_build(def_dir, meta_dir, json_files, bstr)
        builds_data[btag] = {
            build_str  = result.build_str,
            short_name = result.short_name,
            tables     = result.tables,
        }
    end

    -- Shared metadata files.
    fs.write(fs.join(meta_dir, "_workspace.lua"),
        generate_workspace_meta(builds_data))
    cli.log(LOG, "_workspace.lua written.")

    fs.write(fs.join(meta_dir, "_tables.lua"),
        generate_tables_meta(builds_data))
    cli.log(LOG, "_tables.lua written.")

    local enums_content, failed = generate_enums_meta("src/enums")
    if enums_content then
        fs.write(fs.join(meta_dir, "_enums.lua"), enums_content)
        if failed and failed > 0 then
            cli.log(LOG, "_enums.lua written (%d enum files failed to load).", failed)
        else
            cli.log(LOG, "_enums.lua written.")
        end
    else
        cli.log(LOG, "_enums.lua skipped: no src/enums/*.lua found.")
    end

    cli.log(LOG, "Done: %d builds in '%s/'.", #build_targets, meta_dir)
end

main(arg or {})