return {
  name = "AuraStateType",
  kind = "enum",
  values = {
    NONE = 0,
    DEFENSE = 1,
    HEALTHLESS_20_PERCENT = 2,
    BERSERKING = 3,
    FROZEN = 4,
    JUDGEMENT = 5,
    HUNTER_PARRY = 7,
    WARRIOR_VICTORY_RUSH = 10,
    FAERIE_FIRE = 12,
    HEALTHLESS_35_PERCENT = 13,
    CONFLAGRATE = 14,
    SWIFTMEND = 15,
    DEADLY_POISON = 16,
    ENRAGE = 17,
    BLEEDING = 18,
    UNKNOWN19 = 19,
    UNKNOWN22 = 22,
    HEALTH_ABOVE_75_PERCENT = 23,
  },
  names = {
    [0] = "NONE",
    [1] = "DEFENSE",
    [2] = "HEALTHLESS_20_PERCENT",
    [3] = "BERSERKING",
    [4] = "FROZEN",
    [5] = "JUDGEMENT",
    [7] = "HUNTER_PARRY",
    [10] = "WARRIOR_VICTORY_RUSH",
    [12] = "FAERIE_FIRE",
    [13] = "HEALTHLESS_35_PERCENT",
    [14] = "CONFLAGRATE",
    [15] = "SWIFTMEND",
    [16] = "DEADLY_POISON",
    [17] = "ENRAGE",
    [18] = "BLEEDING",
    [19] = "UNKNOWN19",
    [22] = "UNKNOWN22",
    [23] = "HEALTH_ABOVE_75_PERCENT",
  },
}
