return {
  name = "BagFamily",
  kind = "enum",
  values = {
    NONE = 0,
    ARROWS = 1,
    BULLETS = 2,
    SOUL_SHARDS = 4,
    LEATHERWORKING = 8,
    INSCRIPTION_SUPPLIES = 16,
    HERBS = 32,
    ENCHANTING_SUPPLIES = 64,
    ENGINEERING_SUPPLIES = 128,
    KEYS = 256,
    GEMS = 512,
    MINING_SUPPLIES = 1024,
    SOULBOUND_EQUIPMENT = 2048,
    VANITY_PETS = 4096,
    CURRENCY_TOKENS = 8192,
    QUEST_ITEMS = 16384,
  },
  names = {
    [0] = "NONE",
    [1] = "ARROWS",
    [2] = "BULLETS",
    [4] = "SOUL_SHARDS",
    [8] = "LEATHERWORKING",
    [16] = "INSCRIPTION_SUPPLIES",
    [32] = "HERBS",
    [64] = "ENCHANTING_SUPPLIES",
    [128] = "ENGINEERING_SUPPLIES",
    [256] = "KEYS",
    [512] = "GEMS",
    [1024] = "MINING_SUPPLIES",
    [2048] = "SOULBOUND_EQUIPMENT",
    [4096] = "VANITY_PETS",
    [8192] = "CURRENCY_TOKENS",
    [16384] = "QUEST_ITEMS",
  },
}
