return {
  name = "CombatRating",
  kind = "enum",
  values = {
    WEAPON_SKILL = 0,
    DEFENSE_SKILL = 1,
    DODGE = 2,
    PARRY = 3,
    BLOCK = 4,
    HIT_MELEE = 5,
    HIT_RANGED = 6,
    HIT_SPELL = 7,
    CRIT_MELEE = 8,
    CRIT_RANGED = 9,
    CRIT_SPELL = 10,
    HIT_TAKEN_MELEE = 11,
    HIT_TAKEN_RANGED = 12,
    HIT_TAKEN_SPELL = 13,
    CRIT_TAKEN_MELEE = 14,
    CRIT_TAKEN_RANGED = 15,
    CRIT_TAKEN_SPELL = 16,
    HASTE_MELEE = 17,
    HASTE_RANGED = 18,
    HASTE_SPELL = 19,
  },
  names = {
    [0] = "WEAPON_SKILL",
    [1] = "DEFENSE_SKILL",
    [2] = "DODGE",
    [3] = "PARRY",
    [4] = "BLOCK",
    [5] = "HIT_MELEE",
    [6] = "HIT_RANGED",
    [7] = "HIT_SPELL",
    [8] = "CRIT_MELEE",
    [9] = "CRIT_RANGED",
    [10] = "CRIT_SPELL",
    [11] = "HIT_TAKEN_MELEE",
    [12] = "HIT_TAKEN_RANGED",
    [13] = "HIT_TAKEN_SPELL",
    [14] = "CRIT_TAKEN_MELEE",
    [15] = "CRIT_TAKEN_RANGED",
    [16] = "CRIT_TAKEN_SPELL",
    [17] = "HASTE_MELEE",
    [18] = "HASTE_RANGED",
    [19] = "HASTE_SPELL",
  },
}
