return {
  name = "CreatureFactionTemplate",
  kind = "enum",
  values = {
    NeutralNonAggressive = 7,
    Stormwind = 11,
    NeutralHostile = 21,
    NeutralPassive = 35,
    Ironforge = 57,
    Gnomeregan = 64,
    Ratchet = 69,
    Undercity = 71,
    Darnassus = 79,
    Orgrimmar = 85,
    ThunderBluff = 105,
    BloodsailBuccaneers = 119,
    BootyBay = 121,
    DarkspearTrolls = 126,
    Gadgetzan = 474,
    CenarionCircle = 994,
    Silvermoon = 1604,
    Exodar = 1639,
    Shatar = 1741,
    KirinTor = 2007,
  },
  names = {
    [7] = "NeutralNonAggressive",
    [11] = "Stormwind",
    [21] = "NeutralHostile",
    [35] = "NeutralPassive",
    [57] = "Ironforge",
    [64] = "Gnomeregan",
    [69] = "Ratchet",
    [71] = "Undercity",
    [79] = "Darnassus",
    [85] = "Orgrimmar",
    [105] = "ThunderBluff",
    [119] = "BloodsailBuccaneers",
    [121] = "BootyBay",
    [126] = "DarkspearTrolls",
    [474] = "Gadgetzan",
    [994] = "CenarionCircle",
    [1604] = "Silvermoon",
    [1639] = "Exodar",
    [1741] = "Shatar",
    [2007] = "KirinTor",
  },
}
