return {
  name = "GossipOptionType",
  kind = "enum",
  values = {
    SPIRIT_HEALER = 6,
    SPIRIT_GUIDE = 7,
    INNKEEPER = 8,
    BANKER = 9,
    PETITION = 10,
    TABARD_DESIGNER = 11,
    AUCTIONEER = 13,
    STABLE_MASTER = 14,
    UNLEARN_TALENTS = 16,
    UNLEARN_PET_TALENTS = 17,
    DUAL_SPEC = 18,
  },
  names = {
    [6] = "SPIRIT_HEALER",
    [7] = "SPIRIT_GUIDE",
    [8] = "INNKEEPER",
    [9] = "BANKER",
    [10] = "PETITION",
    [11] = "TABARD_DESIGNER",
    [13] = "AUCTIONEER",
    [14] = "STABLE_MASTER",
    [16] = "UNLEARN_TALENTS",
    [17] = "UNLEARN_PET_TALENTS",
    [18] = "DUAL_SPEC",
  },
}
