---@meta
-- Generated LuaLS annotations for Achievement.dbc. Do not edit.

---Row representation of Achievement.dbc.
---@class dbc.row.Achievement : RowProxy
---@field ID integer
---@field Faction integer
---@field Map integer
---@field Previous integer
---@field Title string
---@field Description string
---@field Category integer
---@field Points integer
---@field Ui_Order integer
---@field Flags integer
---@field IconID integer
---@field Reward string
---@field Minimum_Criteria integer
---@field Shares_Criteria integer

-- Fluent PascalCase Methods for Achievement
---@field GetID fun(self: dbc.row.Achievement): integer
---@field SetID fun(self: dbc.row.Achievement, value: integer): dbc.row.Achievement
---@field GetFaction fun(self: dbc.row.Achievement): integer
---@field SetFaction fun(self: dbc.row.Achievement, value: integer): dbc.row.Achievement
---@field GetMap fun(self: dbc.row.Achievement): integer
---@field SetMap fun(self: dbc.row.Achievement, value: integer): dbc.row.Achievement
---@field GetPrevious fun(self: dbc.row.Achievement): integer
---@field SetPrevious fun(self: dbc.row.Achievement, value: integer): dbc.row.Achievement
---@field GetTitle fun(self: dbc.row.Achievement, locale?: string|integer): string
---@field SetTitle fun(self: dbc.row.Achievement, value: string, locale?: string|integer): dbc.row.Achievement
---@field GetDescription fun(self: dbc.row.Achievement, locale?: string|integer): string
---@field SetDescription fun(self: dbc.row.Achievement, value: string, locale?: string|integer): dbc.row.Achievement
---@field GetCategory fun(self: dbc.row.Achievement): integer
---@field SetCategory fun(self: dbc.row.Achievement, value: integer): dbc.row.Achievement
---@field GetPoints fun(self: dbc.row.Achievement): integer
---@field SetPoints fun(self: dbc.row.Achievement, value: integer): dbc.row.Achievement
---@field GetUi_Order fun(self: dbc.row.Achievement): integer
---@field SetUi_Order fun(self: dbc.row.Achievement, value: integer): dbc.row.Achievement
---@field GetFlags fun(self: dbc.row.Achievement): integer
---@field SetFlags fun(self: dbc.row.Achievement, value: integer): dbc.row.Achievement
---@field HasFlags fun(self: dbc.row.Achievement, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.Achievement, flag: integer): dbc.row.Achievement
---@field RemoveFlags fun(self: dbc.row.Achievement, flag: integer): dbc.row.Achievement
---@field GetIconID fun(self: dbc.row.Achievement): integer
---@field SetIconID fun(self: dbc.row.Achievement, value: integer): dbc.row.Achievement
---@field GetReward fun(self: dbc.row.Achievement, locale?: string|integer): string
---@field SetReward fun(self: dbc.row.Achievement, value: string, locale?: string|integer): dbc.row.Achievement
---@field GetMinimum_Criteria fun(self: dbc.row.Achievement): integer
---@field SetMinimum_Criteria fun(self: dbc.row.Achievement, value: integer): dbc.row.Achievement
---@field GetShares_Criteria fun(self: dbc.row.Achievement): integer
---@field SetShares_Criteria fun(self: dbc.row.Achievement, value: integer): dbc.row.Achievement

-- Inferred Cross-Table Relations for Achievement
---@field GetFaction fun(self: dbc.row.Achievement): dbc.row.Faction|nil
---@field SetFaction fun(self: dbc.row.Achievement, target: dbc.row.Faction|integer): dbc.row.Achievement

-- Cascading Creation & Relations Engine for Achievement
---@field CreateRelated fun(self: dbc.row.Achievement, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.Achievement, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.Achievement, child_table: string, child_field?: string): any[]

---Typed table handle for Achievement.dbc.
---@class dbc.Table.Achievement : DbcTable
---@field FindById fun(self: dbc.Table.Achievement, id: integer): dbc.row.Achievement|nil
---@field GetById fun(self: dbc.Table.Achievement, id: integer): dbc.row.Achievement|nil
---@field GetRow fun(self: dbc.Table.Achievement, row: integer): dbc.row.Achievement
---@field NewRow fun(self: dbc.Table.Achievement, id?: integer): dbc.row.Achievement
---@field Create fun(self: dbc.Table.Achievement, id?: integer): dbc.row.Achievement
---@field CreateNext fun(self: dbc.Table.Achievement, data?: table): dbc.row.Achievement
---@field CloneRow fun(self: dbc.Table.Achievement, source: integer|dbc.row.Achievement, new_id?: integer): dbc.row.Achievement
---@field GetAllRows fun(self: dbc.Table.Achievement): dbc.row.Achievement[]
---@field Query fun(self: dbc.Table.Achievement): dbc.Query<dbc.row.Achievement>
---@field Rows fun(self: dbc.Table.Achievement): fun(): integer, dbc.row.Achievement
