---@meta
-- Generated LuaLS annotations for Achievement_Criteria.dbc. Do not edit.

---Row representation of Achievement_Criteria.dbc.
---@class dbc.row.Achievement_Criteria : RowProxy
---@field ID integer
---@field Achievement_Id integer
---@field Type integer
---@field Asset_Id integer
---@field Quantity integer
---@field Start_Event integer
---@field Start_Asset integer
---@field Fail_Event integer
---@field Fail_Asset integer
---@field Description string
---@field Flags integer
---@field Timer_Start_Event integer
---@field Timer_Asset_Id integer
---@field Timer_Time integer
---@field Ui_Order integer

-- Fluent PascalCase Methods for Achievement_Criteria
---@field GetID fun(self: dbc.row.Achievement_Criteria): integer
---@field SetID fun(self: dbc.row.Achievement_Criteria, value: integer): dbc.row.Achievement_Criteria
---@field GetAchievement_Id fun(self: dbc.row.Achievement_Criteria): integer
---@field SetAchievement_Id fun(self: dbc.row.Achievement_Criteria, value: integer): dbc.row.Achievement_Criteria
---@field GetType fun(self: dbc.row.Achievement_Criteria): integer
---@field SetType fun(self: dbc.row.Achievement_Criteria, value: integer): dbc.row.Achievement_Criteria
---@field GetAsset_Id fun(self: dbc.row.Achievement_Criteria): integer
---@field SetAsset_Id fun(self: dbc.row.Achievement_Criteria, value: integer): dbc.row.Achievement_Criteria
---@field GetQuantity fun(self: dbc.row.Achievement_Criteria): integer
---@field SetQuantity fun(self: dbc.row.Achievement_Criteria, value: integer): dbc.row.Achievement_Criteria
---@field GetStart_Event fun(self: dbc.row.Achievement_Criteria): integer
---@field SetStart_Event fun(self: dbc.row.Achievement_Criteria, value: integer): dbc.row.Achievement_Criteria
---@field GetStart_Asset fun(self: dbc.row.Achievement_Criteria): integer
---@field SetStart_Asset fun(self: dbc.row.Achievement_Criteria, value: integer): dbc.row.Achievement_Criteria
---@field GetFail_Event fun(self: dbc.row.Achievement_Criteria): integer
---@field SetFail_Event fun(self: dbc.row.Achievement_Criteria, value: integer): dbc.row.Achievement_Criteria
---@field GetFail_Asset fun(self: dbc.row.Achievement_Criteria): integer
---@field SetFail_Asset fun(self: dbc.row.Achievement_Criteria, value: integer): dbc.row.Achievement_Criteria
---@field GetDescription fun(self: dbc.row.Achievement_Criteria, locale?: string|integer): string
---@field SetDescription fun(self: dbc.row.Achievement_Criteria, value: string, locale?: string|integer): dbc.row.Achievement_Criteria
---@field GetFlags fun(self: dbc.row.Achievement_Criteria): integer
---@field SetFlags fun(self: dbc.row.Achievement_Criteria, value: integer): dbc.row.Achievement_Criteria
---@field HasFlags fun(self: dbc.row.Achievement_Criteria, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.Achievement_Criteria, flag: integer): dbc.row.Achievement_Criteria
---@field RemoveFlags fun(self: dbc.row.Achievement_Criteria, flag: integer): dbc.row.Achievement_Criteria
---@field GetTimer_Start_Event fun(self: dbc.row.Achievement_Criteria): integer
---@field SetTimer_Start_Event fun(self: dbc.row.Achievement_Criteria, value: integer): dbc.row.Achievement_Criteria
---@field GetTimer_Asset_Id fun(self: dbc.row.Achievement_Criteria): integer
---@field SetTimer_Asset_Id fun(self: dbc.row.Achievement_Criteria, value: integer): dbc.row.Achievement_Criteria
---@field GetTimer_Time fun(self: dbc.row.Achievement_Criteria): integer
---@field SetTimer_Time fun(self: dbc.row.Achievement_Criteria, value: integer): dbc.row.Achievement_Criteria
---@field GetUi_Order fun(self: dbc.row.Achievement_Criteria): integer
---@field SetUi_Order fun(self: dbc.row.Achievement_Criteria, value: integer): dbc.row.Achievement_Criteria

-- Inferred Cross-Table Relations for Achievement_Criteria

-- Cascading Creation & Relations Engine for Achievement_Criteria
---@field CreateRelated fun(self: dbc.row.Achievement_Criteria, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.Achievement_Criteria, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.Achievement_Criteria, child_table: string, child_field?: string): any[]

---Typed table handle for Achievement_Criteria.dbc.
---@class dbc.Table.Achievement_Criteria : DbcTable
---@field FindById fun(self: dbc.Table.Achievement_Criteria, id: integer): dbc.row.Achievement_Criteria|nil
---@field GetById fun(self: dbc.Table.Achievement_Criteria, id: integer): dbc.row.Achievement_Criteria|nil
---@field GetRow fun(self: dbc.Table.Achievement_Criteria, row: integer): dbc.row.Achievement_Criteria
---@field NewRow fun(self: dbc.Table.Achievement_Criteria, id?: integer): dbc.row.Achievement_Criteria
---@field Create fun(self: dbc.Table.Achievement_Criteria, id?: integer): dbc.row.Achievement_Criteria
---@field CreateNext fun(self: dbc.Table.Achievement_Criteria, data?: table): dbc.row.Achievement_Criteria
---@field CloneRow fun(self: dbc.Table.Achievement_Criteria, source: integer|dbc.row.Achievement_Criteria, new_id?: integer): dbc.row.Achievement_Criteria
---@field GetAllRows fun(self: dbc.Table.Achievement_Criteria): dbc.row.Achievement_Criteria[]
---@field Query fun(self: dbc.Table.Achievement_Criteria): dbc.Query<dbc.row.Achievement_Criteria>
---@field Rows fun(self: dbc.Table.Achievement_Criteria): fun(): integer, dbc.row.Achievement_Criteria
