---@meta
-- Generated LuaLS annotations for AreaTrigger.dbc. Do not edit.

---Row representation of AreaTrigger.dbc.
---@class dbc.row.AreaTrigger : RowProxy
---@field ID integer
---@field MapID integer
---@field X number
---@field Y number
---@field Z number
---@field Radius number
---@field Box_Length number
---@field Box_Width number
---@field Box_Height number
---@field Box_Yaw number

-- Fluent PascalCase Methods for AreaTrigger
---@field GetID fun(self: dbc.row.AreaTrigger): integer
---@field SetID fun(self: dbc.row.AreaTrigger, value: integer): dbc.row.AreaTrigger
---@field GetMapID fun(self: dbc.row.AreaTrigger): integer
---@field SetMapID fun(self: dbc.row.AreaTrigger, value: integer): dbc.row.AreaTrigger
---@field GetX fun(self: dbc.row.AreaTrigger): number
---@field SetX fun(self: dbc.row.AreaTrigger, value: number): dbc.row.AreaTrigger
---@field GetY fun(self: dbc.row.AreaTrigger): number
---@field SetY fun(self: dbc.row.AreaTrigger, value: number): dbc.row.AreaTrigger
---@field GetZ fun(self: dbc.row.AreaTrigger): number
---@field SetZ fun(self: dbc.row.AreaTrigger, value: number): dbc.row.AreaTrigger
---@field GetRadius fun(self: dbc.row.AreaTrigger): number
---@field SetRadius fun(self: dbc.row.AreaTrigger, value: number): dbc.row.AreaTrigger
---@field GetBox_Length fun(self: dbc.row.AreaTrigger): number
---@field SetBox_Length fun(self: dbc.row.AreaTrigger, value: number): dbc.row.AreaTrigger
---@field GetBox_Width fun(self: dbc.row.AreaTrigger): number
---@field SetBox_Width fun(self: dbc.row.AreaTrigger, value: number): dbc.row.AreaTrigger
---@field GetBox_Height fun(self: dbc.row.AreaTrigger): number
---@field SetBox_Height fun(self: dbc.row.AreaTrigger, value: number): dbc.row.AreaTrigger
---@field GetBox_Yaw fun(self: dbc.row.AreaTrigger): number
---@field SetBox_Yaw fun(self: dbc.row.AreaTrigger, value: number): dbc.row.AreaTrigger

-- Inferred Cross-Table Relations for AreaTrigger
---@field GetMap fun(self: dbc.row.AreaTrigger): dbc.row.Map|nil
---@field SetMap fun(self: dbc.row.AreaTrigger, target: dbc.row.Map|integer): dbc.row.AreaTrigger

-- Cascading Creation & Relations Engine for AreaTrigger
---@field CreateRelated fun(self: dbc.row.AreaTrigger, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.AreaTrigger, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.AreaTrigger, child_table: string, child_field?: string): any[]

---Typed table handle for AreaTrigger.dbc.
---@class dbc.Table.AreaTrigger : DbcTable
---@field FindById fun(self: dbc.Table.AreaTrigger, id: integer): dbc.row.AreaTrigger|nil
---@field GetById fun(self: dbc.Table.AreaTrigger, id: integer): dbc.row.AreaTrigger|nil
---@field GetRow fun(self: dbc.Table.AreaTrigger, row: integer): dbc.row.AreaTrigger
---@field NewRow fun(self: dbc.Table.AreaTrigger, id?: integer): dbc.row.AreaTrigger
---@field Create fun(self: dbc.Table.AreaTrigger, id?: integer): dbc.row.AreaTrigger
---@field CreateNext fun(self: dbc.Table.AreaTrigger, data?: table): dbc.row.AreaTrigger
---@field CloneRow fun(self: dbc.Table.AreaTrigger, source: integer|dbc.row.AreaTrigger, new_id?: integer): dbc.row.AreaTrigger
---@field GetAllRows fun(self: dbc.Table.AreaTrigger): dbc.row.AreaTrigger[]
---@field Query fun(self: dbc.Table.AreaTrigger): dbc.Query<dbc.row.AreaTrigger>
---@field Rows fun(self: dbc.Table.AreaTrigger): fun(): integer, dbc.row.AreaTrigger
