---@meta
-- Generated LuaLS annotations for BarberShopStyle.dbc. Do not edit.

---Row representation of BarberShopStyle.dbc.
---@class dbc.row.BarberShopStyle : RowProxy
---@field ID integer
---@field Type integer
---@field DisplayName string
---@field Description string
---@field Cost_Modifier number
---@field Race integer
---@field Sex integer
---@field Data integer

-- Fluent PascalCase Methods for BarberShopStyle
---@field GetID fun(self: dbc.row.BarberShopStyle): integer
---@field SetID fun(self: dbc.row.BarberShopStyle, value: integer): dbc.row.BarberShopStyle
---@field GetType fun(self: dbc.row.BarberShopStyle): integer
---@field SetType fun(self: dbc.row.BarberShopStyle, value: integer): dbc.row.BarberShopStyle
---@field GetDisplayName fun(self: dbc.row.BarberShopStyle, locale?: string|integer): string
---@field SetDisplayName fun(self: dbc.row.BarberShopStyle, value: string, locale?: string|integer): dbc.row.BarberShopStyle
---@field GetDescription fun(self: dbc.row.BarberShopStyle, locale?: string|integer): string
---@field SetDescription fun(self: dbc.row.BarberShopStyle, value: string, locale?: string|integer): dbc.row.BarberShopStyle
---@field GetCost_Modifier fun(self: dbc.row.BarberShopStyle): number
---@field SetCost_Modifier fun(self: dbc.row.BarberShopStyle, value: number): dbc.row.BarberShopStyle
---@field GetRace fun(self: dbc.row.BarberShopStyle): integer
---@field SetRace fun(self: dbc.row.BarberShopStyle, value: integer): dbc.row.BarberShopStyle
---@field GetSex fun(self: dbc.row.BarberShopStyle): integer
---@field SetSex fun(self: dbc.row.BarberShopStyle, value: integer): dbc.row.BarberShopStyle
---@field GetData fun(self: dbc.row.BarberShopStyle): integer
---@field SetData fun(self: dbc.row.BarberShopStyle, value: integer): dbc.row.BarberShopStyle

-- Inferred Cross-Table Relations for BarberShopStyle

-- Cascading Creation & Relations Engine for BarberShopStyle
---@field CreateRelated fun(self: dbc.row.BarberShopStyle, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.BarberShopStyle, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.BarberShopStyle, child_table: string, child_field?: string): any[]

---Typed table handle for BarberShopStyle.dbc.
---@class dbc.Table.BarberShopStyle : DbcTable
---@field FindById fun(self: dbc.Table.BarberShopStyle, id: integer): dbc.row.BarberShopStyle|nil
---@field GetById fun(self: dbc.Table.BarberShopStyle, id: integer): dbc.row.BarberShopStyle|nil
---@field GetRow fun(self: dbc.Table.BarberShopStyle, row: integer): dbc.row.BarberShopStyle
---@field NewRow fun(self: dbc.Table.BarberShopStyle, id?: integer): dbc.row.BarberShopStyle
---@field Create fun(self: dbc.Table.BarberShopStyle, id?: integer): dbc.row.BarberShopStyle
---@field CreateNext fun(self: dbc.Table.BarberShopStyle, data?: table): dbc.row.BarberShopStyle
---@field CloneRow fun(self: dbc.Table.BarberShopStyle, source: integer|dbc.row.BarberShopStyle, new_id?: integer): dbc.row.BarberShopStyle
---@field GetAllRows fun(self: dbc.Table.BarberShopStyle): dbc.row.BarberShopStyle[]
---@field Query fun(self: dbc.Table.BarberShopStyle): dbc.Query<dbc.row.BarberShopStyle>
---@field Rows fun(self: dbc.Table.BarberShopStyle): fun(): integer, dbc.row.BarberShopStyle
