---@meta
-- Generated LuaLS annotations for CameraShakes.dbc. Do not edit.

---Row representation of CameraShakes.dbc.
---@class dbc.row.CameraShakes : RowProxy
---@field ID integer
---@field ShakeType integer
---@field Direction integer
---@field Amplitude number
---@field Frequency number
---@field Duration number
---@field Phase number
---@field Coefficient number

-- Fluent PascalCase Methods for CameraShakes
---@field GetID fun(self: dbc.row.CameraShakes): integer
---@field SetID fun(self: dbc.row.CameraShakes, value: integer): dbc.row.CameraShakes
---@field GetShakeType fun(self: dbc.row.CameraShakes): integer
---@field SetShakeType fun(self: dbc.row.CameraShakes, value: integer): dbc.row.CameraShakes
---@field GetDirection fun(self: dbc.row.CameraShakes): integer
---@field SetDirection fun(self: dbc.row.CameraShakes, value: integer): dbc.row.CameraShakes
---@field GetAmplitude fun(self: dbc.row.CameraShakes): number
---@field SetAmplitude fun(self: dbc.row.CameraShakes, value: number): dbc.row.CameraShakes
---@field GetFrequency fun(self: dbc.row.CameraShakes): number
---@field SetFrequency fun(self: dbc.row.CameraShakes, value: number): dbc.row.CameraShakes
---@field GetDuration fun(self: dbc.row.CameraShakes): number
---@field SetDuration fun(self: dbc.row.CameraShakes, value: number): dbc.row.CameraShakes
---@field GetPhase fun(self: dbc.row.CameraShakes): number
---@field SetPhase fun(self: dbc.row.CameraShakes, value: number): dbc.row.CameraShakes
---@field GetCoefficient fun(self: dbc.row.CameraShakes): number
---@field SetCoefficient fun(self: dbc.row.CameraShakes, value: number): dbc.row.CameraShakes

-- Inferred Cross-Table Relations for CameraShakes

-- Cascading Creation & Relations Engine for CameraShakes
---@field CreateRelated fun(self: dbc.row.CameraShakes, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.CameraShakes, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.CameraShakes, child_table: string, child_field?: string): any[]

---Typed table handle for CameraShakes.dbc.
---@class dbc.Table.CameraShakes : DbcTable
---@field FindById fun(self: dbc.Table.CameraShakes, id: integer): dbc.row.CameraShakes|nil
---@field GetById fun(self: dbc.Table.CameraShakes, id: integer): dbc.row.CameraShakes|nil
---@field GetRow fun(self: dbc.Table.CameraShakes, row: integer): dbc.row.CameraShakes
---@field NewRow fun(self: dbc.Table.CameraShakes, id?: integer): dbc.row.CameraShakes
---@field Create fun(self: dbc.Table.CameraShakes, id?: integer): dbc.row.CameraShakes
---@field CreateNext fun(self: dbc.Table.CameraShakes, data?: table): dbc.row.CameraShakes
---@field CloneRow fun(self: dbc.Table.CameraShakes, source: integer|dbc.row.CameraShakes, new_id?: integer): dbc.row.CameraShakes
---@field GetAllRows fun(self: dbc.Table.CameraShakes): dbc.row.CameraShakes[]
---@field Query fun(self: dbc.Table.CameraShakes): dbc.Query<dbc.row.CameraShakes>
---@field Rows fun(self: dbc.Table.CameraShakes): fun(): integer, dbc.row.CameraShakes
