---@meta
-- Generated LuaLS annotations for CharSections.dbc. Do not edit.

---Row representation of CharSections.dbc.
---@class dbc.row.CharSections : RowProxy
---@field ID integer
---@field RaceID integer
---@field SexID integer
---@field BaseSection integer
---@field TextureName string[]
---@field Flags integer
---@field VariationIndex integer
---@field ColorIndex integer

-- Fluent PascalCase Methods for CharSections
---@field GetID fun(self: dbc.row.CharSections): integer
---@field SetID fun(self: dbc.row.CharSections, value: integer): dbc.row.CharSections
---@field GetRaceID fun(self: dbc.row.CharSections): integer
---@field SetRaceID fun(self: dbc.row.CharSections, value: integer): dbc.row.CharSections
---@field GetSexID fun(self: dbc.row.CharSections): integer
---@field SetSexID fun(self: dbc.row.CharSections, value: integer): dbc.row.CharSections
---@field GetBaseSection fun(self: dbc.row.CharSections): integer
---@field SetBaseSection fun(self: dbc.row.CharSections, value: integer): dbc.row.CharSections
---@field GetTextureName fun(self: dbc.row.CharSections, index?: integer): string|string[]
---@field SetTextureName fun(self: dbc.row.CharSections, value: string|string[], index?: integer): dbc.row.CharSections
---@field GetFlags fun(self: dbc.row.CharSections): integer
---@field SetFlags fun(self: dbc.row.CharSections, value: integer): dbc.row.CharSections
---@field HasFlags fun(self: dbc.row.CharSections, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.CharSections, flag: integer): dbc.row.CharSections
---@field RemoveFlags fun(self: dbc.row.CharSections, flag: integer): dbc.row.CharSections
---@field GetVariationIndex fun(self: dbc.row.CharSections): integer
---@field SetVariationIndex fun(self: dbc.row.CharSections, value: integer): dbc.row.CharSections
---@field GetColorIndex fun(self: dbc.row.CharSections): integer
---@field SetColorIndex fun(self: dbc.row.CharSections, value: integer): dbc.row.CharSections

-- Inferred Cross-Table Relations for CharSections

-- Cascading Creation & Relations Engine for CharSections
---@field CreateRelated fun(self: dbc.row.CharSections, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.CharSections, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.CharSections, child_table: string, child_field?: string): any[]

---Typed table handle for CharSections.dbc.
---@class dbc.Table.CharSections : DbcTable
---@field FindById fun(self: dbc.Table.CharSections, id: integer): dbc.row.CharSections|nil
---@field GetById fun(self: dbc.Table.CharSections, id: integer): dbc.row.CharSections|nil
---@field GetRow fun(self: dbc.Table.CharSections, row: integer): dbc.row.CharSections
---@field NewRow fun(self: dbc.Table.CharSections, id?: integer): dbc.row.CharSections
---@field Create fun(self: dbc.Table.CharSections, id?: integer): dbc.row.CharSections
---@field CreateNext fun(self: dbc.Table.CharSections, data?: table): dbc.row.CharSections
---@field CloneRow fun(self: dbc.Table.CharSections, source: integer|dbc.row.CharSections, new_id?: integer): dbc.row.CharSections
---@field GetAllRows fun(self: dbc.Table.CharSections): dbc.row.CharSections[]
---@field Query fun(self: dbc.Table.CharSections): dbc.Query<dbc.row.CharSections>
---@field Rows fun(self: dbc.Table.CharSections): fun(): integer, dbc.row.CharSections
