---@meta
-- Generated LuaLS annotations for CharStartOutfit.dbc. Do not edit.

---Row representation of CharStartOutfit.dbc.
---@class dbc.row.CharStartOutfit : RowProxy
---@field ID integer
---@field RaceID integer
---@field ClassID integer
---@field SexID integer
---@field OutfitID integer
---@field ItemID integer[]
---@field DisplayItemID integer[]
---@field InventoryType integer[]

-- Fluent PascalCase Methods for CharStartOutfit
---@field GetID fun(self: dbc.row.CharStartOutfit): integer
---@field SetID fun(self: dbc.row.CharStartOutfit, value: integer): dbc.row.CharStartOutfit
---@field GetRaceID fun(self: dbc.row.CharStartOutfit): integer
---@field SetRaceID fun(self: dbc.row.CharStartOutfit, value: integer): dbc.row.CharStartOutfit
---@field GetClassID fun(self: dbc.row.CharStartOutfit): integer
---@field SetClassID fun(self: dbc.row.CharStartOutfit, value: integer): dbc.row.CharStartOutfit
---@field GetSexID fun(self: dbc.row.CharStartOutfit): integer
---@field SetSexID fun(self: dbc.row.CharStartOutfit, value: integer): dbc.row.CharStartOutfit
---@field GetOutfitID fun(self: dbc.row.CharStartOutfit): integer
---@field SetOutfitID fun(self: dbc.row.CharStartOutfit, value: integer): dbc.row.CharStartOutfit
---@field GetItemID fun(self: dbc.row.CharStartOutfit, index?: integer): integer|integer[]
---@field SetItemID fun(self: dbc.row.CharStartOutfit, value: integer|integer[], index?: integer): dbc.row.CharStartOutfit
---@field GetDisplayItemID fun(self: dbc.row.CharStartOutfit, index?: integer): integer|integer[]
---@field SetDisplayItemID fun(self: dbc.row.CharStartOutfit, value: integer|integer[], index?: integer): dbc.row.CharStartOutfit
---@field GetInventoryType fun(self: dbc.row.CharStartOutfit, index?: integer): integer|integer[]
---@field SetInventoryType fun(self: dbc.row.CharStartOutfit, value: integer|integer[], index?: integer): dbc.row.CharStartOutfit

-- Inferred Cross-Table Relations for CharStartOutfit
---@field GetItem fun(self: dbc.row.CharStartOutfit): dbc.row.Item|nil
---@field SetItem fun(self: dbc.row.CharStartOutfit, target: dbc.row.Item|integer): dbc.row.CharStartOutfit

-- Cascading Creation & Relations Engine for CharStartOutfit
---@field CreateRelated fun(self: dbc.row.CharStartOutfit, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.CharStartOutfit, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.CharStartOutfit, child_table: string, child_field?: string): any[]

---Typed table handle for CharStartOutfit.dbc.
---@class dbc.Table.CharStartOutfit : DbcTable
---@field FindById fun(self: dbc.Table.CharStartOutfit, id: integer): dbc.row.CharStartOutfit|nil
---@field GetById fun(self: dbc.Table.CharStartOutfit, id: integer): dbc.row.CharStartOutfit|nil
---@field GetRow fun(self: dbc.Table.CharStartOutfit, row: integer): dbc.row.CharStartOutfit
---@field NewRow fun(self: dbc.Table.CharStartOutfit, id?: integer): dbc.row.CharStartOutfit
---@field Create fun(self: dbc.Table.CharStartOutfit, id?: integer): dbc.row.CharStartOutfit
---@field CreateNext fun(self: dbc.Table.CharStartOutfit, data?: table): dbc.row.CharStartOutfit
---@field CloneRow fun(self: dbc.Table.CharStartOutfit, source: integer|dbc.row.CharStartOutfit, new_id?: integer): dbc.row.CharStartOutfit
---@field GetAllRows fun(self: dbc.Table.CharStartOutfit): dbc.row.CharStartOutfit[]
---@field Query fun(self: dbc.Table.CharStartOutfit): dbc.Query<dbc.row.CharStartOutfit>
---@field Rows fun(self: dbc.Table.CharStartOutfit): fun(): integer, dbc.row.CharStartOutfit
