---@meta
-- Generated LuaLS annotations for CreatureModelData.dbc. Do not edit.

---Row representation of CreatureModelData.dbc.
---@class dbc.row.CreatureModelData : RowProxy
---@field ID integer
---@field Flags integer
---@field ModelName string
---@field SizeClass integer
---@field ModelScale number
---@field BloodID integer
---@field FootprintTextureID integer
---@field FootprintTextureLength number
---@field FootprintTextureWidth number
---@field FootprintParticleScale number
---@field FoleyMaterialID integer
---@field FootstepShakeSize integer
---@field DeathThudShakeSize integer
---@field SoundID integer
---@field CollisionWidth number
---@field CollisionHeight number
---@field MountHeight number
---@field GeoBoxMinX number
---@field GeoBoxMinY number
---@field GeoBoxMinZ number
---@field GeoBoxMaxX number
---@field GeoBoxMaxY number
---@field GeoBoxMaxZ number
---@field WorldEffectScale number
---@field AttachedEffectScale number
---@field MissileCollisionRadius number
---@field MissileCollisionPush number
---@field MissileCollisionRaise number

-- Fluent PascalCase Methods for CreatureModelData
---@field GetID fun(self: dbc.row.CreatureModelData): integer
---@field SetID fun(self: dbc.row.CreatureModelData, value: integer): dbc.row.CreatureModelData
---@field GetFlags fun(self: dbc.row.CreatureModelData): integer
---@field SetFlags fun(self: dbc.row.CreatureModelData, value: integer): dbc.row.CreatureModelData
---@field HasFlags fun(self: dbc.row.CreatureModelData, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.CreatureModelData, flag: integer): dbc.row.CreatureModelData
---@field RemoveFlags fun(self: dbc.row.CreatureModelData, flag: integer): dbc.row.CreatureModelData
---@field GetModelName fun(self: dbc.row.CreatureModelData): string
---@field SetModelName fun(self: dbc.row.CreatureModelData, value: string): dbc.row.CreatureModelData
---@field GetSizeClass fun(self: dbc.row.CreatureModelData): integer
---@field SetSizeClass fun(self: dbc.row.CreatureModelData, value: integer): dbc.row.CreatureModelData
---@field GetModelScale fun(self: dbc.row.CreatureModelData): number
---@field SetModelScale fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetBloodID fun(self: dbc.row.CreatureModelData): integer
---@field SetBloodID fun(self: dbc.row.CreatureModelData, value: integer): dbc.row.CreatureModelData
---@field GetFootprintTextureID fun(self: dbc.row.CreatureModelData): integer
---@field SetFootprintTextureID fun(self: dbc.row.CreatureModelData, value: integer): dbc.row.CreatureModelData
---@field GetFootprintTextureLength fun(self: dbc.row.CreatureModelData): number
---@field SetFootprintTextureLength fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetFootprintTextureWidth fun(self: dbc.row.CreatureModelData): number
---@field SetFootprintTextureWidth fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetFootprintParticleScale fun(self: dbc.row.CreatureModelData): number
---@field SetFootprintParticleScale fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetFoleyMaterialID fun(self: dbc.row.CreatureModelData): integer
---@field SetFoleyMaterialID fun(self: dbc.row.CreatureModelData, value: integer): dbc.row.CreatureModelData
---@field GetFootstepShakeSize fun(self: dbc.row.CreatureModelData): integer
---@field SetFootstepShakeSize fun(self: dbc.row.CreatureModelData, value: integer): dbc.row.CreatureModelData
---@field GetDeathThudShakeSize fun(self: dbc.row.CreatureModelData): integer
---@field SetDeathThudShakeSize fun(self: dbc.row.CreatureModelData, value: integer): dbc.row.CreatureModelData
---@field GetSoundID fun(self: dbc.row.CreatureModelData): integer
---@field SetSoundID fun(self: dbc.row.CreatureModelData, value: integer): dbc.row.CreatureModelData
---@field GetCollisionWidth fun(self: dbc.row.CreatureModelData): number
---@field SetCollisionWidth fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetCollisionHeight fun(self: dbc.row.CreatureModelData): number
---@field SetCollisionHeight fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetMountHeight fun(self: dbc.row.CreatureModelData): number
---@field SetMountHeight fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetGeoBoxMinX fun(self: dbc.row.CreatureModelData): number
---@field SetGeoBoxMinX fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetGeoBoxMinY fun(self: dbc.row.CreatureModelData): number
---@field SetGeoBoxMinY fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetGeoBoxMinZ fun(self: dbc.row.CreatureModelData): number
---@field SetGeoBoxMinZ fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetGeoBoxMaxX fun(self: dbc.row.CreatureModelData): number
---@field SetGeoBoxMaxX fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetGeoBoxMaxY fun(self: dbc.row.CreatureModelData): number
---@field SetGeoBoxMaxY fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetGeoBoxMaxZ fun(self: dbc.row.CreatureModelData): number
---@field SetGeoBoxMaxZ fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetWorldEffectScale fun(self: dbc.row.CreatureModelData): number
---@field SetWorldEffectScale fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetAttachedEffectScale fun(self: dbc.row.CreatureModelData): number
---@field SetAttachedEffectScale fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetMissileCollisionRadius fun(self: dbc.row.CreatureModelData): number
---@field SetMissileCollisionRadius fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetMissileCollisionPush fun(self: dbc.row.CreatureModelData): number
---@field SetMissileCollisionPush fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData
---@field GetMissileCollisionRaise fun(self: dbc.row.CreatureModelData): number
---@field SetMissileCollisionRaise fun(self: dbc.row.CreatureModelData, value: number): dbc.row.CreatureModelData

-- Inferred Cross-Table Relations for CreatureModelData
---@field GetSoundEntries fun(self: dbc.row.CreatureModelData): dbc.row.SoundEntries|nil
---@field SetSoundEntries fun(self: dbc.row.CreatureModelData, target: dbc.row.SoundEntries|integer): dbc.row.CreatureModelData

-- Cascading Creation & Relations Engine for CreatureModelData
---@field CreateRelated fun(self: dbc.row.CreatureModelData, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.CreatureModelData, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.CreatureModelData, child_table: string, child_field?: string): any[]

---Typed table handle for CreatureModelData.dbc.
---@class dbc.Table.CreatureModelData : DbcTable
---@field FindById fun(self: dbc.Table.CreatureModelData, id: integer): dbc.row.CreatureModelData|nil
---@field GetById fun(self: dbc.Table.CreatureModelData, id: integer): dbc.row.CreatureModelData|nil
---@field GetRow fun(self: dbc.Table.CreatureModelData, row: integer): dbc.row.CreatureModelData
---@field NewRow fun(self: dbc.Table.CreatureModelData, id?: integer): dbc.row.CreatureModelData
---@field Create fun(self: dbc.Table.CreatureModelData, id?: integer): dbc.row.CreatureModelData
---@field CreateNext fun(self: dbc.Table.CreatureModelData, data?: table): dbc.row.CreatureModelData
---@field CloneRow fun(self: dbc.Table.CreatureModelData, source: integer|dbc.row.CreatureModelData, new_id?: integer): dbc.row.CreatureModelData
---@field GetAllRows fun(self: dbc.Table.CreatureModelData): dbc.row.CreatureModelData[]
---@field Query fun(self: dbc.Table.CreatureModelData): dbc.Query<dbc.row.CreatureModelData>
---@field Rows fun(self: dbc.Table.CreatureModelData): fun(): integer, dbc.row.CreatureModelData
