---@meta
-- Generated LuaLS annotations for CreatureDisplayInfoExtra.dbc. Do not edit.

---Row representation of CreatureDisplayInfoExtra.dbc.
---@class dbc.row.CreatureDisplayInfoExtra : RowProxy
---@field ID integer
---@field DisplayRaceID integer
---@field DisplaySexID integer
---@field SkinID integer
---@field FaceID integer
---@field HairStyleID integer
---@field HairColorID integer
---@field FacialHairID integer
---@field NPCItemDisplay integer[]
---@field Flags integer
---@field BakeName string

-- Fluent PascalCase Methods for CreatureDisplayInfoExtra
---@field GetID fun(self: dbc.row.CreatureDisplayInfoExtra): integer
---@field SetID fun(self: dbc.row.CreatureDisplayInfoExtra, value: integer): dbc.row.CreatureDisplayInfoExtra
---@field GetDisplayRaceID fun(self: dbc.row.CreatureDisplayInfoExtra): integer
---@field SetDisplayRaceID fun(self: dbc.row.CreatureDisplayInfoExtra, value: integer): dbc.row.CreatureDisplayInfoExtra
---@field GetDisplaySexID fun(self: dbc.row.CreatureDisplayInfoExtra): integer
---@field SetDisplaySexID fun(self: dbc.row.CreatureDisplayInfoExtra, value: integer): dbc.row.CreatureDisplayInfoExtra
---@field GetSkinID fun(self: dbc.row.CreatureDisplayInfoExtra): integer
---@field SetSkinID fun(self: dbc.row.CreatureDisplayInfoExtra, value: integer): dbc.row.CreatureDisplayInfoExtra
---@field GetFaceID fun(self: dbc.row.CreatureDisplayInfoExtra): integer
---@field SetFaceID fun(self: dbc.row.CreatureDisplayInfoExtra, value: integer): dbc.row.CreatureDisplayInfoExtra
---@field GetHairStyleID fun(self: dbc.row.CreatureDisplayInfoExtra): integer
---@field SetHairStyleID fun(self: dbc.row.CreatureDisplayInfoExtra, value: integer): dbc.row.CreatureDisplayInfoExtra
---@field GetHairColorID fun(self: dbc.row.CreatureDisplayInfoExtra): integer
---@field SetHairColorID fun(self: dbc.row.CreatureDisplayInfoExtra, value: integer): dbc.row.CreatureDisplayInfoExtra
---@field GetFacialHairID fun(self: dbc.row.CreatureDisplayInfoExtra): integer
---@field SetFacialHairID fun(self: dbc.row.CreatureDisplayInfoExtra, value: integer): dbc.row.CreatureDisplayInfoExtra
---@field GetNPCItemDisplay fun(self: dbc.row.CreatureDisplayInfoExtra, index?: integer): integer|integer[]
---@field SetNPCItemDisplay fun(self: dbc.row.CreatureDisplayInfoExtra, value: integer|integer[], index?: integer): dbc.row.CreatureDisplayInfoExtra
---@field GetFlags fun(self: dbc.row.CreatureDisplayInfoExtra): integer
---@field SetFlags fun(self: dbc.row.CreatureDisplayInfoExtra, value: integer): dbc.row.CreatureDisplayInfoExtra
---@field HasFlags fun(self: dbc.row.CreatureDisplayInfoExtra, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.CreatureDisplayInfoExtra, flag: integer): dbc.row.CreatureDisplayInfoExtra
---@field RemoveFlags fun(self: dbc.row.CreatureDisplayInfoExtra, flag: integer): dbc.row.CreatureDisplayInfoExtra
---@field GetBakeName fun(self: dbc.row.CreatureDisplayInfoExtra): string
---@field SetBakeName fun(self: dbc.row.CreatureDisplayInfoExtra, value: string): dbc.row.CreatureDisplayInfoExtra

-- Inferred Cross-Table Relations for CreatureDisplayInfoExtra

-- Cascading Creation & Relations Engine for CreatureDisplayInfoExtra
---@field CreateRelated fun(self: dbc.row.CreatureDisplayInfoExtra, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.CreatureDisplayInfoExtra, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.CreatureDisplayInfoExtra, child_table: string, child_field?: string): any[]

---Typed table handle for CreatureDisplayInfoExtra.dbc.
---@class dbc.Table.CreatureDisplayInfoExtra : DbcTable
---@field FindById fun(self: dbc.Table.CreatureDisplayInfoExtra, id: integer): dbc.row.CreatureDisplayInfoExtra|nil
---@field GetById fun(self: dbc.Table.CreatureDisplayInfoExtra, id: integer): dbc.row.CreatureDisplayInfoExtra|nil
---@field GetRow fun(self: dbc.Table.CreatureDisplayInfoExtra, row: integer): dbc.row.CreatureDisplayInfoExtra
---@field NewRow fun(self: dbc.Table.CreatureDisplayInfoExtra, id?: integer): dbc.row.CreatureDisplayInfoExtra
---@field Create fun(self: dbc.Table.CreatureDisplayInfoExtra, id?: integer): dbc.row.CreatureDisplayInfoExtra
---@field CreateNext fun(self: dbc.Table.CreatureDisplayInfoExtra, data?: table): dbc.row.CreatureDisplayInfoExtra
---@field CloneRow fun(self: dbc.Table.CreatureDisplayInfoExtra, source: integer|dbc.row.CreatureDisplayInfoExtra, new_id?: integer): dbc.row.CreatureDisplayInfoExtra
---@field GetAllRows fun(self: dbc.Table.CreatureDisplayInfoExtra): dbc.row.CreatureDisplayInfoExtra[]
---@field Query fun(self: dbc.Table.CreatureDisplayInfoExtra): dbc.Query<dbc.row.CreatureDisplayInfoExtra>
---@field Rows fun(self: dbc.Table.CreatureDisplayInfoExtra): fun(): integer, dbc.row.CreatureDisplayInfoExtra
