---@meta
-- Generated LuaLS annotations for CreatureFamily.dbc. Do not edit.

---Row representation of CreatureFamily.dbc.
---@class dbc.row.CreatureFamily : RowProxy
---@field ID integer
---@field MinScale number
---@field MinScaleLevel integer
---@field MaxScale number
---@field MaxScaleLevel integer
---@field SkillLine integer[]
---@field PetFoodMask integer
---@field PetTalentType integer
---@field CategoryEnumID integer
---@field Name string
---@field IconFile string

-- Fluent PascalCase Methods for CreatureFamily
---@field GetID fun(self: dbc.row.CreatureFamily): integer
---@field SetID fun(self: dbc.row.CreatureFamily, value: integer): dbc.row.CreatureFamily
---@field GetMinScale fun(self: dbc.row.CreatureFamily): number
---@field SetMinScale fun(self: dbc.row.CreatureFamily, value: number): dbc.row.CreatureFamily
---@field GetMinScaleLevel fun(self: dbc.row.CreatureFamily): integer
---@field SetMinScaleLevel fun(self: dbc.row.CreatureFamily, value: integer): dbc.row.CreatureFamily
---@field GetMaxScale fun(self: dbc.row.CreatureFamily): number
---@field SetMaxScale fun(self: dbc.row.CreatureFamily, value: number): dbc.row.CreatureFamily
---@field GetMaxScaleLevel fun(self: dbc.row.CreatureFamily): integer
---@field SetMaxScaleLevel fun(self: dbc.row.CreatureFamily, value: integer): dbc.row.CreatureFamily
---@field GetSkillLine fun(self: dbc.row.CreatureFamily, index?: integer): integer|integer[]
---@field SetSkillLine fun(self: dbc.row.CreatureFamily, value: integer|integer[], index?: integer): dbc.row.CreatureFamily
---@field GetPetFoodMask fun(self: dbc.row.CreatureFamily): integer
---@field SetPetFoodMask fun(self: dbc.row.CreatureFamily, value: integer): dbc.row.CreatureFamily
---@field HasPetFoodMask fun(self: dbc.row.CreatureFamily, flag: integer): boolean
---@field AddPetFoodMask fun(self: dbc.row.CreatureFamily, flag: integer): dbc.row.CreatureFamily
---@field RemovePetFoodMask fun(self: dbc.row.CreatureFamily, flag: integer): dbc.row.CreatureFamily
---@field GetPetTalentType fun(self: dbc.row.CreatureFamily): integer
---@field SetPetTalentType fun(self: dbc.row.CreatureFamily, value: integer): dbc.row.CreatureFamily
---@field GetCategoryEnumID fun(self: dbc.row.CreatureFamily): integer
---@field SetCategoryEnumID fun(self: dbc.row.CreatureFamily, value: integer): dbc.row.CreatureFamily
---@field GetName fun(self: dbc.row.CreatureFamily, locale?: string|integer): string
---@field SetName fun(self: dbc.row.CreatureFamily, value: string, locale?: string|integer): dbc.row.CreatureFamily
---@field GetIconFile fun(self: dbc.row.CreatureFamily): string
---@field SetIconFile fun(self: dbc.row.CreatureFamily, value: string): dbc.row.CreatureFamily

-- Inferred Cross-Table Relations for CreatureFamily
---@field GetSkillLine fun(self: dbc.row.CreatureFamily): dbc.row.SkillLine|nil
---@field SetSkillLine fun(self: dbc.row.CreatureFamily, target: dbc.row.SkillLine|integer): dbc.row.CreatureFamily

-- Cascading Creation & Relations Engine for CreatureFamily
---@field CreateRelated fun(self: dbc.row.CreatureFamily, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.CreatureFamily, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.CreatureFamily, child_table: string, child_field?: string): any[]

---Typed table handle for CreatureFamily.dbc.
---@class dbc.Table.CreatureFamily : DbcTable
---@field FindById fun(self: dbc.Table.CreatureFamily, id: integer): dbc.row.CreatureFamily|nil
---@field GetById fun(self: dbc.Table.CreatureFamily, id: integer): dbc.row.CreatureFamily|nil
---@field GetRow fun(self: dbc.Table.CreatureFamily, row: integer): dbc.row.CreatureFamily
---@field NewRow fun(self: dbc.Table.CreatureFamily, id?: integer): dbc.row.CreatureFamily
---@field Create fun(self: dbc.Table.CreatureFamily, id?: integer): dbc.row.CreatureFamily
---@field CreateNext fun(self: dbc.Table.CreatureFamily, data?: table): dbc.row.CreatureFamily
---@field CloneRow fun(self: dbc.Table.CreatureFamily, source: integer|dbc.row.CreatureFamily, new_id?: integer): dbc.row.CreatureFamily
---@field GetAllRows fun(self: dbc.Table.CreatureFamily): dbc.row.CreatureFamily[]
---@field Query fun(self: dbc.Table.CreatureFamily): dbc.Query<dbc.row.CreatureFamily>
---@field Rows fun(self: dbc.Table.CreatureFamily): fun(): integer, dbc.row.CreatureFamily
