---@meta
-- Generated LuaLS annotations for CreatureSoundData.dbc. Do not edit.

---Row representation of CreatureSoundData.dbc.
---@class dbc.row.CreatureSoundData : RowProxy
---@field ID integer
---@field SoundExertionID integer
---@field SoundExertionCriticalID integer
---@field SoundInjuryID integer
---@field SoundInjuryCriticalID integer
---@field SoundInjuryCrushingBlowID integer
---@field SoundDeathID integer
---@field SoundStunID integer
---@field SoundStandID integer
---@field SoundFootstepID integer
---@field SoundAggroID integer
---@field SoundWingFlapID integer
---@field SoundWingGlideID integer
---@field SoundAlertID integer
---@field SoundFidget integer[]
---@field CustomAttack integer[]
---@field NPCSoundID integer
---@field LoopSoundID integer
---@field CreatureImpactType integer
---@field SoundJumpStartID integer
---@field SoundJumpEndID integer
---@field SoundPetAttackID integer
---@field SoundPetOrderID integer
---@field SoundPetDismissID integer
---@field FidgetDelaySecondsMin number
---@field FidgetDelaySecondsMax number
---@field BirthSoundID integer
---@field SpellCastDirectedSoundID integer
---@field SubmergeSoundID integer
---@field SubmergedSoundID integer
---@field CreatureSoundDataIDPet integer

-- Fluent PascalCase Methods for CreatureSoundData
---@field GetID fun(self: dbc.row.CreatureSoundData): integer
---@field SetID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundExertionID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundExertionID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundExertionCriticalID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundExertionCriticalID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundInjuryID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundInjuryID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundInjuryCriticalID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundInjuryCriticalID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundInjuryCrushingBlowID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundInjuryCrushingBlowID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundDeathID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundDeathID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundStunID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundStunID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundStandID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundStandID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundFootstepID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundFootstepID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundAggroID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundAggroID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundWingFlapID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundWingFlapID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundWingGlideID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundWingGlideID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundAlertID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundAlertID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundFidget fun(self: dbc.row.CreatureSoundData, index?: integer): integer|integer[]
---@field SetSoundFidget fun(self: dbc.row.CreatureSoundData, value: integer|integer[], index?: integer): dbc.row.CreatureSoundData
---@field GetCustomAttack fun(self: dbc.row.CreatureSoundData, index?: integer): integer|integer[]
---@field SetCustomAttack fun(self: dbc.row.CreatureSoundData, value: integer|integer[], index?: integer): dbc.row.CreatureSoundData
---@field GetNPCSoundID fun(self: dbc.row.CreatureSoundData): integer
---@field SetNPCSoundID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetLoopSoundID fun(self: dbc.row.CreatureSoundData): integer
---@field SetLoopSoundID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetCreatureImpactType fun(self: dbc.row.CreatureSoundData): integer
---@field SetCreatureImpactType fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundJumpStartID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundJumpStartID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundJumpEndID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundJumpEndID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundPetAttackID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundPetAttackID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundPetOrderID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundPetOrderID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSoundPetDismissID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSoundPetDismissID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetFidgetDelaySecondsMin fun(self: dbc.row.CreatureSoundData): number
---@field SetFidgetDelaySecondsMin fun(self: dbc.row.CreatureSoundData, value: number): dbc.row.CreatureSoundData
---@field GetFidgetDelaySecondsMax fun(self: dbc.row.CreatureSoundData): number
---@field SetFidgetDelaySecondsMax fun(self: dbc.row.CreatureSoundData, value: number): dbc.row.CreatureSoundData
---@field GetBirthSoundID fun(self: dbc.row.CreatureSoundData): integer
---@field SetBirthSoundID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSpellCastDirectedSoundID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSpellCastDirectedSoundID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSubmergeSoundID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSubmergeSoundID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetSubmergedSoundID fun(self: dbc.row.CreatureSoundData): integer
---@field SetSubmergedSoundID fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData
---@field GetCreatureSoundDataIDPet fun(self: dbc.row.CreatureSoundData): integer
---@field SetCreatureSoundDataIDPet fun(self: dbc.row.CreatureSoundData, value: integer): dbc.row.CreatureSoundData

-- Inferred Cross-Table Relations for CreatureSoundData

-- Cascading Creation & Relations Engine for CreatureSoundData
---@field CreateRelated fun(self: dbc.row.CreatureSoundData, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.CreatureSoundData, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.CreatureSoundData, child_table: string, child_field?: string): any[]

---Typed table handle for CreatureSoundData.dbc.
---@class dbc.Table.CreatureSoundData : DbcTable
---@field FindById fun(self: dbc.Table.CreatureSoundData, id: integer): dbc.row.CreatureSoundData|nil
---@field GetById fun(self: dbc.Table.CreatureSoundData, id: integer): dbc.row.CreatureSoundData|nil
---@field GetRow fun(self: dbc.Table.CreatureSoundData, row: integer): dbc.row.CreatureSoundData
---@field NewRow fun(self: dbc.Table.CreatureSoundData, id?: integer): dbc.row.CreatureSoundData
---@field Create fun(self: dbc.Table.CreatureSoundData, id?: integer): dbc.row.CreatureSoundData
---@field CreateNext fun(self: dbc.Table.CreatureSoundData, data?: table): dbc.row.CreatureSoundData
---@field CloneRow fun(self: dbc.Table.CreatureSoundData, source: integer|dbc.row.CreatureSoundData, new_id?: integer): dbc.row.CreatureSoundData
---@field GetAllRows fun(self: dbc.Table.CreatureSoundData): dbc.row.CreatureSoundData[]
---@field Query fun(self: dbc.Table.CreatureSoundData): dbc.Query<dbc.row.CreatureSoundData>
---@field Rows fun(self: dbc.Table.CreatureSoundData): fun(): integer, dbc.row.CreatureSoundData
