---@meta
-- Generated LuaLS annotations for CreatureDisplayInfo.dbc. Do not edit.

---Row representation of CreatureDisplayInfo.dbc.
---@class dbc.row.CreatureDisplayInfo : RowProxy
---@field ID integer
---@field ModelID integer
---@field SoundID integer
---@field ExtendedDisplayInfoID integer
---@field CreatureModelScale number
---@field CreatureModelAlpha integer
---@field TextureVariation string[]
---@field PortraitTextureName string
---@field BloodLevel integer
---@field BloodID integer
---@field NPCSoundID integer
---@field ParticleColorID integer
---@field CreatureGeosetData integer
---@field ObjectEffectPackageID integer

-- Fluent PascalCase Methods for CreatureDisplayInfo
---@field GetID fun(self: dbc.row.CreatureDisplayInfo): integer
---@field SetID fun(self: dbc.row.CreatureDisplayInfo, value: integer): dbc.row.CreatureDisplayInfo
---@field GetModelID fun(self: dbc.row.CreatureDisplayInfo): integer
---@field SetModelID fun(self: dbc.row.CreatureDisplayInfo, value: integer): dbc.row.CreatureDisplayInfo
---@field GetSoundID fun(self: dbc.row.CreatureDisplayInfo): integer
---@field SetSoundID fun(self: dbc.row.CreatureDisplayInfo, value: integer): dbc.row.CreatureDisplayInfo
---@field GetExtendedDisplayInfoID fun(self: dbc.row.CreatureDisplayInfo): integer
---@field SetExtendedDisplayInfoID fun(self: dbc.row.CreatureDisplayInfo, value: integer): dbc.row.CreatureDisplayInfo
---@field GetCreatureModelScale fun(self: dbc.row.CreatureDisplayInfo): number
---@field SetCreatureModelScale fun(self: dbc.row.CreatureDisplayInfo, value: number): dbc.row.CreatureDisplayInfo
---@field GetCreatureModelAlpha fun(self: dbc.row.CreatureDisplayInfo): integer
---@field SetCreatureModelAlpha fun(self: dbc.row.CreatureDisplayInfo, value: integer): dbc.row.CreatureDisplayInfo
---@field GetTextureVariation fun(self: dbc.row.CreatureDisplayInfo, index?: integer): string|string[]
---@field SetTextureVariation fun(self: dbc.row.CreatureDisplayInfo, value: string|string[], index?: integer): dbc.row.CreatureDisplayInfo
---@field GetPortraitTextureName fun(self: dbc.row.CreatureDisplayInfo): string
---@field SetPortraitTextureName fun(self: dbc.row.CreatureDisplayInfo, value: string): dbc.row.CreatureDisplayInfo
---@field GetBloodLevel fun(self: dbc.row.CreatureDisplayInfo): integer
---@field SetBloodLevel fun(self: dbc.row.CreatureDisplayInfo, value: integer): dbc.row.CreatureDisplayInfo
---@field GetBloodID fun(self: dbc.row.CreatureDisplayInfo): integer
---@field SetBloodID fun(self: dbc.row.CreatureDisplayInfo, value: integer): dbc.row.CreatureDisplayInfo
---@field GetNPCSoundID fun(self: dbc.row.CreatureDisplayInfo): integer
---@field SetNPCSoundID fun(self: dbc.row.CreatureDisplayInfo, value: integer): dbc.row.CreatureDisplayInfo
---@field GetParticleColorID fun(self: dbc.row.CreatureDisplayInfo): integer
---@field SetParticleColorID fun(self: dbc.row.CreatureDisplayInfo, value: integer): dbc.row.CreatureDisplayInfo
---@field GetCreatureGeosetData fun(self: dbc.row.CreatureDisplayInfo): integer
---@field SetCreatureGeosetData fun(self: dbc.row.CreatureDisplayInfo, value: integer): dbc.row.CreatureDisplayInfo
---@field GetObjectEffectPackageID fun(self: dbc.row.CreatureDisplayInfo): integer
---@field SetObjectEffectPackageID fun(self: dbc.row.CreatureDisplayInfo, value: integer): dbc.row.CreatureDisplayInfo

-- Inferred Cross-Table Relations for CreatureDisplayInfo
---@field GetCreatureModelData fun(self: dbc.row.CreatureDisplayInfo): dbc.row.CreatureModelData|nil
---@field SetCreatureModelData fun(self: dbc.row.CreatureDisplayInfo, target: dbc.row.CreatureModelData|integer): dbc.row.CreatureDisplayInfo
---@field GetSoundEntries fun(self: dbc.row.CreatureDisplayInfo): dbc.row.SoundEntries|nil
---@field SetSoundEntries fun(self: dbc.row.CreatureDisplayInfo, target: dbc.row.SoundEntries|integer): dbc.row.CreatureDisplayInfo
---@field GetParticleColor fun(self: dbc.row.CreatureDisplayInfo): dbc.row.ParticleColor|nil
---@field SetParticleColor fun(self: dbc.row.CreatureDisplayInfo, target: dbc.row.ParticleColor|integer): dbc.row.CreatureDisplayInfo
---@field GetObjectEffectPackage fun(self: dbc.row.CreatureDisplayInfo): dbc.row.ObjectEffectPackage|nil
---@field SetObjectEffectPackage fun(self: dbc.row.CreatureDisplayInfo, target: dbc.row.ObjectEffectPackage|integer): dbc.row.CreatureDisplayInfo

-- Cascading Creation & Relations Engine for CreatureDisplayInfo
---@field CreateRelated fun(self: dbc.row.CreatureDisplayInfo, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.CreatureDisplayInfo, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.CreatureDisplayInfo, child_table: string, child_field?: string): any[]

---Typed table handle for CreatureDisplayInfo.dbc.
---@class dbc.Table.CreatureDisplayInfo : DbcTable
---@field FindById fun(self: dbc.Table.CreatureDisplayInfo, id: integer): dbc.row.CreatureDisplayInfo|nil
---@field GetById fun(self: dbc.Table.CreatureDisplayInfo, id: integer): dbc.row.CreatureDisplayInfo|nil
---@field GetRow fun(self: dbc.Table.CreatureDisplayInfo, row: integer): dbc.row.CreatureDisplayInfo
---@field NewRow fun(self: dbc.Table.CreatureDisplayInfo, id?: integer): dbc.row.CreatureDisplayInfo
---@field Create fun(self: dbc.Table.CreatureDisplayInfo, id?: integer): dbc.row.CreatureDisplayInfo
---@field CreateNext fun(self: dbc.Table.CreatureDisplayInfo, data?: table): dbc.row.CreatureDisplayInfo
---@field CloneRow fun(self: dbc.Table.CreatureDisplayInfo, source: integer|dbc.row.CreatureDisplayInfo, new_id?: integer): dbc.row.CreatureDisplayInfo
---@field GetAllRows fun(self: dbc.Table.CreatureDisplayInfo): dbc.row.CreatureDisplayInfo[]
---@field Query fun(self: dbc.Table.CreatureDisplayInfo): dbc.Query<dbc.row.CreatureDisplayInfo>
---@field Rows fun(self: dbc.Table.CreatureDisplayInfo): fun(): integer, dbc.row.CreatureDisplayInfo
