---@meta
-- Generated LuaLS annotations for DanceMoves.dbc. Do not edit.

---Row representation of DanceMoves.dbc.
---@class dbc.row.DanceMoves : RowProxy
---@field ID integer
---@field Type integer
---@field Param integer
---@field Fallback integer
---@field Racemask integer
---@field Internal_Name string
---@field Name string
---@field LockID integer

-- Fluent PascalCase Methods for DanceMoves
---@field GetID fun(self: dbc.row.DanceMoves): integer
---@field SetID fun(self: dbc.row.DanceMoves, value: integer): dbc.row.DanceMoves
---@field GetType fun(self: dbc.row.DanceMoves): integer
---@field SetType fun(self: dbc.row.DanceMoves, value: integer): dbc.row.DanceMoves
---@field GetParam fun(self: dbc.row.DanceMoves): integer
---@field SetParam fun(self: dbc.row.DanceMoves, value: integer): dbc.row.DanceMoves
---@field GetFallback fun(self: dbc.row.DanceMoves): integer
---@field SetFallback fun(self: dbc.row.DanceMoves, value: integer): dbc.row.DanceMoves
---@field GetRacemask fun(self: dbc.row.DanceMoves): integer
---@field SetRacemask fun(self: dbc.row.DanceMoves, value: integer): dbc.row.DanceMoves
---@field GetInternal_Name fun(self: dbc.row.DanceMoves): string
---@field SetInternal_Name fun(self: dbc.row.DanceMoves, value: string): dbc.row.DanceMoves
---@field GetName fun(self: dbc.row.DanceMoves, locale?: string|integer): string
---@field SetName fun(self: dbc.row.DanceMoves, value: string, locale?: string|integer): dbc.row.DanceMoves
---@field GetLockID fun(self: dbc.row.DanceMoves): integer
---@field SetLockID fun(self: dbc.row.DanceMoves, value: integer): dbc.row.DanceMoves

-- Inferred Cross-Table Relations for DanceMoves
---@field GetLock fun(self: dbc.row.DanceMoves): dbc.row.Lock|nil
---@field SetLock fun(self: dbc.row.DanceMoves, target: dbc.row.Lock|integer): dbc.row.DanceMoves

-- Cascading Creation & Relations Engine for DanceMoves
---@field CreateRelated fun(self: dbc.row.DanceMoves, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.DanceMoves, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.DanceMoves, child_table: string, child_field?: string): any[]

---Typed table handle for DanceMoves.dbc.
---@class dbc.Table.DanceMoves : DbcTable
---@field FindById fun(self: dbc.Table.DanceMoves, id: integer): dbc.row.DanceMoves|nil
---@field GetById fun(self: dbc.Table.DanceMoves, id: integer): dbc.row.DanceMoves|nil
---@field GetRow fun(self: dbc.Table.DanceMoves, row: integer): dbc.row.DanceMoves
---@field NewRow fun(self: dbc.Table.DanceMoves, id?: integer): dbc.row.DanceMoves
---@field Create fun(self: dbc.Table.DanceMoves, id?: integer): dbc.row.DanceMoves
---@field CreateNext fun(self: dbc.Table.DanceMoves, data?: table): dbc.row.DanceMoves
---@field CloneRow fun(self: dbc.Table.DanceMoves, source: integer|dbc.row.DanceMoves, new_id?: integer): dbc.row.DanceMoves
---@field GetAllRows fun(self: dbc.Table.DanceMoves): dbc.row.DanceMoves[]
---@field Query fun(self: dbc.Table.DanceMoves): dbc.Query<dbc.row.DanceMoves>
---@field Rows fun(self: dbc.Table.DanceMoves): fun(): integer, dbc.row.DanceMoves
