---@meta
-- Generated LuaLS annotations for DungeonEncounter.dbc. Do not edit.

---Row representation of DungeonEncounter.dbc.
---@class dbc.row.DungeonEncounter : RowProxy
---@field ID integer
---@field MapID integer
---@field Difficulty integer
---@field OrderIndex integer
---@field Bit integer
---@field Name string
---@field SpellIconID integer

-- Fluent PascalCase Methods for DungeonEncounter
---@field GetID fun(self: dbc.row.DungeonEncounter): integer
---@field SetID fun(self: dbc.row.DungeonEncounter, value: integer): dbc.row.DungeonEncounter
---@field GetMapID fun(self: dbc.row.DungeonEncounter): integer
---@field SetMapID fun(self: dbc.row.DungeonEncounter, value: integer): dbc.row.DungeonEncounter
---@field GetDifficulty fun(self: dbc.row.DungeonEncounter): integer
---@field SetDifficulty fun(self: dbc.row.DungeonEncounter, value: integer): dbc.row.DungeonEncounter
---@field GetOrderIndex fun(self: dbc.row.DungeonEncounter): integer
---@field SetOrderIndex fun(self: dbc.row.DungeonEncounter, value: integer): dbc.row.DungeonEncounter
---@field GetBit fun(self: dbc.row.DungeonEncounter): integer
---@field SetBit fun(self: dbc.row.DungeonEncounter, value: integer): dbc.row.DungeonEncounter
---@field GetName fun(self: dbc.row.DungeonEncounter, locale?: string|integer): string
---@field SetName fun(self: dbc.row.DungeonEncounter, value: string, locale?: string|integer): dbc.row.DungeonEncounter
---@field GetSpellIconID fun(self: dbc.row.DungeonEncounter): integer
---@field SetSpellIconID fun(self: dbc.row.DungeonEncounter, value: integer): dbc.row.DungeonEncounter

-- Inferred Cross-Table Relations for DungeonEncounter
---@field GetMap fun(self: dbc.row.DungeonEncounter): dbc.row.Map|nil
---@field SetMap fun(self: dbc.row.DungeonEncounter, target: dbc.row.Map|integer): dbc.row.DungeonEncounter
---@field GetSpellIcon fun(self: dbc.row.DungeonEncounter): dbc.row.SpellIcon|nil
---@field SetSpellIcon fun(self: dbc.row.DungeonEncounter, target: dbc.row.SpellIcon|integer): dbc.row.DungeonEncounter

-- Cascading Creation & Relations Engine for DungeonEncounter
---@field CreateRelated fun(self: dbc.row.DungeonEncounter, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.DungeonEncounter, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.DungeonEncounter, child_table: string, child_field?: string): any[]

---Typed table handle for DungeonEncounter.dbc.
---@class dbc.Table.DungeonEncounter : DbcTable
---@field FindById fun(self: dbc.Table.DungeonEncounter, id: integer): dbc.row.DungeonEncounter|nil
---@field GetById fun(self: dbc.Table.DungeonEncounter, id: integer): dbc.row.DungeonEncounter|nil
---@field GetRow fun(self: dbc.Table.DungeonEncounter, row: integer): dbc.row.DungeonEncounter
---@field NewRow fun(self: dbc.Table.DungeonEncounter, id?: integer): dbc.row.DungeonEncounter
---@field Create fun(self: dbc.Table.DungeonEncounter, id?: integer): dbc.row.DungeonEncounter
---@field CreateNext fun(self: dbc.Table.DungeonEncounter, data?: table): dbc.row.DungeonEncounter
---@field CloneRow fun(self: dbc.Table.DungeonEncounter, source: integer|dbc.row.DungeonEncounter, new_id?: integer): dbc.row.DungeonEncounter
---@field GetAllRows fun(self: dbc.Table.DungeonEncounter): dbc.row.DungeonEncounter[]
---@field Query fun(self: dbc.Table.DungeonEncounter): dbc.Query<dbc.row.DungeonEncounter>
---@field Rows fun(self: dbc.Table.DungeonEncounter): fun(): integer, dbc.row.DungeonEncounter
