---@meta
-- Generated LuaLS annotations for DungeonMap.dbc. Do not edit.

---Row representation of DungeonMap.dbc.
---@class dbc.row.DungeonMap : RowProxy
---@field ID integer
---@field MapID integer
---@field FloorIndex integer
---@field MinX number
---@field MaxX number
---@field MinY number
---@field MaxY number
---@field ParentWorldMapID integer

-- Fluent PascalCase Methods for DungeonMap
---@field GetID fun(self: dbc.row.DungeonMap): integer
---@field SetID fun(self: dbc.row.DungeonMap, value: integer): dbc.row.DungeonMap
---@field GetMapID fun(self: dbc.row.DungeonMap): integer
---@field SetMapID fun(self: dbc.row.DungeonMap, value: integer): dbc.row.DungeonMap
---@field GetFloorIndex fun(self: dbc.row.DungeonMap): integer
---@field SetFloorIndex fun(self: dbc.row.DungeonMap, value: integer): dbc.row.DungeonMap
---@field GetMinX fun(self: dbc.row.DungeonMap): number
---@field SetMinX fun(self: dbc.row.DungeonMap, value: number): dbc.row.DungeonMap
---@field GetMaxX fun(self: dbc.row.DungeonMap): number
---@field SetMaxX fun(self: dbc.row.DungeonMap, value: number): dbc.row.DungeonMap
---@field GetMinY fun(self: dbc.row.DungeonMap): number
---@field SetMinY fun(self: dbc.row.DungeonMap, value: number): dbc.row.DungeonMap
---@field GetMaxY fun(self: dbc.row.DungeonMap): number
---@field SetMaxY fun(self: dbc.row.DungeonMap, value: number): dbc.row.DungeonMap
---@field GetParentWorldMapID fun(self: dbc.row.DungeonMap): integer
---@field SetParentWorldMapID fun(self: dbc.row.DungeonMap, value: integer): dbc.row.DungeonMap

-- Inferred Cross-Table Relations for DungeonMap
---@field GetMap fun(self: dbc.row.DungeonMap): dbc.row.Map|nil
---@field SetMap fun(self: dbc.row.DungeonMap, target: dbc.row.Map|integer): dbc.row.DungeonMap

-- Cascading Creation & Relations Engine for DungeonMap
---@field CreateRelated fun(self: dbc.row.DungeonMap, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.DungeonMap, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.DungeonMap, child_table: string, child_field?: string): any[]

---Typed table handle for DungeonMap.dbc.
---@class dbc.Table.DungeonMap : DbcTable
---@field FindById fun(self: dbc.Table.DungeonMap, id: integer): dbc.row.DungeonMap|nil
---@field GetById fun(self: dbc.Table.DungeonMap, id: integer): dbc.row.DungeonMap|nil
---@field GetRow fun(self: dbc.Table.DungeonMap, row: integer): dbc.row.DungeonMap
---@field NewRow fun(self: dbc.Table.DungeonMap, id?: integer): dbc.row.DungeonMap
---@field Create fun(self: dbc.Table.DungeonMap, id?: integer): dbc.row.DungeonMap
---@field CreateNext fun(self: dbc.Table.DungeonMap, data?: table): dbc.row.DungeonMap
---@field CloneRow fun(self: dbc.Table.DungeonMap, source: integer|dbc.row.DungeonMap, new_id?: integer): dbc.row.DungeonMap
---@field GetAllRows fun(self: dbc.Table.DungeonMap): dbc.row.DungeonMap[]
---@field Query fun(self: dbc.Table.DungeonMap): dbc.Query<dbc.row.DungeonMap>
---@field Rows fun(self: dbc.Table.DungeonMap): fun(): integer, dbc.row.DungeonMap
