---@meta
-- Generated LuaLS annotations for GameObjectDisplayInfo.dbc. Do not edit.

---Row representation of GameObjectDisplayInfo.dbc.
---@class dbc.row.GameObjectDisplayInfo : RowProxy
---@field ID integer
---@field ModelName string
---@field Sound integer[]
---@field GeoBoxMinX number
---@field GeoBoxMinY number
---@field GeoBoxMinZ number
---@field GeoBoxMaxX number
---@field GeoBoxMaxY number
---@field GeoBoxMaxZ number
---@field ObjectEffectPackageID integer

-- Fluent PascalCase Methods for GameObjectDisplayInfo
---@field GetID fun(self: dbc.row.GameObjectDisplayInfo): integer
---@field SetID fun(self: dbc.row.GameObjectDisplayInfo, value: integer): dbc.row.GameObjectDisplayInfo
---@field GetModelName fun(self: dbc.row.GameObjectDisplayInfo): string
---@field SetModelName fun(self: dbc.row.GameObjectDisplayInfo, value: string): dbc.row.GameObjectDisplayInfo
---@field GetSound fun(self: dbc.row.GameObjectDisplayInfo, index?: integer): integer|integer[]
---@field SetSound fun(self: dbc.row.GameObjectDisplayInfo, value: integer|integer[], index?: integer): dbc.row.GameObjectDisplayInfo
---@field GetGeoBoxMinX fun(self: dbc.row.GameObjectDisplayInfo): number
---@field SetGeoBoxMinX fun(self: dbc.row.GameObjectDisplayInfo, value: number): dbc.row.GameObjectDisplayInfo
---@field GetGeoBoxMinY fun(self: dbc.row.GameObjectDisplayInfo): number
---@field SetGeoBoxMinY fun(self: dbc.row.GameObjectDisplayInfo, value: number): dbc.row.GameObjectDisplayInfo
---@field GetGeoBoxMinZ fun(self: dbc.row.GameObjectDisplayInfo): number
---@field SetGeoBoxMinZ fun(self: dbc.row.GameObjectDisplayInfo, value: number): dbc.row.GameObjectDisplayInfo
---@field GetGeoBoxMaxX fun(self: dbc.row.GameObjectDisplayInfo): number
---@field SetGeoBoxMaxX fun(self: dbc.row.GameObjectDisplayInfo, value: number): dbc.row.GameObjectDisplayInfo
---@field GetGeoBoxMaxY fun(self: dbc.row.GameObjectDisplayInfo): number
---@field SetGeoBoxMaxY fun(self: dbc.row.GameObjectDisplayInfo, value: number): dbc.row.GameObjectDisplayInfo
---@field GetGeoBoxMaxZ fun(self: dbc.row.GameObjectDisplayInfo): number
---@field SetGeoBoxMaxZ fun(self: dbc.row.GameObjectDisplayInfo, value: number): dbc.row.GameObjectDisplayInfo
---@field GetObjectEffectPackageID fun(self: dbc.row.GameObjectDisplayInfo): integer
---@field SetObjectEffectPackageID fun(self: dbc.row.GameObjectDisplayInfo, value: integer): dbc.row.GameObjectDisplayInfo

-- Inferred Cross-Table Relations for GameObjectDisplayInfo
---@field GetObjectEffectPackage fun(self: dbc.row.GameObjectDisplayInfo): dbc.row.ObjectEffectPackage|nil
---@field SetObjectEffectPackage fun(self: dbc.row.GameObjectDisplayInfo, target: dbc.row.ObjectEffectPackage|integer): dbc.row.GameObjectDisplayInfo

-- Cascading Creation & Relations Engine for GameObjectDisplayInfo
---@field CreateRelated fun(self: dbc.row.GameObjectDisplayInfo, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.GameObjectDisplayInfo, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.GameObjectDisplayInfo, child_table: string, child_field?: string): any[]

---Typed table handle for GameObjectDisplayInfo.dbc.
---@class dbc.Table.GameObjectDisplayInfo : DbcTable
---@field FindById fun(self: dbc.Table.GameObjectDisplayInfo, id: integer): dbc.row.GameObjectDisplayInfo|nil
---@field GetById fun(self: dbc.Table.GameObjectDisplayInfo, id: integer): dbc.row.GameObjectDisplayInfo|nil
---@field GetRow fun(self: dbc.Table.GameObjectDisplayInfo, row: integer): dbc.row.GameObjectDisplayInfo
---@field NewRow fun(self: dbc.Table.GameObjectDisplayInfo, id?: integer): dbc.row.GameObjectDisplayInfo
---@field Create fun(self: dbc.Table.GameObjectDisplayInfo, id?: integer): dbc.row.GameObjectDisplayInfo
---@field CreateNext fun(self: dbc.Table.GameObjectDisplayInfo, data?: table): dbc.row.GameObjectDisplayInfo
---@field CloneRow fun(self: dbc.Table.GameObjectDisplayInfo, source: integer|dbc.row.GameObjectDisplayInfo, new_id?: integer): dbc.row.GameObjectDisplayInfo
---@field GetAllRows fun(self: dbc.Table.GameObjectDisplayInfo): dbc.row.GameObjectDisplayInfo[]
---@field Query fun(self: dbc.Table.GameObjectDisplayInfo): dbc.Query<dbc.row.GameObjectDisplayInfo>
---@field Rows fun(self: dbc.Table.GameObjectDisplayInfo): fun(): integer, dbc.row.GameObjectDisplayInfo
