---@meta
-- Generated LuaLS annotations for Holidays.dbc. Do not edit.

---Row representation of Holidays.dbc.
---@class dbc.row.Holidays : RowProxy
---@field ID integer
---@field Duration integer[]
---@field Date integer[]
---@field Region integer
---@field Looping integer
---@field CalendarFlags integer[]
---@field HolidayNameID integer
---@field HolidayDescriptionID integer
---@field TextureFilename string
---@field Priority integer
---@field CalendarFilterType integer
---@field Flags integer

-- Fluent PascalCase Methods for Holidays
---@field GetID fun(self: dbc.row.Holidays): integer
---@field SetID fun(self: dbc.row.Holidays, value: integer): dbc.row.Holidays
---@field GetDuration fun(self: dbc.row.Holidays, index?: integer): integer|integer[]
---@field SetDuration fun(self: dbc.row.Holidays, value: integer|integer[], index?: integer): dbc.row.Holidays
---@field GetDate fun(self: dbc.row.Holidays, index?: integer): integer|integer[]
---@field SetDate fun(self: dbc.row.Holidays, value: integer|integer[], index?: integer): dbc.row.Holidays
---@field GetRegion fun(self: dbc.row.Holidays): integer
---@field SetRegion fun(self: dbc.row.Holidays, value: integer): dbc.row.Holidays
---@field GetLooping fun(self: dbc.row.Holidays): integer
---@field SetLooping fun(self: dbc.row.Holidays, value: integer): dbc.row.Holidays
---@field GetCalendarFlags fun(self: dbc.row.Holidays, index?: integer): integer|integer[]
---@field SetCalendarFlags fun(self: dbc.row.Holidays, value: integer|integer[], index?: integer): dbc.row.Holidays
---@field HasCalendarFlags fun(self: dbc.row.Holidays, flag: integer): boolean
---@field AddCalendarFlags fun(self: dbc.row.Holidays, flag: integer): dbc.row.Holidays
---@field RemoveCalendarFlags fun(self: dbc.row.Holidays, flag: integer): dbc.row.Holidays
---@field GetHolidayNameID fun(self: dbc.row.Holidays): integer
---@field SetHolidayNameID fun(self: dbc.row.Holidays, value: integer): dbc.row.Holidays
---@field GetHolidayDescriptionID fun(self: dbc.row.Holidays): integer
---@field SetHolidayDescriptionID fun(self: dbc.row.Holidays, value: integer): dbc.row.Holidays
---@field GetTextureFilename fun(self: dbc.row.Holidays): string
---@field SetTextureFilename fun(self: dbc.row.Holidays, value: string): dbc.row.Holidays
---@field GetPriority fun(self: dbc.row.Holidays): integer
---@field SetPriority fun(self: dbc.row.Holidays, value: integer): dbc.row.Holidays
---@field GetCalendarFilterType fun(self: dbc.row.Holidays): integer
---@field SetCalendarFilterType fun(self: dbc.row.Holidays, value: integer): dbc.row.Holidays
---@field GetFlags fun(self: dbc.row.Holidays): integer
---@field SetFlags fun(self: dbc.row.Holidays, value: integer): dbc.row.Holidays
---@field HasFlags fun(self: dbc.row.Holidays, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.Holidays, flag: integer): dbc.row.Holidays
---@field RemoveFlags fun(self: dbc.row.Holidays, flag: integer): dbc.row.Holidays

-- Inferred Cross-Table Relations for Holidays

-- Cascading Creation & Relations Engine for Holidays
---@field CreateRelated fun(self: dbc.row.Holidays, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.Holidays, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.Holidays, child_table: string, child_field?: string): any[]

---Typed table handle for Holidays.dbc.
---@class dbc.Table.Holidays : DbcTable
---@field FindById fun(self: dbc.Table.Holidays, id: integer): dbc.row.Holidays|nil
---@field GetById fun(self: dbc.Table.Holidays, id: integer): dbc.row.Holidays|nil
---@field GetRow fun(self: dbc.Table.Holidays, row: integer): dbc.row.Holidays
---@field NewRow fun(self: dbc.Table.Holidays, id?: integer): dbc.row.Holidays
---@field Create fun(self: dbc.Table.Holidays, id?: integer): dbc.row.Holidays
---@field CreateNext fun(self: dbc.Table.Holidays, data?: table): dbc.row.Holidays
---@field CloneRow fun(self: dbc.Table.Holidays, source: integer|dbc.row.Holidays, new_id?: integer): dbc.row.Holidays
---@field GetAllRows fun(self: dbc.Table.Holidays): dbc.row.Holidays[]
---@field Query fun(self: dbc.Table.Holidays): dbc.Query<dbc.row.Holidays>
---@field Rows fun(self: dbc.Table.Holidays): fun(): integer, dbc.row.Holidays
