---@meta
-- Generated LuaLS annotations for Item.dbc. Do not edit.

---Row representation of Item.dbc.
---@class dbc.row.Item : RowProxy
---@field ID integer
---@field ClassID integer
---@field SubclassID integer
---@field Sound_Override_Subclassid integer
---@field Material integer
---@field DisplayInfoID integer
---@field InventoryType integer
---@field SheatheType integer

-- Fluent PascalCase Methods for Item
---@field GetID fun(self: dbc.row.Item): integer
---@field SetID fun(self: dbc.row.Item, value: integer): dbc.row.Item
---@field GetClassID fun(self: dbc.row.Item): integer
---@field SetClassID fun(self: dbc.row.Item, value: integer): dbc.row.Item
---@field GetSubclassID fun(self: dbc.row.Item): integer
---@field SetSubclassID fun(self: dbc.row.Item, value: integer): dbc.row.Item
---@field GetSound_Override_Subclassid fun(self: dbc.row.Item): integer
---@field SetSound_Override_Subclassid fun(self: dbc.row.Item, value: integer): dbc.row.Item
---@field GetMaterial fun(self: dbc.row.Item): integer
---@field SetMaterial fun(self: dbc.row.Item, value: integer): dbc.row.Item
---@field GetDisplayInfoID fun(self: dbc.row.Item): integer
---@field SetDisplayInfoID fun(self: dbc.row.Item, value: integer): dbc.row.Item
---@field GetInventoryType fun(self: dbc.row.Item): integer
---@field SetInventoryType fun(self: dbc.row.Item, value: integer): dbc.row.Item
---@field GetSheatheType fun(self: dbc.row.Item): integer
---@field SetSheatheType fun(self: dbc.row.Item, value: integer): dbc.row.Item

-- Inferred Cross-Table Relations for Item
---@field GetCreatureDisplayInfo fun(self: dbc.row.Item): dbc.row.CreatureDisplayInfo|nil
---@field SetCreatureDisplayInfo fun(self: dbc.row.Item, target: dbc.row.CreatureDisplayInfo|integer): dbc.row.Item

-- Cascading Creation & Relations Engine for Item
---@field CreateRelated fun(self: dbc.row.Item, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.Item, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.Item, child_table: string, child_field?: string): any[]

---Typed table handle for Item.dbc.
---@class dbc.Table.Item : DbcTable
---@field FindById fun(self: dbc.Table.Item, id: integer): dbc.row.Item|nil
---@field GetById fun(self: dbc.Table.Item, id: integer): dbc.row.Item|nil
---@field GetRow fun(self: dbc.Table.Item, row: integer): dbc.row.Item
---@field NewRow fun(self: dbc.Table.Item, id?: integer): dbc.row.Item
---@field Create fun(self: dbc.Table.Item, id?: integer): dbc.row.Item
---@field CreateNext fun(self: dbc.Table.Item, data?: table): dbc.row.Item
---@field CloneRow fun(self: dbc.Table.Item, source: integer|dbc.row.Item, new_id?: integer): dbc.row.Item
---@field GetAllRows fun(self: dbc.Table.Item): dbc.row.Item[]
---@field Query fun(self: dbc.Table.Item): dbc.Query<dbc.row.Item>
---@field Rows fun(self: dbc.Table.Item): fun(): integer, dbc.row.Item
