---@meta
-- Generated LuaLS annotations for LfgDungeons.dbc. Do not edit.

---Row representation of LfgDungeons.dbc.
---@class dbc.row.LfgDungeons : RowProxy
---@field ID integer
---@field Name string
---@field MinLevel integer
---@field MaxLevel integer
---@field Target_Level integer
---@field Target_Level_Min integer
---@field Target_Level_Max integer
---@field MapID integer
---@field Difficulty integer
---@field Flags integer
---@field TypeID integer
---@field Faction integer
---@field TextureFilename string
---@field ExpansionLevel integer
---@field Order_Index integer
---@field Group_Id integer
---@field Description string

-- Fluent PascalCase Methods for LfgDungeons
---@field GetID fun(self: dbc.row.LfgDungeons): integer
---@field SetID fun(self: dbc.row.LfgDungeons, value: integer): dbc.row.LfgDungeons
---@field GetName fun(self: dbc.row.LfgDungeons, locale?: string|integer): string
---@field SetName fun(self: dbc.row.LfgDungeons, value: string, locale?: string|integer): dbc.row.LfgDungeons
---@field GetMinLevel fun(self: dbc.row.LfgDungeons): integer
---@field SetMinLevel fun(self: dbc.row.LfgDungeons, value: integer): dbc.row.LfgDungeons
---@field GetMaxLevel fun(self: dbc.row.LfgDungeons): integer
---@field SetMaxLevel fun(self: dbc.row.LfgDungeons, value: integer): dbc.row.LfgDungeons
---@field GetTarget_Level fun(self: dbc.row.LfgDungeons): integer
---@field SetTarget_Level fun(self: dbc.row.LfgDungeons, value: integer): dbc.row.LfgDungeons
---@field GetTarget_Level_Min fun(self: dbc.row.LfgDungeons): integer
---@field SetTarget_Level_Min fun(self: dbc.row.LfgDungeons, value: integer): dbc.row.LfgDungeons
---@field GetTarget_Level_Max fun(self: dbc.row.LfgDungeons): integer
---@field SetTarget_Level_Max fun(self: dbc.row.LfgDungeons, value: integer): dbc.row.LfgDungeons
---@field GetMapID fun(self: dbc.row.LfgDungeons): integer
---@field SetMapID fun(self: dbc.row.LfgDungeons, value: integer): dbc.row.LfgDungeons
---@field GetDifficulty fun(self: dbc.row.LfgDungeons): integer
---@field SetDifficulty fun(self: dbc.row.LfgDungeons, value: integer): dbc.row.LfgDungeons
---@field GetFlags fun(self: dbc.row.LfgDungeons): integer
---@field SetFlags fun(self: dbc.row.LfgDungeons, value: integer): dbc.row.LfgDungeons
---@field HasFlags fun(self: dbc.row.LfgDungeons, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.LfgDungeons, flag: integer): dbc.row.LfgDungeons
---@field RemoveFlags fun(self: dbc.row.LfgDungeons, flag: integer): dbc.row.LfgDungeons
---@field GetTypeID fun(self: dbc.row.LfgDungeons): integer
---@field SetTypeID fun(self: dbc.row.LfgDungeons, value: integer): dbc.row.LfgDungeons
---@field GetFaction fun(self: dbc.row.LfgDungeons): integer
---@field SetFaction fun(self: dbc.row.LfgDungeons, value: integer): dbc.row.LfgDungeons
---@field GetTextureFilename fun(self: dbc.row.LfgDungeons): string
---@field SetTextureFilename fun(self: dbc.row.LfgDungeons, value: string): dbc.row.LfgDungeons
---@field GetExpansionLevel fun(self: dbc.row.LfgDungeons): integer
---@field SetExpansionLevel fun(self: dbc.row.LfgDungeons, value: integer): dbc.row.LfgDungeons
---@field GetOrder_Index fun(self: dbc.row.LfgDungeons): integer
---@field SetOrder_Index fun(self: dbc.row.LfgDungeons, value: integer): dbc.row.LfgDungeons
---@field GetGroup_Id fun(self: dbc.row.LfgDungeons): integer
---@field SetGroup_Id fun(self: dbc.row.LfgDungeons, value: integer): dbc.row.LfgDungeons
---@field GetDescription fun(self: dbc.row.LfgDungeons, locale?: string|integer): string
---@field SetDescription fun(self: dbc.row.LfgDungeons, value: string, locale?: string|integer): dbc.row.LfgDungeons

-- Inferred Cross-Table Relations for LfgDungeons
---@field GetMap fun(self: dbc.row.LfgDungeons): dbc.row.Map|nil
---@field SetMap fun(self: dbc.row.LfgDungeons, target: dbc.row.Map|integer): dbc.row.LfgDungeons
---@field GetFaction fun(self: dbc.row.LfgDungeons): dbc.row.Faction|nil
---@field SetFaction fun(self: dbc.row.LfgDungeons, target: dbc.row.Faction|integer): dbc.row.LfgDungeons

-- Cascading Creation & Relations Engine for LfgDungeons
---@field CreateRelated fun(self: dbc.row.LfgDungeons, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.LfgDungeons, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.LfgDungeons, child_table: string, child_field?: string): any[]

---Typed table handle for LfgDungeons.dbc.
---@class dbc.Table.LfgDungeons : DbcTable
---@field FindById fun(self: dbc.Table.LfgDungeons, id: integer): dbc.row.LfgDungeons|nil
---@field GetById fun(self: dbc.Table.LfgDungeons, id: integer): dbc.row.LfgDungeons|nil
---@field GetRow fun(self: dbc.Table.LfgDungeons, row: integer): dbc.row.LfgDungeons
---@field NewRow fun(self: dbc.Table.LfgDungeons, id?: integer): dbc.row.LfgDungeons
---@field Create fun(self: dbc.Table.LfgDungeons, id?: integer): dbc.row.LfgDungeons
---@field CreateNext fun(self: dbc.Table.LfgDungeons, data?: table): dbc.row.LfgDungeons
---@field CloneRow fun(self: dbc.Table.LfgDungeons, source: integer|dbc.row.LfgDungeons, new_id?: integer): dbc.row.LfgDungeons
---@field GetAllRows fun(self: dbc.Table.LfgDungeons): dbc.row.LfgDungeons[]
---@field Query fun(self: dbc.Table.LfgDungeons): dbc.Query<dbc.row.LfgDungeons>
---@field Rows fun(self: dbc.Table.LfgDungeons): fun(): integer, dbc.row.LfgDungeons
