---@meta
-- Generated LuaLS annotations for Light.dbc. Do not edit.

---Row representation of Light.dbc.
---@class dbc.row.Light : RowProxy
---@field ID integer
---@field MapID integer
---@field X number
---@field Y number
---@field Z number
---@field FalloffStart number
---@field FalloffEnd number
---@field LightParamsID integer[]

-- Fluent PascalCase Methods for Light
---@field GetID fun(self: dbc.row.Light): integer
---@field SetID fun(self: dbc.row.Light, value: integer): dbc.row.Light
---@field GetMapID fun(self: dbc.row.Light): integer
---@field SetMapID fun(self: dbc.row.Light, value: integer): dbc.row.Light
---@field GetX fun(self: dbc.row.Light): number
---@field SetX fun(self: dbc.row.Light, value: number): dbc.row.Light
---@field GetY fun(self: dbc.row.Light): number
---@field SetY fun(self: dbc.row.Light, value: number): dbc.row.Light
---@field GetZ fun(self: dbc.row.Light): number
---@field SetZ fun(self: dbc.row.Light, value: number): dbc.row.Light
---@field GetFalloffStart fun(self: dbc.row.Light): number
---@field SetFalloffStart fun(self: dbc.row.Light, value: number): dbc.row.Light
---@field GetFalloffEnd fun(self: dbc.row.Light): number
---@field SetFalloffEnd fun(self: dbc.row.Light, value: number): dbc.row.Light
---@field GetLightParamsID fun(self: dbc.row.Light, index?: integer): integer|integer[]
---@field SetLightParamsID fun(self: dbc.row.Light, value: integer|integer[], index?: integer): dbc.row.Light

-- Inferred Cross-Table Relations for Light
---@field GetMap fun(self: dbc.row.Light): dbc.row.Map|nil
---@field SetMap fun(self: dbc.row.Light, target: dbc.row.Map|integer): dbc.row.Light
---@field GetLightParams fun(self: dbc.row.Light): dbc.row.LightParams|nil
---@field SetLightParams fun(self: dbc.row.Light, target: dbc.row.LightParams|integer): dbc.row.Light

-- Cascading Creation & Relations Engine for Light
---@field CreateRelated fun(self: dbc.row.Light, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.Light, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.Light, child_table: string, child_field?: string): any[]

---Typed table handle for Light.dbc.
---@class dbc.Table.Light : DbcTable
---@field FindById fun(self: dbc.Table.Light, id: integer): dbc.row.Light|nil
---@field GetById fun(self: dbc.Table.Light, id: integer): dbc.row.Light|nil
---@field GetRow fun(self: dbc.Table.Light, row: integer): dbc.row.Light
---@field NewRow fun(self: dbc.Table.Light, id?: integer): dbc.row.Light
---@field Create fun(self: dbc.Table.Light, id?: integer): dbc.row.Light
---@field CreateNext fun(self: dbc.Table.Light, data?: table): dbc.row.Light
---@field CloneRow fun(self: dbc.Table.Light, source: integer|dbc.row.Light, new_id?: integer): dbc.row.Light
---@field GetAllRows fun(self: dbc.Table.Light): dbc.row.Light[]
---@field Query fun(self: dbc.Table.Light): dbc.Query<dbc.row.Light>
---@field Rows fun(self: dbc.Table.Light): fun(): integer, dbc.row.Light
