---@meta
-- Generated LuaLS annotations for LiquidType.dbc. Do not edit.

---Row representation of LiquidType.dbc.
---@class dbc.row.LiquidType : RowProxy
---@field ID integer
---@field Name string
---@field Flags integer
---@field Type integer
---@field SoundID integer
---@field SpellID integer
---@field MaxDarkenDepth number
---@field FogDarkenintensity number
---@field AmbDarkenintensity number
---@field DirDarkenintensity number
---@field LightID integer
---@field ParticleScale number
---@field ParticleMovement integer
---@field ParticleTexSlots integer
---@field MaterialID integer
---@field Texture string[]
---@field Color integer[]
---@field Float number[]
---@field Int integer[]

-- Fluent PascalCase Methods for LiquidType
---@field GetID fun(self: dbc.row.LiquidType): integer
---@field SetID fun(self: dbc.row.LiquidType, value: integer): dbc.row.LiquidType
---@field GetName fun(self: dbc.row.LiquidType): string
---@field SetName fun(self: dbc.row.LiquidType, value: string): dbc.row.LiquidType
---@field GetFlags fun(self: dbc.row.LiquidType): integer
---@field SetFlags fun(self: dbc.row.LiquidType, value: integer): dbc.row.LiquidType
---@field HasFlags fun(self: dbc.row.LiquidType, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.LiquidType, flag: integer): dbc.row.LiquidType
---@field RemoveFlags fun(self: dbc.row.LiquidType, flag: integer): dbc.row.LiquidType
---@field GetType fun(self: dbc.row.LiquidType): integer
---@field SetType fun(self: dbc.row.LiquidType, value: integer): dbc.row.LiquidType
---@field GetSoundID fun(self: dbc.row.LiquidType): integer
---@field SetSoundID fun(self: dbc.row.LiquidType, value: integer): dbc.row.LiquidType
---@field GetSpellID fun(self: dbc.row.LiquidType): integer
---@field SetSpellID fun(self: dbc.row.LiquidType, value: integer): dbc.row.LiquidType
---@field GetMaxDarkenDepth fun(self: dbc.row.LiquidType): number
---@field SetMaxDarkenDepth fun(self: dbc.row.LiquidType, value: number): dbc.row.LiquidType
---@field GetFogDarkenintensity fun(self: dbc.row.LiquidType): number
---@field SetFogDarkenintensity fun(self: dbc.row.LiquidType, value: number): dbc.row.LiquidType
---@field GetAmbDarkenintensity fun(self: dbc.row.LiquidType): number
---@field SetAmbDarkenintensity fun(self: dbc.row.LiquidType, value: number): dbc.row.LiquidType
---@field GetDirDarkenintensity fun(self: dbc.row.LiquidType): number
---@field SetDirDarkenintensity fun(self: dbc.row.LiquidType, value: number): dbc.row.LiquidType
---@field GetLightID fun(self: dbc.row.LiquidType): integer
---@field SetLightID fun(self: dbc.row.LiquidType, value: integer): dbc.row.LiquidType
---@field GetParticleScale fun(self: dbc.row.LiquidType): number
---@field SetParticleScale fun(self: dbc.row.LiquidType, value: number): dbc.row.LiquidType
---@field GetParticleMovement fun(self: dbc.row.LiquidType): integer
---@field SetParticleMovement fun(self: dbc.row.LiquidType, value: integer): dbc.row.LiquidType
---@field GetParticleTexSlots fun(self: dbc.row.LiquidType): integer
---@field SetParticleTexSlots fun(self: dbc.row.LiquidType, value: integer): dbc.row.LiquidType
---@field GetMaterialID fun(self: dbc.row.LiquidType): integer
---@field SetMaterialID fun(self: dbc.row.LiquidType, value: integer): dbc.row.LiquidType
---@field GetTexture fun(self: dbc.row.LiquidType, index?: integer): string|string[]
---@field SetTexture fun(self: dbc.row.LiquidType, value: string|string[], index?: integer): dbc.row.LiquidType
---@field GetColor fun(self: dbc.row.LiquidType, index?: integer): integer|integer[]
---@field SetColor fun(self: dbc.row.LiquidType, value: integer|integer[], index?: integer): dbc.row.LiquidType
---@field GetFloat fun(self: dbc.row.LiquidType, index?: integer): number|number[]
---@field SetFloat fun(self: dbc.row.LiquidType, value: number|number[], index?: integer): dbc.row.LiquidType
---@field GetInt fun(self: dbc.row.LiquidType, index?: integer): integer|integer[]
---@field SetInt fun(self: dbc.row.LiquidType, value: integer|integer[], index?: integer): dbc.row.LiquidType

-- Inferred Cross-Table Relations for LiquidType
---@field GetSoundEntries fun(self: dbc.row.LiquidType): dbc.row.SoundEntries|nil
---@field SetSoundEntries fun(self: dbc.row.LiquidType, target: dbc.row.SoundEntries|integer): dbc.row.LiquidType
---@field GetSpell fun(self: dbc.row.LiquidType): dbc.row.Spell|nil
---@field SetSpell fun(self: dbc.row.LiquidType, target: dbc.row.Spell|integer): dbc.row.LiquidType
---@field GetLight fun(self: dbc.row.LiquidType): dbc.row.Light|nil
---@field SetLight fun(self: dbc.row.LiquidType, target: dbc.row.Light|integer): dbc.row.LiquidType
---@field GetMaterial fun(self: dbc.row.LiquidType): dbc.row.Material|nil
---@field SetMaterial fun(self: dbc.row.LiquidType, target: dbc.row.Material|integer): dbc.row.LiquidType

-- Cascading Creation & Relations Engine for LiquidType
---@field CreateRelated fun(self: dbc.row.LiquidType, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.LiquidType, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.LiquidType, child_table: string, child_field?: string): any[]

---Typed table handle for LiquidType.dbc.
---@class dbc.Table.LiquidType : DbcTable
---@field FindById fun(self: dbc.Table.LiquidType, id: integer): dbc.row.LiquidType|nil
---@field GetById fun(self: dbc.Table.LiquidType, id: integer): dbc.row.LiquidType|nil
---@field GetRow fun(self: dbc.Table.LiquidType, row: integer): dbc.row.LiquidType
---@field NewRow fun(self: dbc.Table.LiquidType, id?: integer): dbc.row.LiquidType
---@field Create fun(self: dbc.Table.LiquidType, id?: integer): dbc.row.LiquidType
---@field CreateNext fun(self: dbc.Table.LiquidType, data?: table): dbc.row.LiquidType
---@field CloneRow fun(self: dbc.Table.LiquidType, source: integer|dbc.row.LiquidType, new_id?: integer): dbc.row.LiquidType
---@field GetAllRows fun(self: dbc.Table.LiquidType): dbc.row.LiquidType[]
---@field Query fun(self: dbc.Table.LiquidType): dbc.Query<dbc.row.LiquidType>
---@field Rows fun(self: dbc.Table.LiquidType): fun(): integer, dbc.row.LiquidType
