---@meta
-- Generated LuaLS annotations for Map.dbc. Do not edit.

---Row representation of Map.dbc.
---@class dbc.row.Map : RowProxy
---@field ID integer
---@field Directory string
---@field InstanceType integer
---@field Flags integer
---@field PVP integer
---@field MapName string
---@field AreaTableID integer
---@field MapDescription0 string
---@field MapDescription1 string
---@field LoadingScreenID integer
---@field MinimapIconScale number
---@field CorpseMapID integer
---@field CorpseX number
---@field CorpseY number
---@field TimeOfDayOverride integer
---@field ExpansionID integer
---@field RaidOffset integer
---@field MaxPlayers integer

-- Fluent PascalCase Methods for Map
---@field GetID fun(self: dbc.row.Map): integer
---@field SetID fun(self: dbc.row.Map, value: integer): dbc.row.Map
---@field GetDirectory fun(self: dbc.row.Map): string
---@field SetDirectory fun(self: dbc.row.Map, value: string): dbc.row.Map
---@field GetInstanceType fun(self: dbc.row.Map): integer
---@field SetInstanceType fun(self: dbc.row.Map, value: integer): dbc.row.Map
---@field GetFlags fun(self: dbc.row.Map): integer
---@field SetFlags fun(self: dbc.row.Map, value: integer): dbc.row.Map
---@field HasFlags fun(self: dbc.row.Map, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.Map, flag: integer): dbc.row.Map
---@field RemoveFlags fun(self: dbc.row.Map, flag: integer): dbc.row.Map
---@field GetPVP fun(self: dbc.row.Map): integer
---@field SetPVP fun(self: dbc.row.Map, value: integer): dbc.row.Map
---@field GetMapName fun(self: dbc.row.Map, locale?: string|integer): string
---@field SetMapName fun(self: dbc.row.Map, value: string, locale?: string|integer): dbc.row.Map
---@field GetAreaTableID fun(self: dbc.row.Map): integer
---@field SetAreaTableID fun(self: dbc.row.Map, value: integer): dbc.row.Map
---@field GetMapDescription0 fun(self: dbc.row.Map, locale?: string|integer): string
---@field SetMapDescription0 fun(self: dbc.row.Map, value: string, locale?: string|integer): dbc.row.Map
---@field GetMapDescription1 fun(self: dbc.row.Map, locale?: string|integer): string
---@field SetMapDescription1 fun(self: dbc.row.Map, value: string, locale?: string|integer): dbc.row.Map
---@field GetLoadingScreenID fun(self: dbc.row.Map): integer
---@field SetLoadingScreenID fun(self: dbc.row.Map, value: integer): dbc.row.Map
---@field GetMinimapIconScale fun(self: dbc.row.Map): number
---@field SetMinimapIconScale fun(self: dbc.row.Map, value: number): dbc.row.Map
---@field GetCorpseMapID fun(self: dbc.row.Map): integer
---@field SetCorpseMapID fun(self: dbc.row.Map, value: integer): dbc.row.Map
---@field GetCorpseX fun(self: dbc.row.Map): number
---@field SetCorpseX fun(self: dbc.row.Map, value: number): dbc.row.Map
---@field GetCorpseY fun(self: dbc.row.Map): number
---@field SetCorpseY fun(self: dbc.row.Map, value: number): dbc.row.Map
---@field GetTimeOfDayOverride fun(self: dbc.row.Map): integer
---@field SetTimeOfDayOverride fun(self: dbc.row.Map, value: integer): dbc.row.Map
---@field GetExpansionID fun(self: dbc.row.Map): integer
---@field SetExpansionID fun(self: dbc.row.Map, value: integer): dbc.row.Map
---@field GetRaidOffset fun(self: dbc.row.Map): integer
---@field SetRaidOffset fun(self: dbc.row.Map, value: integer): dbc.row.Map
---@field GetMaxPlayers fun(self: dbc.row.Map): integer
---@field SetMaxPlayers fun(self: dbc.row.Map, value: integer): dbc.row.Map

-- Inferred Cross-Table Relations for Map
---@field GetAreaTable fun(self: dbc.row.Map): dbc.row.AreaTable|nil
---@field SetAreaTable fun(self: dbc.row.Map, target: dbc.row.AreaTable|integer): dbc.row.Map

-- Cascading Creation & Relations Engine for Map
---@field CreateRelated fun(self: dbc.row.Map, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.Map, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.Map, child_table: string, child_field?: string): any[]

---Typed table handle for Map.dbc.
---@class dbc.Table.Map : DbcTable
---@field FindById fun(self: dbc.Table.Map, id: integer): dbc.row.Map|nil
---@field GetById fun(self: dbc.Table.Map, id: integer): dbc.row.Map|nil
---@field GetRow fun(self: dbc.Table.Map, row: integer): dbc.row.Map
---@field NewRow fun(self: dbc.Table.Map, id?: integer): dbc.row.Map
---@field Create fun(self: dbc.Table.Map, id?: integer): dbc.row.Map
---@field CreateNext fun(self: dbc.Table.Map, data?: table): dbc.row.Map
---@field CloneRow fun(self: dbc.Table.Map, source: integer|dbc.row.Map, new_id?: integer): dbc.row.Map
---@field GetAllRows fun(self: dbc.Table.Map): dbc.row.Map[]
---@field Query fun(self: dbc.Table.Map): dbc.Query<dbc.row.Map>
---@field Rows fun(self: dbc.Table.Map): fun(): integer, dbc.row.Map
