---@meta
-- Generated LuaLS annotations for ObjectEffect.dbc. Do not edit.

---Row representation of ObjectEffect.dbc.
---@class dbc.row.ObjectEffect : RowProxy
---@field ID integer
---@field Name string
---@field ObjectEffectGroupID integer
---@field TriggerType integer
---@field EventType integer
---@field EffectRecType integer
---@field EffectRecID integer
---@field Attachment integer
---@field OffsetX number
---@field OffsetY number
---@field OffsetZ number
---@field ObjectEffectModifierID integer

-- Fluent PascalCase Methods for ObjectEffect
---@field GetID fun(self: dbc.row.ObjectEffect): integer
---@field SetID fun(self: dbc.row.ObjectEffect, value: integer): dbc.row.ObjectEffect
---@field GetName fun(self: dbc.row.ObjectEffect): string
---@field SetName fun(self: dbc.row.ObjectEffect, value: string): dbc.row.ObjectEffect
---@field GetObjectEffectGroupID fun(self: dbc.row.ObjectEffect): integer
---@field SetObjectEffectGroupID fun(self: dbc.row.ObjectEffect, value: integer): dbc.row.ObjectEffect
---@field GetTriggerType fun(self: dbc.row.ObjectEffect): integer
---@field SetTriggerType fun(self: dbc.row.ObjectEffect, value: integer): dbc.row.ObjectEffect
---@field GetEventType fun(self: dbc.row.ObjectEffect): integer
---@field SetEventType fun(self: dbc.row.ObjectEffect, value: integer): dbc.row.ObjectEffect
---@field GetEffectRecType fun(self: dbc.row.ObjectEffect): integer
---@field SetEffectRecType fun(self: dbc.row.ObjectEffect, value: integer): dbc.row.ObjectEffect
---@field GetEffectRecID fun(self: dbc.row.ObjectEffect): integer
---@field SetEffectRecID fun(self: dbc.row.ObjectEffect, value: integer): dbc.row.ObjectEffect
---@field GetAttachment fun(self: dbc.row.ObjectEffect): integer
---@field SetAttachment fun(self: dbc.row.ObjectEffect, value: integer): dbc.row.ObjectEffect
---@field GetOffsetX fun(self: dbc.row.ObjectEffect): number
---@field SetOffsetX fun(self: dbc.row.ObjectEffect, value: number): dbc.row.ObjectEffect
---@field GetOffsetY fun(self: dbc.row.ObjectEffect): number
---@field SetOffsetY fun(self: dbc.row.ObjectEffect, value: number): dbc.row.ObjectEffect
---@field GetOffsetZ fun(self: dbc.row.ObjectEffect): number
---@field SetOffsetZ fun(self: dbc.row.ObjectEffect, value: number): dbc.row.ObjectEffect
---@field GetObjectEffectModifierID fun(self: dbc.row.ObjectEffect): integer
---@field SetObjectEffectModifierID fun(self: dbc.row.ObjectEffect, value: integer): dbc.row.ObjectEffect

-- Inferred Cross-Table Relations for ObjectEffect
---@field GetObjectEffectGroup fun(self: dbc.row.ObjectEffect): dbc.row.ObjectEffectGroup|nil
---@field SetObjectEffectGroup fun(self: dbc.row.ObjectEffect, target: dbc.row.ObjectEffectGroup|integer): dbc.row.ObjectEffect
---@field GetObjectEffectModifier fun(self: dbc.row.ObjectEffect): dbc.row.ObjectEffectModifier|nil
---@field SetObjectEffectModifier fun(self: dbc.row.ObjectEffect, target: dbc.row.ObjectEffectModifier|integer): dbc.row.ObjectEffect

-- Cascading Creation & Relations Engine for ObjectEffect
---@field CreateRelated fun(self: dbc.row.ObjectEffect, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.ObjectEffect, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.ObjectEffect, child_table: string, child_field?: string): any[]

---Typed table handle for ObjectEffect.dbc.
---@class dbc.Table.ObjectEffect : DbcTable
---@field FindById fun(self: dbc.Table.ObjectEffect, id: integer): dbc.row.ObjectEffect|nil
---@field GetById fun(self: dbc.Table.ObjectEffect, id: integer): dbc.row.ObjectEffect|nil
---@field GetRow fun(self: dbc.Table.ObjectEffect, row: integer): dbc.row.ObjectEffect
---@field NewRow fun(self: dbc.Table.ObjectEffect, id?: integer): dbc.row.ObjectEffect
---@field Create fun(self: dbc.Table.ObjectEffect, id?: integer): dbc.row.ObjectEffect
---@field CreateNext fun(self: dbc.Table.ObjectEffect, data?: table): dbc.row.ObjectEffect
---@field CloneRow fun(self: dbc.Table.ObjectEffect, source: integer|dbc.row.ObjectEffect, new_id?: integer): dbc.row.ObjectEffect
---@field GetAllRows fun(self: dbc.Table.ObjectEffect): dbc.row.ObjectEffect[]
---@field Query fun(self: dbc.Table.ObjectEffect): dbc.Query<dbc.row.ObjectEffect>
---@field Rows fun(self: dbc.Table.ObjectEffect): fun(): integer, dbc.row.ObjectEffect
