---@meta
-- Generated LuaLS annotations for SkillRaceClassInfo.dbc. Do not edit.

---Row representation of SkillRaceClassInfo.dbc.
---@class dbc.row.SkillRaceClassInfo : RowProxy
---@field ID integer
---@field SkillID integer
---@field RaceMask integer
---@field ClassMask integer
---@field Flags integer
---@field MinLevel integer
---@field SkillTierID integer
---@field SkillCostIndex integer

-- Fluent PascalCase Methods for SkillRaceClassInfo
---@field GetID fun(self: dbc.row.SkillRaceClassInfo): integer
---@field SetID fun(self: dbc.row.SkillRaceClassInfo, value: integer): dbc.row.SkillRaceClassInfo
---@field GetSkillID fun(self: dbc.row.SkillRaceClassInfo): integer
---@field SetSkillID fun(self: dbc.row.SkillRaceClassInfo, value: integer): dbc.row.SkillRaceClassInfo
---@field GetRaceMask fun(self: dbc.row.SkillRaceClassInfo): integer
---@field SetRaceMask fun(self: dbc.row.SkillRaceClassInfo, value: integer): dbc.row.SkillRaceClassInfo
---@field HasRaceMask fun(self: dbc.row.SkillRaceClassInfo, flag: integer): boolean
---@field AddRaceMask fun(self: dbc.row.SkillRaceClassInfo, flag: integer): dbc.row.SkillRaceClassInfo
---@field RemoveRaceMask fun(self: dbc.row.SkillRaceClassInfo, flag: integer): dbc.row.SkillRaceClassInfo
---@field GetClassMask fun(self: dbc.row.SkillRaceClassInfo): integer
---@field SetClassMask fun(self: dbc.row.SkillRaceClassInfo, value: integer): dbc.row.SkillRaceClassInfo
---@field HasClassMask fun(self: dbc.row.SkillRaceClassInfo, flag: integer): boolean
---@field AddClassMask fun(self: dbc.row.SkillRaceClassInfo, flag: integer): dbc.row.SkillRaceClassInfo
---@field RemoveClassMask fun(self: dbc.row.SkillRaceClassInfo, flag: integer): dbc.row.SkillRaceClassInfo
---@field GetFlags fun(self: dbc.row.SkillRaceClassInfo): integer
---@field SetFlags fun(self: dbc.row.SkillRaceClassInfo, value: integer): dbc.row.SkillRaceClassInfo
---@field HasFlags fun(self: dbc.row.SkillRaceClassInfo, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.SkillRaceClassInfo, flag: integer): dbc.row.SkillRaceClassInfo
---@field RemoveFlags fun(self: dbc.row.SkillRaceClassInfo, flag: integer): dbc.row.SkillRaceClassInfo
---@field GetMinLevel fun(self: dbc.row.SkillRaceClassInfo): integer
---@field SetMinLevel fun(self: dbc.row.SkillRaceClassInfo, value: integer): dbc.row.SkillRaceClassInfo
---@field GetSkillTierID fun(self: dbc.row.SkillRaceClassInfo): integer
---@field SetSkillTierID fun(self: dbc.row.SkillRaceClassInfo, value: integer): dbc.row.SkillRaceClassInfo
---@field GetSkillCostIndex fun(self: dbc.row.SkillRaceClassInfo): integer
---@field SetSkillCostIndex fun(self: dbc.row.SkillRaceClassInfo, value: integer): dbc.row.SkillRaceClassInfo

-- Inferred Cross-Table Relations for SkillRaceClassInfo

-- Cascading Creation & Relations Engine for SkillRaceClassInfo
---@field CreateRelated fun(self: dbc.row.SkillRaceClassInfo, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.SkillRaceClassInfo, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.SkillRaceClassInfo, child_table: string, child_field?: string): any[]

---Typed table handle for SkillRaceClassInfo.dbc.
---@class dbc.Table.SkillRaceClassInfo : DbcTable
---@field FindById fun(self: dbc.Table.SkillRaceClassInfo, id: integer): dbc.row.SkillRaceClassInfo|nil
---@field GetById fun(self: dbc.Table.SkillRaceClassInfo, id: integer): dbc.row.SkillRaceClassInfo|nil
---@field GetRow fun(self: dbc.Table.SkillRaceClassInfo, row: integer): dbc.row.SkillRaceClassInfo
---@field NewRow fun(self: dbc.Table.SkillRaceClassInfo, id?: integer): dbc.row.SkillRaceClassInfo
---@field Create fun(self: dbc.Table.SkillRaceClassInfo, id?: integer): dbc.row.SkillRaceClassInfo
---@field CreateNext fun(self: dbc.Table.SkillRaceClassInfo, data?: table): dbc.row.SkillRaceClassInfo
---@field CloneRow fun(self: dbc.Table.SkillRaceClassInfo, source: integer|dbc.row.SkillRaceClassInfo, new_id?: integer): dbc.row.SkillRaceClassInfo
---@field GetAllRows fun(self: dbc.Table.SkillRaceClassInfo): dbc.row.SkillRaceClassInfo[]
---@field Query fun(self: dbc.Table.SkillRaceClassInfo): dbc.Query<dbc.row.SkillRaceClassInfo>
---@field Rows fun(self: dbc.Table.SkillRaceClassInfo): fun(): integer, dbc.row.SkillRaceClassInfo
