---@meta
-- Generated LuaLS annotations for SoundEntries.dbc. Do not edit.

---Row representation of SoundEntries.dbc.
---@class dbc.row.SoundEntries : RowProxy
---@field ID integer
---@field SoundType integer
---@field Name string
---@field File string[]
---@field Freq integer[]
---@field DirectoryBase string
---@field Volumefloat number
---@field Flags integer
---@field MinDistance number
---@field DistanceCutoff number
---@field EAXDef integer
---@field SoundEntriesAdvancedID integer

-- Fluent PascalCase Methods for SoundEntries
---@field GetID fun(self: dbc.row.SoundEntries): integer
---@field SetID fun(self: dbc.row.SoundEntries, value: integer): dbc.row.SoundEntries
---@field GetSoundType fun(self: dbc.row.SoundEntries): integer
---@field SetSoundType fun(self: dbc.row.SoundEntries, value: integer): dbc.row.SoundEntries
---@field GetName fun(self: dbc.row.SoundEntries): string
---@field SetName fun(self: dbc.row.SoundEntries, value: string): dbc.row.SoundEntries
---@field GetFile fun(self: dbc.row.SoundEntries, index?: integer): string|string[]
---@field SetFile fun(self: dbc.row.SoundEntries, value: string|string[], index?: integer): dbc.row.SoundEntries
---@field GetFreq fun(self: dbc.row.SoundEntries, index?: integer): integer|integer[]
---@field SetFreq fun(self: dbc.row.SoundEntries, value: integer|integer[], index?: integer): dbc.row.SoundEntries
---@field GetDirectoryBase fun(self: dbc.row.SoundEntries): string
---@field SetDirectoryBase fun(self: dbc.row.SoundEntries, value: string): dbc.row.SoundEntries
---@field GetVolumefloat fun(self: dbc.row.SoundEntries): number
---@field SetVolumefloat fun(self: dbc.row.SoundEntries, value: number): dbc.row.SoundEntries
---@field GetFlags fun(self: dbc.row.SoundEntries): integer
---@field SetFlags fun(self: dbc.row.SoundEntries, value: integer): dbc.row.SoundEntries
---@field HasFlags fun(self: dbc.row.SoundEntries, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.SoundEntries, flag: integer): dbc.row.SoundEntries
---@field RemoveFlags fun(self: dbc.row.SoundEntries, flag: integer): dbc.row.SoundEntries
---@field GetMinDistance fun(self: dbc.row.SoundEntries): number
---@field SetMinDistance fun(self: dbc.row.SoundEntries, value: number): dbc.row.SoundEntries
---@field GetDistanceCutoff fun(self: dbc.row.SoundEntries): number
---@field SetDistanceCutoff fun(self: dbc.row.SoundEntries, value: number): dbc.row.SoundEntries
---@field GetEAXDef fun(self: dbc.row.SoundEntries): integer
---@field SetEAXDef fun(self: dbc.row.SoundEntries, value: integer): dbc.row.SoundEntries
---@field GetSoundEntriesAdvancedID fun(self: dbc.row.SoundEntries): integer
---@field SetSoundEntriesAdvancedID fun(self: dbc.row.SoundEntries, value: integer): dbc.row.SoundEntries

-- Inferred Cross-Table Relations for SoundEntries
---@field GetSoundEntriesAdvanced fun(self: dbc.row.SoundEntries): dbc.row.SoundEntriesAdvanced|nil
---@field SetSoundEntriesAdvanced fun(self: dbc.row.SoundEntries, target: dbc.row.SoundEntriesAdvanced|integer): dbc.row.SoundEntries

-- Cascading Creation & Relations Engine for SoundEntries
---@field CreateRelated fun(self: dbc.row.SoundEntries, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.SoundEntries, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.SoundEntries, child_table: string, child_field?: string): any[]

---Typed table handle for SoundEntries.dbc.
---@class dbc.Table.SoundEntries : DbcTable
---@field FindById fun(self: dbc.Table.SoundEntries, id: integer): dbc.row.SoundEntries|nil
---@field GetById fun(self: dbc.Table.SoundEntries, id: integer): dbc.row.SoundEntries|nil
---@field GetRow fun(self: dbc.Table.SoundEntries, row: integer): dbc.row.SoundEntries
---@field NewRow fun(self: dbc.Table.SoundEntries, id?: integer): dbc.row.SoundEntries
---@field Create fun(self: dbc.Table.SoundEntries, id?: integer): dbc.row.SoundEntries
---@field CreateNext fun(self: dbc.Table.SoundEntries, data?: table): dbc.row.SoundEntries
---@field CloneRow fun(self: dbc.Table.SoundEntries, source: integer|dbc.row.SoundEntries, new_id?: integer): dbc.row.SoundEntries
---@field GetAllRows fun(self: dbc.Table.SoundEntries): dbc.row.SoundEntries[]
---@field Query fun(self: dbc.Table.SoundEntries): dbc.Query<dbc.row.SoundEntries>
---@field Rows fun(self: dbc.Table.SoundEntries): fun(): integer, dbc.row.SoundEntries
