---@meta
-- Generated LuaLS annotations for SoundProviderPreferences.dbc. Do not edit.

---Row representation of SoundProviderPreferences.dbc.
---@class dbc.row.SoundProviderPreferences : RowProxy
---@field ID integer
---@field Description string
---@field Flags integer
---@field EAXEnvironmentSelection integer
---@field EAXDecayTime number
---@field EAX2EnvironmentSize number
---@field EAX2EnvironmentDiffusion number
---@field EAX2Room integer
---@field EAX2RoomHF integer
---@field EAX2DecayHFRatio number
---@field EAX2Reflections integer
---@field EAX2ReflectionsDelay number
---@field EAX2Reverb integer
---@field EAX2ReverbDelay number
---@field EAX2RoomRolloff number
---@field EAX2AirAbsorption number
---@field EAX3RoomLF integer
---@field EAX3DecayLFRatio number
---@field EAX3EchoTime number
---@field EAX3EchoDepth number
---@field EAX3ModulationTime number
---@field EAX3ModulationDepth number
---@field EAX3HFReference number
---@field EAX3LFReference number

-- Fluent PascalCase Methods for SoundProviderPreferences
---@field GetID fun(self: dbc.row.SoundProviderPreferences): integer
---@field SetID fun(self: dbc.row.SoundProviderPreferences, value: integer): dbc.row.SoundProviderPreferences
---@field GetDescription fun(self: dbc.row.SoundProviderPreferences): string
---@field SetDescription fun(self: dbc.row.SoundProviderPreferences, value: string): dbc.row.SoundProviderPreferences
---@field GetFlags fun(self: dbc.row.SoundProviderPreferences): integer
---@field SetFlags fun(self: dbc.row.SoundProviderPreferences, value: integer): dbc.row.SoundProviderPreferences
---@field HasFlags fun(self: dbc.row.SoundProviderPreferences, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.SoundProviderPreferences, flag: integer): dbc.row.SoundProviderPreferences
---@field RemoveFlags fun(self: dbc.row.SoundProviderPreferences, flag: integer): dbc.row.SoundProviderPreferences
---@field GetEAXEnvironmentSelection fun(self: dbc.row.SoundProviderPreferences): integer
---@field SetEAXEnvironmentSelection fun(self: dbc.row.SoundProviderPreferences, value: integer): dbc.row.SoundProviderPreferences
---@field GetEAXDecayTime fun(self: dbc.row.SoundProviderPreferences): number
---@field SetEAXDecayTime fun(self: dbc.row.SoundProviderPreferences, value: number): dbc.row.SoundProviderPreferences
---@field GetEAX2EnvironmentSize fun(self: dbc.row.SoundProviderPreferences): number
---@field SetEAX2EnvironmentSize fun(self: dbc.row.SoundProviderPreferences, value: number): dbc.row.SoundProviderPreferences
---@field GetEAX2EnvironmentDiffusion fun(self: dbc.row.SoundProviderPreferences): number
---@field SetEAX2EnvironmentDiffusion fun(self: dbc.row.SoundProviderPreferences, value: number): dbc.row.SoundProviderPreferences
---@field GetEAX2Room fun(self: dbc.row.SoundProviderPreferences): integer
---@field SetEAX2Room fun(self: dbc.row.SoundProviderPreferences, value: integer): dbc.row.SoundProviderPreferences
---@field GetEAX2RoomHF fun(self: dbc.row.SoundProviderPreferences): integer
---@field SetEAX2RoomHF fun(self: dbc.row.SoundProviderPreferences, value: integer): dbc.row.SoundProviderPreferences
---@field GetEAX2DecayHFRatio fun(self: dbc.row.SoundProviderPreferences): number
---@field SetEAX2DecayHFRatio fun(self: dbc.row.SoundProviderPreferences, value: number): dbc.row.SoundProviderPreferences
---@field GetEAX2Reflections fun(self: dbc.row.SoundProviderPreferences): integer
---@field SetEAX2Reflections fun(self: dbc.row.SoundProviderPreferences, value: integer): dbc.row.SoundProviderPreferences
---@field GetEAX2ReflectionsDelay fun(self: dbc.row.SoundProviderPreferences): number
---@field SetEAX2ReflectionsDelay fun(self: dbc.row.SoundProviderPreferences, value: number): dbc.row.SoundProviderPreferences
---@field GetEAX2Reverb fun(self: dbc.row.SoundProviderPreferences): integer
---@field SetEAX2Reverb fun(self: dbc.row.SoundProviderPreferences, value: integer): dbc.row.SoundProviderPreferences
---@field GetEAX2ReverbDelay fun(self: dbc.row.SoundProviderPreferences): number
---@field SetEAX2ReverbDelay fun(self: dbc.row.SoundProviderPreferences, value: number): dbc.row.SoundProviderPreferences
---@field GetEAX2RoomRolloff fun(self: dbc.row.SoundProviderPreferences): number
---@field SetEAX2RoomRolloff fun(self: dbc.row.SoundProviderPreferences, value: number): dbc.row.SoundProviderPreferences
---@field GetEAX2AirAbsorption fun(self: dbc.row.SoundProviderPreferences): number
---@field SetEAX2AirAbsorption fun(self: dbc.row.SoundProviderPreferences, value: number): dbc.row.SoundProviderPreferences
---@field GetEAX3RoomLF fun(self: dbc.row.SoundProviderPreferences): integer
---@field SetEAX3RoomLF fun(self: dbc.row.SoundProviderPreferences, value: integer): dbc.row.SoundProviderPreferences
---@field GetEAX3DecayLFRatio fun(self: dbc.row.SoundProviderPreferences): number
---@field SetEAX3DecayLFRatio fun(self: dbc.row.SoundProviderPreferences, value: number): dbc.row.SoundProviderPreferences
---@field GetEAX3EchoTime fun(self: dbc.row.SoundProviderPreferences): number
---@field SetEAX3EchoTime fun(self: dbc.row.SoundProviderPreferences, value: number): dbc.row.SoundProviderPreferences
---@field GetEAX3EchoDepth fun(self: dbc.row.SoundProviderPreferences): number
---@field SetEAX3EchoDepth fun(self: dbc.row.SoundProviderPreferences, value: number): dbc.row.SoundProviderPreferences
---@field GetEAX3ModulationTime fun(self: dbc.row.SoundProviderPreferences): number
---@field SetEAX3ModulationTime fun(self: dbc.row.SoundProviderPreferences, value: number): dbc.row.SoundProviderPreferences
---@field GetEAX3ModulationDepth fun(self: dbc.row.SoundProviderPreferences): number
---@field SetEAX3ModulationDepth fun(self: dbc.row.SoundProviderPreferences, value: number): dbc.row.SoundProviderPreferences
---@field GetEAX3HFReference fun(self: dbc.row.SoundProviderPreferences): number
---@field SetEAX3HFReference fun(self: dbc.row.SoundProviderPreferences, value: number): dbc.row.SoundProviderPreferences
---@field GetEAX3LFReference fun(self: dbc.row.SoundProviderPreferences): number
---@field SetEAX3LFReference fun(self: dbc.row.SoundProviderPreferences, value: number): dbc.row.SoundProviderPreferences

-- Inferred Cross-Table Relations for SoundProviderPreferences

-- Cascading Creation & Relations Engine for SoundProviderPreferences
---@field CreateRelated fun(self: dbc.row.SoundProviderPreferences, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.SoundProviderPreferences, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.SoundProviderPreferences, child_table: string, child_field?: string): any[]

---Typed table handle for SoundProviderPreferences.dbc.
---@class dbc.Table.SoundProviderPreferences : DbcTable
---@field FindById fun(self: dbc.Table.SoundProviderPreferences, id: integer): dbc.row.SoundProviderPreferences|nil
---@field GetById fun(self: dbc.Table.SoundProviderPreferences, id: integer): dbc.row.SoundProviderPreferences|nil
---@field GetRow fun(self: dbc.Table.SoundProviderPreferences, row: integer): dbc.row.SoundProviderPreferences
---@field NewRow fun(self: dbc.Table.SoundProviderPreferences, id?: integer): dbc.row.SoundProviderPreferences
---@field Create fun(self: dbc.Table.SoundProviderPreferences, id?: integer): dbc.row.SoundProviderPreferences
---@field CreateNext fun(self: dbc.Table.SoundProviderPreferences, data?: table): dbc.row.SoundProviderPreferences
---@field CloneRow fun(self: dbc.Table.SoundProviderPreferences, source: integer|dbc.row.SoundProviderPreferences, new_id?: integer): dbc.row.SoundProviderPreferences
---@field GetAllRows fun(self: dbc.Table.SoundProviderPreferences): dbc.row.SoundProviderPreferences[]
---@field Query fun(self: dbc.Table.SoundProviderPreferences): dbc.Query<dbc.row.SoundProviderPreferences>
---@field Rows fun(self: dbc.Table.SoundProviderPreferences): fun(): integer, dbc.row.SoundProviderPreferences
