---@meta
-- Generated LuaLS annotations for SpellChainEffects.dbc. Do not edit.

---Row representation of SpellChainEffects.dbc.
---@class dbc.row.SpellChainEffects : RowProxy
---@field ID integer
---@field AvgSegLen number
---@field Width number
---@field NoiseScale number
---@field TexCoordScale number
---@field SegDuration integer
---@field SegDelay integer
---@field Texture string
---@field Flags integer
---@field JointCount integer
---@field JointOffsetRadius number
---@field JointsPerMinorJoint integer
---@field MinorJointsPerMajorJoint integer
---@field MinorJointScale number
---@field MajorJointScale number
---@field JointMoveSpeed number
---@field JointSmoothness number
---@field MinDurationBetweenJointJumps number
---@field MaxDurationBetweenJointJumps number
---@field WaveHeight number
---@field WaveFreq number
---@field WaveSpeed number
---@field MinWaveAngle number
---@field MaxWaveAngle number
---@field MinWaveSpin number
---@field MaxWaveSpin number
---@field ArcHeight number
---@field MinArcAngle number
---@field MaxArcAngle number
---@field MinArcSpin number
---@field MaxArcSpin number
---@field DelayBetweenEffects number
---@field MinFlickerOnDuration number
---@field MaxFlickerOnDuration number
---@field MinFlickerOffDuration number
---@field MaxFlickerOffDuration number
---@field PulseSpeed number
---@field PulseOnLength number
---@field PulseFadeLength number
---@field Alpha integer
---@field Red integer
---@field Green integer
---@field Blue integer
---@field BlendMode integer
---@field Combo string
---@field RenderLayer integer
---@field TextureLength number
---@field WavePhase number

-- Fluent PascalCase Methods for SpellChainEffects
---@field GetID fun(self: dbc.row.SpellChainEffects): integer
---@field SetID fun(self: dbc.row.SpellChainEffects, value: integer): dbc.row.SpellChainEffects
---@field GetAvgSegLen fun(self: dbc.row.SpellChainEffects): number
---@field SetAvgSegLen fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetWidth fun(self: dbc.row.SpellChainEffects): number
---@field SetWidth fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetNoiseScale fun(self: dbc.row.SpellChainEffects): number
---@field SetNoiseScale fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetTexCoordScale fun(self: dbc.row.SpellChainEffects): number
---@field SetTexCoordScale fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetSegDuration fun(self: dbc.row.SpellChainEffects): integer
---@field SetSegDuration fun(self: dbc.row.SpellChainEffects, value: integer): dbc.row.SpellChainEffects
---@field GetSegDelay fun(self: dbc.row.SpellChainEffects): integer
---@field SetSegDelay fun(self: dbc.row.SpellChainEffects, value: integer): dbc.row.SpellChainEffects
---@field GetTexture fun(self: dbc.row.SpellChainEffects): string
---@field SetTexture fun(self: dbc.row.SpellChainEffects, value: string): dbc.row.SpellChainEffects
---@field GetFlags fun(self: dbc.row.SpellChainEffects): integer
---@field SetFlags fun(self: dbc.row.SpellChainEffects, value: integer): dbc.row.SpellChainEffects
---@field HasFlags fun(self: dbc.row.SpellChainEffects, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.SpellChainEffects, flag: integer): dbc.row.SpellChainEffects
---@field RemoveFlags fun(self: dbc.row.SpellChainEffects, flag: integer): dbc.row.SpellChainEffects
---@field GetJointCount fun(self: dbc.row.SpellChainEffects): integer
---@field SetJointCount fun(self: dbc.row.SpellChainEffects, value: integer): dbc.row.SpellChainEffects
---@field GetJointOffsetRadius fun(self: dbc.row.SpellChainEffects): number
---@field SetJointOffsetRadius fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetJointsPerMinorJoint fun(self: dbc.row.SpellChainEffects): integer
---@field SetJointsPerMinorJoint fun(self: dbc.row.SpellChainEffects, value: integer): dbc.row.SpellChainEffects
---@field GetMinorJointsPerMajorJoint fun(self: dbc.row.SpellChainEffects): integer
---@field SetMinorJointsPerMajorJoint fun(self: dbc.row.SpellChainEffects, value: integer): dbc.row.SpellChainEffects
---@field GetMinorJointScale fun(self: dbc.row.SpellChainEffects): number
---@field SetMinorJointScale fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetMajorJointScale fun(self: dbc.row.SpellChainEffects): number
---@field SetMajorJointScale fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetJointMoveSpeed fun(self: dbc.row.SpellChainEffects): number
---@field SetJointMoveSpeed fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetJointSmoothness fun(self: dbc.row.SpellChainEffects): number
---@field SetJointSmoothness fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetMinDurationBetweenJointJumps fun(self: dbc.row.SpellChainEffects): number
---@field SetMinDurationBetweenJointJumps fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetMaxDurationBetweenJointJumps fun(self: dbc.row.SpellChainEffects): number
---@field SetMaxDurationBetweenJointJumps fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetWaveHeight fun(self: dbc.row.SpellChainEffects): number
---@field SetWaveHeight fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetWaveFreq fun(self: dbc.row.SpellChainEffects): number
---@field SetWaveFreq fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetWaveSpeed fun(self: dbc.row.SpellChainEffects): number
---@field SetWaveSpeed fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetMinWaveAngle fun(self: dbc.row.SpellChainEffects): number
---@field SetMinWaveAngle fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetMaxWaveAngle fun(self: dbc.row.SpellChainEffects): number
---@field SetMaxWaveAngle fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetMinWaveSpin fun(self: dbc.row.SpellChainEffects): number
---@field SetMinWaveSpin fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetMaxWaveSpin fun(self: dbc.row.SpellChainEffects): number
---@field SetMaxWaveSpin fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetArcHeight fun(self: dbc.row.SpellChainEffects): number
---@field SetArcHeight fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetMinArcAngle fun(self: dbc.row.SpellChainEffects): number
---@field SetMinArcAngle fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetMaxArcAngle fun(self: dbc.row.SpellChainEffects): number
---@field SetMaxArcAngle fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetMinArcSpin fun(self: dbc.row.SpellChainEffects): number
---@field SetMinArcSpin fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetMaxArcSpin fun(self: dbc.row.SpellChainEffects): number
---@field SetMaxArcSpin fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetDelayBetweenEffects fun(self: dbc.row.SpellChainEffects): number
---@field SetDelayBetweenEffects fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetMinFlickerOnDuration fun(self: dbc.row.SpellChainEffects): number
---@field SetMinFlickerOnDuration fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetMaxFlickerOnDuration fun(self: dbc.row.SpellChainEffects): number
---@field SetMaxFlickerOnDuration fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetMinFlickerOffDuration fun(self: dbc.row.SpellChainEffects): number
---@field SetMinFlickerOffDuration fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetMaxFlickerOffDuration fun(self: dbc.row.SpellChainEffects): number
---@field SetMaxFlickerOffDuration fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetPulseSpeed fun(self: dbc.row.SpellChainEffects): number
---@field SetPulseSpeed fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetPulseOnLength fun(self: dbc.row.SpellChainEffects): number
---@field SetPulseOnLength fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetPulseFadeLength fun(self: dbc.row.SpellChainEffects): number
---@field SetPulseFadeLength fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetAlpha fun(self: dbc.row.SpellChainEffects): integer
---@field SetAlpha fun(self: dbc.row.SpellChainEffects, value: integer): dbc.row.SpellChainEffects
---@field GetRed fun(self: dbc.row.SpellChainEffects): integer
---@field SetRed fun(self: dbc.row.SpellChainEffects, value: integer): dbc.row.SpellChainEffects
---@field GetGreen fun(self: dbc.row.SpellChainEffects): integer
---@field SetGreen fun(self: dbc.row.SpellChainEffects, value: integer): dbc.row.SpellChainEffects
---@field GetBlue fun(self: dbc.row.SpellChainEffects): integer
---@field SetBlue fun(self: dbc.row.SpellChainEffects, value: integer): dbc.row.SpellChainEffects
---@field GetBlendMode fun(self: dbc.row.SpellChainEffects): integer
---@field SetBlendMode fun(self: dbc.row.SpellChainEffects, value: integer): dbc.row.SpellChainEffects
---@field GetCombo fun(self: dbc.row.SpellChainEffects): string
---@field SetCombo fun(self: dbc.row.SpellChainEffects, value: string): dbc.row.SpellChainEffects
---@field GetRenderLayer fun(self: dbc.row.SpellChainEffects): integer
---@field SetRenderLayer fun(self: dbc.row.SpellChainEffects, value: integer): dbc.row.SpellChainEffects
---@field GetTextureLength fun(self: dbc.row.SpellChainEffects): number
---@field SetTextureLength fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects
---@field GetWavePhase fun(self: dbc.row.SpellChainEffects): number
---@field SetWavePhase fun(self: dbc.row.SpellChainEffects, value: number): dbc.row.SpellChainEffects

-- Inferred Cross-Table Relations for SpellChainEffects

-- Cascading Creation & Relations Engine for SpellChainEffects
---@field CreateRelated fun(self: dbc.row.SpellChainEffects, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.SpellChainEffects, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.SpellChainEffects, child_table: string, child_field?: string): any[]

---Typed table handle for SpellChainEffects.dbc.
---@class dbc.Table.SpellChainEffects : DbcTable
---@field FindById fun(self: dbc.Table.SpellChainEffects, id: integer): dbc.row.SpellChainEffects|nil
---@field GetById fun(self: dbc.Table.SpellChainEffects, id: integer): dbc.row.SpellChainEffects|nil
---@field GetRow fun(self: dbc.Table.SpellChainEffects, row: integer): dbc.row.SpellChainEffects
---@field NewRow fun(self: dbc.Table.SpellChainEffects, id?: integer): dbc.row.SpellChainEffects
---@field Create fun(self: dbc.Table.SpellChainEffects, id?: integer): dbc.row.SpellChainEffects
---@field CreateNext fun(self: dbc.Table.SpellChainEffects, data?: table): dbc.row.SpellChainEffects
---@field CloneRow fun(self: dbc.Table.SpellChainEffects, source: integer|dbc.row.SpellChainEffects, new_id?: integer): dbc.row.SpellChainEffects
---@field GetAllRows fun(self: dbc.Table.SpellChainEffects): dbc.row.SpellChainEffects[]
---@field Query fun(self: dbc.Table.SpellChainEffects): dbc.Query<dbc.row.SpellChainEffects>
---@field Rows fun(self: dbc.Table.SpellChainEffects): fun(): integer, dbc.row.SpellChainEffects
