---@meta
-- Generated LuaLS annotations for SpellMissile.dbc. Do not edit.

---Row representation of SpellMissile.dbc.
---@class dbc.row.SpellMissile : RowProxy
---@field ID integer
---@field Flags integer
---@field DefaultPitchMin number
---@field DefaultPitchMax number
---@field DefaultSpeedMin number
---@field DefaultSpeedMax number
---@field RandomizeFacingMin number
---@field RandomizeFacingMax number
---@field RandomizePitchMin number
---@field RandomizePitchMax number
---@field RandomizeSpeedMin number
---@field RandomizeSpeedMax number
---@field Gravity number
---@field MaxDuration number
---@field CollisionRadius number

-- Fluent PascalCase Methods for SpellMissile
---@field GetID fun(self: dbc.row.SpellMissile): integer
---@field SetID fun(self: dbc.row.SpellMissile, value: integer): dbc.row.SpellMissile
---@field GetFlags fun(self: dbc.row.SpellMissile): integer
---@field SetFlags fun(self: dbc.row.SpellMissile, value: integer): dbc.row.SpellMissile
---@field HasFlags fun(self: dbc.row.SpellMissile, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.SpellMissile, flag: integer): dbc.row.SpellMissile
---@field RemoveFlags fun(self: dbc.row.SpellMissile, flag: integer): dbc.row.SpellMissile
---@field GetDefaultPitchMin fun(self: dbc.row.SpellMissile): number
---@field SetDefaultPitchMin fun(self: dbc.row.SpellMissile, value: number): dbc.row.SpellMissile
---@field GetDefaultPitchMax fun(self: dbc.row.SpellMissile): number
---@field SetDefaultPitchMax fun(self: dbc.row.SpellMissile, value: number): dbc.row.SpellMissile
---@field GetDefaultSpeedMin fun(self: dbc.row.SpellMissile): number
---@field SetDefaultSpeedMin fun(self: dbc.row.SpellMissile, value: number): dbc.row.SpellMissile
---@field GetDefaultSpeedMax fun(self: dbc.row.SpellMissile): number
---@field SetDefaultSpeedMax fun(self: dbc.row.SpellMissile, value: number): dbc.row.SpellMissile
---@field GetRandomizeFacingMin fun(self: dbc.row.SpellMissile): number
---@field SetRandomizeFacingMin fun(self: dbc.row.SpellMissile, value: number): dbc.row.SpellMissile
---@field GetRandomizeFacingMax fun(self: dbc.row.SpellMissile): number
---@field SetRandomizeFacingMax fun(self: dbc.row.SpellMissile, value: number): dbc.row.SpellMissile
---@field GetRandomizePitchMin fun(self: dbc.row.SpellMissile): number
---@field SetRandomizePitchMin fun(self: dbc.row.SpellMissile, value: number): dbc.row.SpellMissile
---@field GetRandomizePitchMax fun(self: dbc.row.SpellMissile): number
---@field SetRandomizePitchMax fun(self: dbc.row.SpellMissile, value: number): dbc.row.SpellMissile
---@field GetRandomizeSpeedMin fun(self: dbc.row.SpellMissile): number
---@field SetRandomizeSpeedMin fun(self: dbc.row.SpellMissile, value: number): dbc.row.SpellMissile
---@field GetRandomizeSpeedMax fun(self: dbc.row.SpellMissile): number
---@field SetRandomizeSpeedMax fun(self: dbc.row.SpellMissile, value: number): dbc.row.SpellMissile
---@field GetGravity fun(self: dbc.row.SpellMissile): number
---@field SetGravity fun(self: dbc.row.SpellMissile, value: number): dbc.row.SpellMissile
---@field GetMaxDuration fun(self: dbc.row.SpellMissile): number
---@field SetMaxDuration fun(self: dbc.row.SpellMissile, value: number): dbc.row.SpellMissile
---@field GetCollisionRadius fun(self: dbc.row.SpellMissile): number
---@field SetCollisionRadius fun(self: dbc.row.SpellMissile, value: number): dbc.row.SpellMissile

-- Inferred Cross-Table Relations for SpellMissile

-- Cascading Creation & Relations Engine for SpellMissile
---@field CreateRelated fun(self: dbc.row.SpellMissile, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.SpellMissile, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.SpellMissile, child_table: string, child_field?: string): any[]

---Typed table handle for SpellMissile.dbc.
---@class dbc.Table.SpellMissile : DbcTable
---@field FindById fun(self: dbc.Table.SpellMissile, id: integer): dbc.row.SpellMissile|nil
---@field GetById fun(self: dbc.Table.SpellMissile, id: integer): dbc.row.SpellMissile|nil
---@field GetRow fun(self: dbc.Table.SpellMissile, row: integer): dbc.row.SpellMissile
---@field NewRow fun(self: dbc.Table.SpellMissile, id?: integer): dbc.row.SpellMissile
---@field Create fun(self: dbc.Table.SpellMissile, id?: integer): dbc.row.SpellMissile
---@field CreateNext fun(self: dbc.Table.SpellMissile, data?: table): dbc.row.SpellMissile
---@field CloneRow fun(self: dbc.Table.SpellMissile, source: integer|dbc.row.SpellMissile, new_id?: integer): dbc.row.SpellMissile
---@field GetAllRows fun(self: dbc.Table.SpellMissile): dbc.row.SpellMissile[]
---@field Query fun(self: dbc.Table.SpellMissile): dbc.Query<dbc.row.SpellMissile>
---@field Rows fun(self: dbc.Table.SpellMissile): fun(): integer, dbc.row.SpellMissile
