---@meta
-- Generated LuaLS annotations for SpellVisualKit.dbc. Do not edit.

---Row representation of SpellVisualKit.dbc.
---@class dbc.row.SpellVisualKit : RowProxy
---@field ID integer
---@field StartAnimID integer
---@field AnimID integer
---@field HeadEffect integer
---@field ChestEffect integer
---@field BaseEffect integer
---@field LeftHandEffect integer
---@field RightHandEffect integer
---@field BreathEffect integer
---@field LeftWeaponEffect integer
---@field RightWeaponEffect integer
---@field SpecialEffect integer[]
---@field WorldEffect integer
---@field SoundID integer
---@field ShakeID integer
---@field CharProc integer[]
---@field CharParamZero number[]
---@field CharParamOne number[]
---@field CharParamTwo number[]
---@field CharParamThree number[]
---@field Flags integer

-- Fluent PascalCase Methods for SpellVisualKit
---@field GetID fun(self: dbc.row.SpellVisualKit): integer
---@field SetID fun(self: dbc.row.SpellVisualKit, value: integer): dbc.row.SpellVisualKit
---@field GetStartAnimID fun(self: dbc.row.SpellVisualKit): integer
---@field SetStartAnimID fun(self: dbc.row.SpellVisualKit, value: integer): dbc.row.SpellVisualKit
---@field GetAnimID fun(self: dbc.row.SpellVisualKit): integer
---@field SetAnimID fun(self: dbc.row.SpellVisualKit, value: integer): dbc.row.SpellVisualKit
---@field GetHeadEffect fun(self: dbc.row.SpellVisualKit): integer
---@field SetHeadEffect fun(self: dbc.row.SpellVisualKit, value: integer): dbc.row.SpellVisualKit
---@field GetChestEffect fun(self: dbc.row.SpellVisualKit): integer
---@field SetChestEffect fun(self: dbc.row.SpellVisualKit, value: integer): dbc.row.SpellVisualKit
---@field GetBaseEffect fun(self: dbc.row.SpellVisualKit): integer
---@field SetBaseEffect fun(self: dbc.row.SpellVisualKit, value: integer): dbc.row.SpellVisualKit
---@field GetLeftHandEffect fun(self: dbc.row.SpellVisualKit): integer
---@field SetLeftHandEffect fun(self: dbc.row.SpellVisualKit, value: integer): dbc.row.SpellVisualKit
---@field GetRightHandEffect fun(self: dbc.row.SpellVisualKit): integer
---@field SetRightHandEffect fun(self: dbc.row.SpellVisualKit, value: integer): dbc.row.SpellVisualKit
---@field GetBreathEffect fun(self: dbc.row.SpellVisualKit): integer
---@field SetBreathEffect fun(self: dbc.row.SpellVisualKit, value: integer): dbc.row.SpellVisualKit
---@field GetLeftWeaponEffect fun(self: dbc.row.SpellVisualKit): integer
---@field SetLeftWeaponEffect fun(self: dbc.row.SpellVisualKit, value: integer): dbc.row.SpellVisualKit
---@field GetRightWeaponEffect fun(self: dbc.row.SpellVisualKit): integer
---@field SetRightWeaponEffect fun(self: dbc.row.SpellVisualKit, value: integer): dbc.row.SpellVisualKit
---@field GetSpecialEffect fun(self: dbc.row.SpellVisualKit, index?: integer): integer|integer[]
---@field SetSpecialEffect fun(self: dbc.row.SpellVisualKit, value: integer|integer[], index?: integer): dbc.row.SpellVisualKit
---@field GetWorldEffect fun(self: dbc.row.SpellVisualKit): integer
---@field SetWorldEffect fun(self: dbc.row.SpellVisualKit, value: integer): dbc.row.SpellVisualKit
---@field GetSoundID fun(self: dbc.row.SpellVisualKit): integer
---@field SetSoundID fun(self: dbc.row.SpellVisualKit, value: integer): dbc.row.SpellVisualKit
---@field GetShakeID fun(self: dbc.row.SpellVisualKit): integer
---@field SetShakeID fun(self: dbc.row.SpellVisualKit, value: integer): dbc.row.SpellVisualKit
---@field GetCharProc fun(self: dbc.row.SpellVisualKit, index?: integer): integer|integer[]
---@field SetCharProc fun(self: dbc.row.SpellVisualKit, value: integer|integer[], index?: integer): dbc.row.SpellVisualKit
---@field GetCharParamZero fun(self: dbc.row.SpellVisualKit, index?: integer): number|number[]
---@field SetCharParamZero fun(self: dbc.row.SpellVisualKit, value: number|number[], index?: integer): dbc.row.SpellVisualKit
---@field GetCharParamOne fun(self: dbc.row.SpellVisualKit, index?: integer): number|number[]
---@field SetCharParamOne fun(self: dbc.row.SpellVisualKit, value: number|number[], index?: integer): dbc.row.SpellVisualKit
---@field GetCharParamTwo fun(self: dbc.row.SpellVisualKit, index?: integer): number|number[]
---@field SetCharParamTwo fun(self: dbc.row.SpellVisualKit, value: number|number[], index?: integer): dbc.row.SpellVisualKit
---@field GetCharParamThree fun(self: dbc.row.SpellVisualKit, index?: integer): number|number[]
---@field SetCharParamThree fun(self: dbc.row.SpellVisualKit, value: number|number[], index?: integer): dbc.row.SpellVisualKit
---@field GetFlags fun(self: dbc.row.SpellVisualKit): integer
---@field SetFlags fun(self: dbc.row.SpellVisualKit, value: integer): dbc.row.SpellVisualKit
---@field HasFlags fun(self: dbc.row.SpellVisualKit, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.SpellVisualKit, flag: integer): dbc.row.SpellVisualKit
---@field RemoveFlags fun(self: dbc.row.SpellVisualKit, flag: integer): dbc.row.SpellVisualKit

-- Inferred Cross-Table Relations for SpellVisualKit
---@field GetSoundEntries fun(self: dbc.row.SpellVisualKit): dbc.row.SoundEntries|nil
---@field SetSoundEntries fun(self: dbc.row.SpellVisualKit, target: dbc.row.SoundEntries|integer): dbc.row.SpellVisualKit

-- Cascading Creation & Relations Engine for SpellVisualKit
---@field CreateRelated fun(self: dbc.row.SpellVisualKit, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.SpellVisualKit, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.SpellVisualKit, child_table: string, child_field?: string): any[]

---Typed table handle for SpellVisualKit.dbc.
---@class dbc.Table.SpellVisualKit : DbcTable
---@field FindById fun(self: dbc.Table.SpellVisualKit, id: integer): dbc.row.SpellVisualKit|nil
---@field GetById fun(self: dbc.Table.SpellVisualKit, id: integer): dbc.row.SpellVisualKit|nil
---@field GetRow fun(self: dbc.Table.SpellVisualKit, row: integer): dbc.row.SpellVisualKit
---@field NewRow fun(self: dbc.Table.SpellVisualKit, id?: integer): dbc.row.SpellVisualKit
---@field Create fun(self: dbc.Table.SpellVisualKit, id?: integer): dbc.row.SpellVisualKit
---@field CreateNext fun(self: dbc.Table.SpellVisualKit, data?: table): dbc.row.SpellVisualKit
---@field CloneRow fun(self: dbc.Table.SpellVisualKit, source: integer|dbc.row.SpellVisualKit, new_id?: integer): dbc.row.SpellVisualKit
---@field GetAllRows fun(self: dbc.Table.SpellVisualKit): dbc.row.SpellVisualKit[]
---@field Query fun(self: dbc.Table.SpellVisualKit): dbc.Query<dbc.row.SpellVisualKit>
---@field Rows fun(self: dbc.Table.SpellVisualKit): fun(): integer, dbc.row.SpellVisualKit
