---@meta
-- Generated LuaLS annotations for SpellItemEnchantment.dbc. Do not edit.

---Row representation of SpellItemEnchantment.dbc.
---@class dbc.row.SpellItemEnchantment : RowProxy
---@field ID integer
---@field Charges integer
---@field Effect integer[]
---@field EffectPointsMin integer[]
---@field EffectPointsMax integer[]
---@field EffectArg integer[]
---@field Name string
---@field ItemVisual integer
---@field Flags integer
---@field Src_ItemID integer
---@field Condition_Id integer
---@field RequiredSkillID integer
---@field RequiredSkillRank integer
---@field MinLevel integer

-- Fluent PascalCase Methods for SpellItemEnchantment
---@field GetID fun(self: dbc.row.SpellItemEnchantment): integer
---@field SetID fun(self: dbc.row.SpellItemEnchantment, value: integer): dbc.row.SpellItemEnchantment
---@field GetCharges fun(self: dbc.row.SpellItemEnchantment): integer
---@field SetCharges fun(self: dbc.row.SpellItemEnchantment, value: integer): dbc.row.SpellItemEnchantment
---@field GetEffect fun(self: dbc.row.SpellItemEnchantment, index?: integer): integer|integer[]
---@field SetEffect fun(self: dbc.row.SpellItemEnchantment, value: integer|integer[], index?: integer): dbc.row.SpellItemEnchantment
---@field GetEffectPointsMin fun(self: dbc.row.SpellItemEnchantment, index?: integer): integer|integer[]
---@field SetEffectPointsMin fun(self: dbc.row.SpellItemEnchantment, value: integer|integer[], index?: integer): dbc.row.SpellItemEnchantment
---@field GetEffectPointsMax fun(self: dbc.row.SpellItemEnchantment, index?: integer): integer|integer[]
---@field SetEffectPointsMax fun(self: dbc.row.SpellItemEnchantment, value: integer|integer[], index?: integer): dbc.row.SpellItemEnchantment
---@field GetEffectArg fun(self: dbc.row.SpellItemEnchantment, index?: integer): integer|integer[]
---@field SetEffectArg fun(self: dbc.row.SpellItemEnchantment, value: integer|integer[], index?: integer): dbc.row.SpellItemEnchantment
---@field GetName fun(self: dbc.row.SpellItemEnchantment, locale?: string|integer): string
---@field SetName fun(self: dbc.row.SpellItemEnchantment, value: string, locale?: string|integer): dbc.row.SpellItemEnchantment
---@field GetItemVisual fun(self: dbc.row.SpellItemEnchantment): integer
---@field SetItemVisual fun(self: dbc.row.SpellItemEnchantment, value: integer): dbc.row.SpellItemEnchantment
---@field GetFlags fun(self: dbc.row.SpellItemEnchantment): integer
---@field SetFlags fun(self: dbc.row.SpellItemEnchantment, value: integer): dbc.row.SpellItemEnchantment
---@field HasFlags fun(self: dbc.row.SpellItemEnchantment, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.SpellItemEnchantment, flag: integer): dbc.row.SpellItemEnchantment
---@field RemoveFlags fun(self: dbc.row.SpellItemEnchantment, flag: integer): dbc.row.SpellItemEnchantment
---@field GetSrc_ItemID fun(self: dbc.row.SpellItemEnchantment): integer
---@field SetSrc_ItemID fun(self: dbc.row.SpellItemEnchantment, value: integer): dbc.row.SpellItemEnchantment
---@field GetCondition_Id fun(self: dbc.row.SpellItemEnchantment): integer
---@field SetCondition_Id fun(self: dbc.row.SpellItemEnchantment, value: integer): dbc.row.SpellItemEnchantment
---@field GetRequiredSkillID fun(self: dbc.row.SpellItemEnchantment): integer
---@field SetRequiredSkillID fun(self: dbc.row.SpellItemEnchantment, value: integer): dbc.row.SpellItemEnchantment
---@field GetRequiredSkillRank fun(self: dbc.row.SpellItemEnchantment): integer
---@field SetRequiredSkillRank fun(self: dbc.row.SpellItemEnchantment, value: integer): dbc.row.SpellItemEnchantment
---@field GetMinLevel fun(self: dbc.row.SpellItemEnchantment): integer
---@field SetMinLevel fun(self: dbc.row.SpellItemEnchantment, value: integer): dbc.row.SpellItemEnchantment

-- Inferred Cross-Table Relations for SpellItemEnchantment

-- Cascading Creation & Relations Engine for SpellItemEnchantment
---@field CreateRelated fun(self: dbc.row.SpellItemEnchantment, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.SpellItemEnchantment, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.SpellItemEnchantment, child_table: string, child_field?: string): any[]

---Typed table handle for SpellItemEnchantment.dbc.
---@class dbc.Table.SpellItemEnchantment : DbcTable
---@field FindById fun(self: dbc.Table.SpellItemEnchantment, id: integer): dbc.row.SpellItemEnchantment|nil
---@field GetById fun(self: dbc.Table.SpellItemEnchantment, id: integer): dbc.row.SpellItemEnchantment|nil
---@field GetRow fun(self: dbc.Table.SpellItemEnchantment, row: integer): dbc.row.SpellItemEnchantment
---@field NewRow fun(self: dbc.Table.SpellItemEnchantment, id?: integer): dbc.row.SpellItemEnchantment
---@field Create fun(self: dbc.Table.SpellItemEnchantment, id?: integer): dbc.row.SpellItemEnchantment
---@field CreateNext fun(self: dbc.Table.SpellItemEnchantment, data?: table): dbc.row.SpellItemEnchantment
---@field CloneRow fun(self: dbc.Table.SpellItemEnchantment, source: integer|dbc.row.SpellItemEnchantment, new_id?: integer): dbc.row.SpellItemEnchantment
---@field GetAllRows fun(self: dbc.Table.SpellItemEnchantment): dbc.row.SpellItemEnchantment[]
---@field Query fun(self: dbc.Table.SpellItemEnchantment): dbc.Query<dbc.row.SpellItemEnchantment>
---@field Rows fun(self: dbc.Table.SpellItemEnchantment): fun(): integer, dbc.row.SpellItemEnchantment
