---@meta
-- Generated LuaLS annotations for TalentTab.dbc. Do not edit.

---Row representation of TalentTab.dbc.
---@class dbc.row.TalentTab : RowProxy
---@field ID integer
---@field Name string
---@field SpellIconID integer
---@field RaceMask integer
---@field ClassMask integer
---@field PetTalentMask integer
---@field OrderIndex integer
---@field BackgroundFile string

-- Fluent PascalCase Methods for TalentTab
---@field GetID fun(self: dbc.row.TalentTab): integer
---@field SetID fun(self: dbc.row.TalentTab, value: integer): dbc.row.TalentTab
---@field GetName fun(self: dbc.row.TalentTab, locale?: string|integer): string
---@field SetName fun(self: dbc.row.TalentTab, value: string, locale?: string|integer): dbc.row.TalentTab
---@field GetSpellIconID fun(self: dbc.row.TalentTab): integer
---@field SetSpellIconID fun(self: dbc.row.TalentTab, value: integer): dbc.row.TalentTab
---@field GetRaceMask fun(self: dbc.row.TalentTab): integer
---@field SetRaceMask fun(self: dbc.row.TalentTab, value: integer): dbc.row.TalentTab
---@field HasRaceMask fun(self: dbc.row.TalentTab, flag: integer): boolean
---@field AddRaceMask fun(self: dbc.row.TalentTab, flag: integer): dbc.row.TalentTab
---@field RemoveRaceMask fun(self: dbc.row.TalentTab, flag: integer): dbc.row.TalentTab
---@field GetClassMask fun(self: dbc.row.TalentTab): integer
---@field SetClassMask fun(self: dbc.row.TalentTab, value: integer): dbc.row.TalentTab
---@field HasClassMask fun(self: dbc.row.TalentTab, flag: integer): boolean
---@field AddClassMask fun(self: dbc.row.TalentTab, flag: integer): dbc.row.TalentTab
---@field RemoveClassMask fun(self: dbc.row.TalentTab, flag: integer): dbc.row.TalentTab
---@field GetPetTalentMask fun(self: dbc.row.TalentTab): integer
---@field SetPetTalentMask fun(self: dbc.row.TalentTab, value: integer): dbc.row.TalentTab
---@field HasPetTalentMask fun(self: dbc.row.TalentTab, flag: integer): boolean
---@field AddPetTalentMask fun(self: dbc.row.TalentTab, flag: integer): dbc.row.TalentTab
---@field RemovePetTalentMask fun(self: dbc.row.TalentTab, flag: integer): dbc.row.TalentTab
---@field GetOrderIndex fun(self: dbc.row.TalentTab): integer
---@field SetOrderIndex fun(self: dbc.row.TalentTab, value: integer): dbc.row.TalentTab
---@field GetBackgroundFile fun(self: dbc.row.TalentTab): string
---@field SetBackgroundFile fun(self: dbc.row.TalentTab, value: string): dbc.row.TalentTab

-- Inferred Cross-Table Relations for TalentTab
---@field GetSpellIcon fun(self: dbc.row.TalentTab): dbc.row.SpellIcon|nil
---@field SetSpellIcon fun(self: dbc.row.TalentTab, target: dbc.row.SpellIcon|integer): dbc.row.TalentTab

-- Cascading Creation & Relations Engine for TalentTab
---@field CreateRelated fun(self: dbc.row.TalentTab, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.TalentTab, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.TalentTab, child_table: string, child_field?: string): any[]

---Typed table handle for TalentTab.dbc.
---@class dbc.Table.TalentTab : DbcTable
---@field FindById fun(self: dbc.Table.TalentTab, id: integer): dbc.row.TalentTab|nil
---@field GetById fun(self: dbc.Table.TalentTab, id: integer): dbc.row.TalentTab|nil
---@field GetRow fun(self: dbc.Table.TalentTab, row: integer): dbc.row.TalentTab
---@field NewRow fun(self: dbc.Table.TalentTab, id?: integer): dbc.row.TalentTab
---@field Create fun(self: dbc.Table.TalentTab, id?: integer): dbc.row.TalentTab
---@field CreateNext fun(self: dbc.Table.TalentTab, data?: table): dbc.row.TalentTab
---@field CloneRow fun(self: dbc.Table.TalentTab, source: integer|dbc.row.TalentTab, new_id?: integer): dbc.row.TalentTab
---@field GetAllRows fun(self: dbc.Table.TalentTab): dbc.row.TalentTab[]
---@field Query fun(self: dbc.Table.TalentTab): dbc.Query<dbc.row.TalentTab>
---@field Rows fun(self: dbc.Table.TalentTab): fun(): integer, dbc.row.TalentTab
