---@meta
-- Generated LuaLS annotations for Vehicle.dbc. Do not edit.

---Row representation of Vehicle.dbc.
---@class dbc.row.Vehicle : RowProxy
---@field ID integer
---@field Flags integer
---@field TurnSpeed number
---@field PitchSpeed number
---@field PitchMin number
---@field PitchMax number
---@field SeatID integer[]
---@field MouseLookOffsetPitch number
---@field CameraFadeDistScalarMin number
---@field CameraFadeDistScalarMax number
---@field CameraPitchOffset number
---@field FacingLimitRight number
---@field FacingLimitLeft number
---@field MsslTrgtTurnLingering number
---@field MsslTrgtPitchLingering number
---@field MsslTrgtMouseLingering number
---@field MsslTrgtEndOpacity number
---@field MsslTrgtArcSpeed number
---@field MsslTrgtArcRepeat number
---@field MsslTrgtArcWidth number
---@field MsslTrgtImpactRadius number[]
---@field MsslTrgtArcTexture string
---@field MsslTrgtImpactTexture string
---@field MsslTrgtImpactModel string[]
---@field CameraYawOffset number
---@field UilocomotionType integer
---@field MsslTrgtImpactTexRadius number
---@field VehicleUIIndicatorID integer
---@field PowerDisplayID integer[]

-- Fluent PascalCase Methods for Vehicle
---@field GetID fun(self: dbc.row.Vehicle): integer
---@field SetID fun(self: dbc.row.Vehicle, value: integer): dbc.row.Vehicle
---@field GetFlags fun(self: dbc.row.Vehicle): integer
---@field SetFlags fun(self: dbc.row.Vehicle, value: integer): dbc.row.Vehicle
---@field HasFlags fun(self: dbc.row.Vehicle, flag: integer): boolean
---@field AddFlags fun(self: dbc.row.Vehicle, flag: integer): dbc.row.Vehicle
---@field RemoveFlags fun(self: dbc.row.Vehicle, flag: integer): dbc.row.Vehicle
---@field GetTurnSpeed fun(self: dbc.row.Vehicle): number
---@field SetTurnSpeed fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetPitchSpeed fun(self: dbc.row.Vehicle): number
---@field SetPitchSpeed fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetPitchMin fun(self: dbc.row.Vehicle): number
---@field SetPitchMin fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetPitchMax fun(self: dbc.row.Vehicle): number
---@field SetPitchMax fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetSeatID fun(self: dbc.row.Vehicle, index?: integer): integer|integer[]
---@field SetSeatID fun(self: dbc.row.Vehicle, value: integer|integer[], index?: integer): dbc.row.Vehicle
---@field GetMouseLookOffsetPitch fun(self: dbc.row.Vehicle): number
---@field SetMouseLookOffsetPitch fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetCameraFadeDistScalarMin fun(self: dbc.row.Vehicle): number
---@field SetCameraFadeDistScalarMin fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetCameraFadeDistScalarMax fun(self: dbc.row.Vehicle): number
---@field SetCameraFadeDistScalarMax fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetCameraPitchOffset fun(self: dbc.row.Vehicle): number
---@field SetCameraPitchOffset fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetFacingLimitRight fun(self: dbc.row.Vehicle): number
---@field SetFacingLimitRight fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetFacingLimitLeft fun(self: dbc.row.Vehicle): number
---@field SetFacingLimitLeft fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetMsslTrgtTurnLingering fun(self: dbc.row.Vehicle): number
---@field SetMsslTrgtTurnLingering fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetMsslTrgtPitchLingering fun(self: dbc.row.Vehicle): number
---@field SetMsslTrgtPitchLingering fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetMsslTrgtMouseLingering fun(self: dbc.row.Vehicle): number
---@field SetMsslTrgtMouseLingering fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetMsslTrgtEndOpacity fun(self: dbc.row.Vehicle): number
---@field SetMsslTrgtEndOpacity fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetMsslTrgtArcSpeed fun(self: dbc.row.Vehicle): number
---@field SetMsslTrgtArcSpeed fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetMsslTrgtArcRepeat fun(self: dbc.row.Vehicle): number
---@field SetMsslTrgtArcRepeat fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetMsslTrgtArcWidth fun(self: dbc.row.Vehicle): number
---@field SetMsslTrgtArcWidth fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetMsslTrgtImpactRadius fun(self: dbc.row.Vehicle, index?: integer): number|number[]
---@field SetMsslTrgtImpactRadius fun(self: dbc.row.Vehicle, value: number|number[], index?: integer): dbc.row.Vehicle
---@field GetMsslTrgtArcTexture fun(self: dbc.row.Vehicle): string
---@field SetMsslTrgtArcTexture fun(self: dbc.row.Vehicle, value: string): dbc.row.Vehicle
---@field GetMsslTrgtImpactTexture fun(self: dbc.row.Vehicle): string
---@field SetMsslTrgtImpactTexture fun(self: dbc.row.Vehicle, value: string): dbc.row.Vehicle
---@field GetMsslTrgtImpactModel fun(self: dbc.row.Vehicle, index?: integer): string|string[]
---@field SetMsslTrgtImpactModel fun(self: dbc.row.Vehicle, value: string|string[], index?: integer): dbc.row.Vehicle
---@field GetCameraYawOffset fun(self: dbc.row.Vehicle): number
---@field SetCameraYawOffset fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetUilocomotionType fun(self: dbc.row.Vehicle): integer
---@field SetUilocomotionType fun(self: dbc.row.Vehicle, value: integer): dbc.row.Vehicle
---@field GetMsslTrgtImpactTexRadius fun(self: dbc.row.Vehicle): number
---@field SetMsslTrgtImpactTexRadius fun(self: dbc.row.Vehicle, value: number): dbc.row.Vehicle
---@field GetVehicleUIIndicatorID fun(self: dbc.row.Vehicle): integer
---@field SetVehicleUIIndicatorID fun(self: dbc.row.Vehicle, value: integer): dbc.row.Vehicle
---@field GetPowerDisplayID fun(self: dbc.row.Vehicle, index?: integer): integer|integer[]
---@field SetPowerDisplayID fun(self: dbc.row.Vehicle, value: integer|integer[], index?: integer): dbc.row.Vehicle

-- Inferred Cross-Table Relations for Vehicle
---@field GetVehicleUIIndicator fun(self: dbc.row.Vehicle): dbc.row.VehicleUIIndicator|nil
---@field SetVehicleUIIndicator fun(self: dbc.row.Vehicle, target: dbc.row.VehicleUIIndicator|integer): dbc.row.Vehicle
---@field GetPowerDisplay fun(self: dbc.row.Vehicle): dbc.row.PowerDisplay|nil
---@field SetPowerDisplay fun(self: dbc.row.Vehicle, target: dbc.row.PowerDisplay|integer): dbc.row.Vehicle

-- Cascading Creation & Relations Engine for Vehicle
---@field CreateRelated fun(self: dbc.row.Vehicle, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.Vehicle, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.Vehicle, child_table: string, child_field?: string): any[]

---Typed table handle for Vehicle.dbc.
---@class dbc.Table.Vehicle : DbcTable
---@field FindById fun(self: dbc.Table.Vehicle, id: integer): dbc.row.Vehicle|nil
---@field GetById fun(self: dbc.Table.Vehicle, id: integer): dbc.row.Vehicle|nil
---@field GetRow fun(self: dbc.Table.Vehicle, row: integer): dbc.row.Vehicle
---@field NewRow fun(self: dbc.Table.Vehicle, id?: integer): dbc.row.Vehicle
---@field Create fun(self: dbc.Table.Vehicle, id?: integer): dbc.row.Vehicle
---@field CreateNext fun(self: dbc.Table.Vehicle, data?: table): dbc.row.Vehicle
---@field CloneRow fun(self: dbc.Table.Vehicle, source: integer|dbc.row.Vehicle, new_id?: integer): dbc.row.Vehicle
---@field GetAllRows fun(self: dbc.Table.Vehicle): dbc.row.Vehicle[]
---@field Query fun(self: dbc.Table.Vehicle): dbc.Query<dbc.row.Vehicle>
---@field Rows fun(self: dbc.Table.Vehicle): fun(): integer, dbc.row.Vehicle
