---@meta
-- Generated LuaLS annotations for VideoHardware.dbc. Do not edit.

---Row representation of VideoHardware.dbc.
---@class dbc.row.VideoHardware : RowProxy
---@field ID integer
---@field VendorID integer
---@field DeviceID integer
---@field FarclipIdx integer
---@field TerrainLODDistIdx integer
---@field TerrainShadowLOD integer
---@field DetailDoodadDensityIdx integer
---@field DetailDoodadAlpha integer
---@field AnimatingDoodadIdx integer
---@field Trilinear integer
---@field NumLights integer
---@field Specularity integer
---@field WaterLODIdx integer
---@field ParticleDensityIdx integer
---@field UnitDrawDistIdx integer
---@field SmallCullDistIdx integer
---@field ResolutionIdx integer
---@field BaseMipLevel integer
---@field OglOverrides string
---@field D3dOverrides string
---@field FixLag integer
---@field Multisample integer
---@field Atlasdisable integer

-- Fluent PascalCase Methods for VideoHardware
---@field GetID fun(self: dbc.row.VideoHardware): integer
---@field SetID fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetVendorID fun(self: dbc.row.VideoHardware): integer
---@field SetVendorID fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetDeviceID fun(self: dbc.row.VideoHardware): integer
---@field SetDeviceID fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetFarclipIdx fun(self: dbc.row.VideoHardware): integer
---@field SetFarclipIdx fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetTerrainLODDistIdx fun(self: dbc.row.VideoHardware): integer
---@field SetTerrainLODDistIdx fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetTerrainShadowLOD fun(self: dbc.row.VideoHardware): integer
---@field SetTerrainShadowLOD fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetDetailDoodadDensityIdx fun(self: dbc.row.VideoHardware): integer
---@field SetDetailDoodadDensityIdx fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetDetailDoodadAlpha fun(self: dbc.row.VideoHardware): integer
---@field SetDetailDoodadAlpha fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetAnimatingDoodadIdx fun(self: dbc.row.VideoHardware): integer
---@field SetAnimatingDoodadIdx fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetTrilinear fun(self: dbc.row.VideoHardware): integer
---@field SetTrilinear fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetNumLights fun(self: dbc.row.VideoHardware): integer
---@field SetNumLights fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetSpecularity fun(self: dbc.row.VideoHardware): integer
---@field SetSpecularity fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetWaterLODIdx fun(self: dbc.row.VideoHardware): integer
---@field SetWaterLODIdx fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetParticleDensityIdx fun(self: dbc.row.VideoHardware): integer
---@field SetParticleDensityIdx fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetUnitDrawDistIdx fun(self: dbc.row.VideoHardware): integer
---@field SetUnitDrawDistIdx fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetSmallCullDistIdx fun(self: dbc.row.VideoHardware): integer
---@field SetSmallCullDistIdx fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetResolutionIdx fun(self: dbc.row.VideoHardware): integer
---@field SetResolutionIdx fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetBaseMipLevel fun(self: dbc.row.VideoHardware): integer
---@field SetBaseMipLevel fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetOglOverrides fun(self: dbc.row.VideoHardware): string
---@field SetOglOverrides fun(self: dbc.row.VideoHardware, value: string): dbc.row.VideoHardware
---@field GetD3dOverrides fun(self: dbc.row.VideoHardware): string
---@field SetD3dOverrides fun(self: dbc.row.VideoHardware, value: string): dbc.row.VideoHardware
---@field GetFixLag fun(self: dbc.row.VideoHardware): integer
---@field SetFixLag fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetMultisample fun(self: dbc.row.VideoHardware): integer
---@field SetMultisample fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware
---@field GetAtlasdisable fun(self: dbc.row.VideoHardware): integer
---@field SetAtlasdisable fun(self: dbc.row.VideoHardware, value: integer): dbc.row.VideoHardware

-- Inferred Cross-Table Relations for VideoHardware

-- Cascading Creation & Relations Engine for VideoHardware
---@field CreateRelated fun(self: dbc.row.VideoHardware, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.VideoHardware, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.VideoHardware, child_table: string, child_field?: string): any[]

---Typed table handle for VideoHardware.dbc.
---@class dbc.Table.VideoHardware : DbcTable
---@field FindById fun(self: dbc.Table.VideoHardware, id: integer): dbc.row.VideoHardware|nil
---@field GetById fun(self: dbc.Table.VideoHardware, id: integer): dbc.row.VideoHardware|nil
---@field GetRow fun(self: dbc.Table.VideoHardware, row: integer): dbc.row.VideoHardware
---@field NewRow fun(self: dbc.Table.VideoHardware, id?: integer): dbc.row.VideoHardware
---@field Create fun(self: dbc.Table.VideoHardware, id?: integer): dbc.row.VideoHardware
---@field CreateNext fun(self: dbc.Table.VideoHardware, data?: table): dbc.row.VideoHardware
---@field CloneRow fun(self: dbc.Table.VideoHardware, source: integer|dbc.row.VideoHardware, new_id?: integer): dbc.row.VideoHardware
---@field GetAllRows fun(self: dbc.Table.VideoHardware): dbc.row.VideoHardware[]
---@field Query fun(self: dbc.Table.VideoHardware): dbc.Query<dbc.row.VideoHardware>
---@field Rows fun(self: dbc.Table.VideoHardware): fun(): integer, dbc.row.VideoHardware
