---@meta
-- Generated LuaLS annotations for WorldMapOverlay.dbc. Do not edit.

---Row representation of WorldMapOverlay.dbc.
---@class dbc.row.WorldMapOverlay : RowProxy
---@field ID integer
---@field MapAreaID integer
---@field AreaID integer[]
---@field MapPointX integer
---@field MapPointY integer
---@field TextureName string
---@field TextureWidth integer
---@field TextureHeight integer
---@field OffsetX integer
---@field OffsetY integer
---@field HitRectTop integer
---@field HitRectLeft integer
---@field HitRectBottom integer
---@field HitRectRight integer

-- Fluent PascalCase Methods for WorldMapOverlay
---@field GetID fun(self: dbc.row.WorldMapOverlay): integer
---@field SetID fun(self: dbc.row.WorldMapOverlay, value: integer): dbc.row.WorldMapOverlay
---@field GetMapAreaID fun(self: dbc.row.WorldMapOverlay): integer
---@field SetMapAreaID fun(self: dbc.row.WorldMapOverlay, value: integer): dbc.row.WorldMapOverlay
---@field GetAreaID fun(self: dbc.row.WorldMapOverlay, index?: integer): integer|integer[]
---@field SetAreaID fun(self: dbc.row.WorldMapOverlay, value: integer|integer[], index?: integer): dbc.row.WorldMapOverlay
---@field GetMapPointX fun(self: dbc.row.WorldMapOverlay): integer
---@field SetMapPointX fun(self: dbc.row.WorldMapOverlay, value: integer): dbc.row.WorldMapOverlay
---@field GetMapPointY fun(self: dbc.row.WorldMapOverlay): integer
---@field SetMapPointY fun(self: dbc.row.WorldMapOverlay, value: integer): dbc.row.WorldMapOverlay
---@field GetTextureName fun(self: dbc.row.WorldMapOverlay): string
---@field SetTextureName fun(self: dbc.row.WorldMapOverlay, value: string): dbc.row.WorldMapOverlay
---@field GetTextureWidth fun(self: dbc.row.WorldMapOverlay): integer
---@field SetTextureWidth fun(self: dbc.row.WorldMapOverlay, value: integer): dbc.row.WorldMapOverlay
---@field GetTextureHeight fun(self: dbc.row.WorldMapOverlay): integer
---@field SetTextureHeight fun(self: dbc.row.WorldMapOverlay, value: integer): dbc.row.WorldMapOverlay
---@field GetOffsetX fun(self: dbc.row.WorldMapOverlay): integer
---@field SetOffsetX fun(self: dbc.row.WorldMapOverlay, value: integer): dbc.row.WorldMapOverlay
---@field GetOffsetY fun(self: dbc.row.WorldMapOverlay): integer
---@field SetOffsetY fun(self: dbc.row.WorldMapOverlay, value: integer): dbc.row.WorldMapOverlay
---@field GetHitRectTop fun(self: dbc.row.WorldMapOverlay): integer
---@field SetHitRectTop fun(self: dbc.row.WorldMapOverlay, value: integer): dbc.row.WorldMapOverlay
---@field GetHitRectLeft fun(self: dbc.row.WorldMapOverlay): integer
---@field SetHitRectLeft fun(self: dbc.row.WorldMapOverlay, value: integer): dbc.row.WorldMapOverlay
---@field GetHitRectBottom fun(self: dbc.row.WorldMapOverlay): integer
---@field SetHitRectBottom fun(self: dbc.row.WorldMapOverlay, value: integer): dbc.row.WorldMapOverlay
---@field GetHitRectRight fun(self: dbc.row.WorldMapOverlay): integer
---@field SetHitRectRight fun(self: dbc.row.WorldMapOverlay, value: integer): dbc.row.WorldMapOverlay

-- Inferred Cross-Table Relations for WorldMapOverlay
---@field GetAreaTable fun(self: dbc.row.WorldMapOverlay): dbc.row.AreaTable|nil
---@field SetAreaTable fun(self: dbc.row.WorldMapOverlay, target: dbc.row.AreaTable|integer): dbc.row.WorldMapOverlay

-- Cascading Creation & Relations Engine for WorldMapOverlay
---@field CreateRelated fun(self: dbc.row.WorldMapOverlay, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.WorldMapOverlay, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.WorldMapOverlay, child_table: string, child_field?: string): any[]

---Typed table handle for WorldMapOverlay.dbc.
---@class dbc.Table.WorldMapOverlay : DbcTable
---@field FindById fun(self: dbc.Table.WorldMapOverlay, id: integer): dbc.row.WorldMapOverlay|nil
---@field GetById fun(self: dbc.Table.WorldMapOverlay, id: integer): dbc.row.WorldMapOverlay|nil
---@field GetRow fun(self: dbc.Table.WorldMapOverlay, row: integer): dbc.row.WorldMapOverlay
---@field NewRow fun(self: dbc.Table.WorldMapOverlay, id?: integer): dbc.row.WorldMapOverlay
---@field Create fun(self: dbc.Table.WorldMapOverlay, id?: integer): dbc.row.WorldMapOverlay
---@field CreateNext fun(self: dbc.Table.WorldMapOverlay, data?: table): dbc.row.WorldMapOverlay
---@field CloneRow fun(self: dbc.Table.WorldMapOverlay, source: integer|dbc.row.WorldMapOverlay, new_id?: integer): dbc.row.WorldMapOverlay
---@field GetAllRows fun(self: dbc.Table.WorldMapOverlay): dbc.row.WorldMapOverlay[]
---@field Query fun(self: dbc.Table.WorldMapOverlay): dbc.Query<dbc.row.WorldMapOverlay>
---@field Rows fun(self: dbc.Table.WorldMapOverlay): fun(): integer, dbc.row.WorldMapOverlay
