---@meta
-- Generated LuaLS annotations for WorldChunkSounds.dbc. Do not edit.

---Row representation of WorldChunkSounds.dbc.
---@class dbc.row.WorldChunkSounds : RowProxy
---@field WorldMapMapID integer
---@field ChunkX integer
---@field ChunkY integer
---@field SubchunkX integer
---@field SubchunkY integer
---@field ZoneintroMusicID integer
---@field ZoneMusicID integer
---@field SoundAmbienceID integer
---@field SoundProviderPreferencesID integer

-- Fluent PascalCase Methods for WorldChunkSounds
---@field GetWorldMapMapID fun(self: dbc.row.WorldChunkSounds): integer
---@field SetWorldMapMapID fun(self: dbc.row.WorldChunkSounds, value: integer): dbc.row.WorldChunkSounds
---@field GetChunkX fun(self: dbc.row.WorldChunkSounds): integer
---@field SetChunkX fun(self: dbc.row.WorldChunkSounds, value: integer): dbc.row.WorldChunkSounds
---@field GetChunkY fun(self: dbc.row.WorldChunkSounds): integer
---@field SetChunkY fun(self: dbc.row.WorldChunkSounds, value: integer): dbc.row.WorldChunkSounds
---@field GetSubchunkX fun(self: dbc.row.WorldChunkSounds): integer
---@field SetSubchunkX fun(self: dbc.row.WorldChunkSounds, value: integer): dbc.row.WorldChunkSounds
---@field GetSubchunkY fun(self: dbc.row.WorldChunkSounds): integer
---@field SetSubchunkY fun(self: dbc.row.WorldChunkSounds, value: integer): dbc.row.WorldChunkSounds
---@field GetZoneintroMusicID fun(self: dbc.row.WorldChunkSounds): integer
---@field SetZoneintroMusicID fun(self: dbc.row.WorldChunkSounds, value: integer): dbc.row.WorldChunkSounds
---@field GetZoneMusicID fun(self: dbc.row.WorldChunkSounds): integer
---@field SetZoneMusicID fun(self: dbc.row.WorldChunkSounds, value: integer): dbc.row.WorldChunkSounds
---@field GetSoundAmbienceID fun(self: dbc.row.WorldChunkSounds): integer
---@field SetSoundAmbienceID fun(self: dbc.row.WorldChunkSounds, value: integer): dbc.row.WorldChunkSounds
---@field GetSoundProviderPreferencesID fun(self: dbc.row.WorldChunkSounds): integer
---@field SetSoundProviderPreferencesID fun(self: dbc.row.WorldChunkSounds, value: integer): dbc.row.WorldChunkSounds

-- Inferred Cross-Table Relations for WorldChunkSounds
---@field GetZoneMusic fun(self: dbc.row.WorldChunkSounds): dbc.row.ZoneMusic|nil
---@field SetZoneMusic fun(self: dbc.row.WorldChunkSounds, target: dbc.row.ZoneMusic|integer): dbc.row.WorldChunkSounds
---@field GetSoundAmbience fun(self: dbc.row.WorldChunkSounds): dbc.row.SoundAmbience|nil
---@field SetSoundAmbience fun(self: dbc.row.WorldChunkSounds, target: dbc.row.SoundAmbience|integer): dbc.row.WorldChunkSounds
---@field GetSoundProviderPreferences fun(self: dbc.row.WorldChunkSounds): dbc.row.SoundProviderPreferences|nil
---@field SetSoundProviderPreferences fun(self: dbc.row.WorldChunkSounds, target: dbc.row.SoundProviderPreferences|integer): dbc.row.WorldChunkSounds

-- Cascading Creation & Relations Engine for WorldChunkSounds
---@field CreateRelated fun(self: dbc.row.WorldChunkSounds, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.WorldChunkSounds, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.WorldChunkSounds, child_table: string, child_field?: string): any[]

---Typed table handle for WorldChunkSounds.dbc.
---@class dbc.Table.WorldChunkSounds : DbcTable
---@field FindById fun(self: dbc.Table.WorldChunkSounds, id: integer): dbc.row.WorldChunkSounds|nil
---@field GetById fun(self: dbc.Table.WorldChunkSounds, id: integer): dbc.row.WorldChunkSounds|nil
---@field GetRow fun(self: dbc.Table.WorldChunkSounds, row: integer): dbc.row.WorldChunkSounds
---@field NewRow fun(self: dbc.Table.WorldChunkSounds, id?: integer): dbc.row.WorldChunkSounds
---@field Create fun(self: dbc.Table.WorldChunkSounds, id?: integer): dbc.row.WorldChunkSounds
---@field CreateNext fun(self: dbc.Table.WorldChunkSounds, data?: table): dbc.row.WorldChunkSounds
---@field CloneRow fun(self: dbc.Table.WorldChunkSounds, source: integer|dbc.row.WorldChunkSounds, new_id?: integer): dbc.row.WorldChunkSounds
---@field GetAllRows fun(self: dbc.Table.WorldChunkSounds): dbc.row.WorldChunkSounds[]
---@field Query fun(self: dbc.Table.WorldChunkSounds): dbc.Query<dbc.row.WorldChunkSounds>
---@field Rows fun(self: dbc.Table.WorldChunkSounds): fun(): integer, dbc.row.WorldChunkSounds
