---@meta
-- Generated LuaLS annotations for WorldMapArea.dbc. Do not edit.

---Row representation of WorldMapArea.dbc.
---@class dbc.row.WorldMapArea : RowProxy
---@field ID integer
---@field MapID integer
---@field AreaID integer
---@field AreaName string
---@field LocLeft number
---@field LocRight number
---@field LocTop number
---@field LocBottom number
---@field DisplayMapID integer
---@field DefaultDungeonFloor integer
---@field ParentWorldMapID integer

-- Fluent PascalCase Methods for WorldMapArea
---@field GetID fun(self: dbc.row.WorldMapArea): integer
---@field SetID fun(self: dbc.row.WorldMapArea, value: integer): dbc.row.WorldMapArea
---@field GetMapID fun(self: dbc.row.WorldMapArea): integer
---@field SetMapID fun(self: dbc.row.WorldMapArea, value: integer): dbc.row.WorldMapArea
---@field GetAreaID fun(self: dbc.row.WorldMapArea): integer
---@field SetAreaID fun(self: dbc.row.WorldMapArea, value: integer): dbc.row.WorldMapArea
---@field GetAreaName fun(self: dbc.row.WorldMapArea): string
---@field SetAreaName fun(self: dbc.row.WorldMapArea, value: string): dbc.row.WorldMapArea
---@field GetLocLeft fun(self: dbc.row.WorldMapArea): number
---@field SetLocLeft fun(self: dbc.row.WorldMapArea, value: number): dbc.row.WorldMapArea
---@field GetLocRight fun(self: dbc.row.WorldMapArea): number
---@field SetLocRight fun(self: dbc.row.WorldMapArea, value: number): dbc.row.WorldMapArea
---@field GetLocTop fun(self: dbc.row.WorldMapArea): number
---@field SetLocTop fun(self: dbc.row.WorldMapArea, value: number): dbc.row.WorldMapArea
---@field GetLocBottom fun(self: dbc.row.WorldMapArea): number
---@field SetLocBottom fun(self: dbc.row.WorldMapArea, value: number): dbc.row.WorldMapArea
---@field GetDisplayMapID fun(self: dbc.row.WorldMapArea): integer
---@field SetDisplayMapID fun(self: dbc.row.WorldMapArea, value: integer): dbc.row.WorldMapArea
---@field GetDefaultDungeonFloor fun(self: dbc.row.WorldMapArea): integer
---@field SetDefaultDungeonFloor fun(self: dbc.row.WorldMapArea, value: integer): dbc.row.WorldMapArea
---@field GetParentWorldMapID fun(self: dbc.row.WorldMapArea): integer
---@field SetParentWorldMapID fun(self: dbc.row.WorldMapArea, value: integer): dbc.row.WorldMapArea

-- Inferred Cross-Table Relations for WorldMapArea
---@field GetMap fun(self: dbc.row.WorldMapArea): dbc.row.Map|nil
---@field SetMap fun(self: dbc.row.WorldMapArea, target: dbc.row.Map|integer): dbc.row.WorldMapArea
---@field GetAreaTable fun(self: dbc.row.WorldMapArea): dbc.row.AreaTable|nil
---@field SetAreaTable fun(self: dbc.row.WorldMapArea, target: dbc.row.AreaTable|integer): dbc.row.WorldMapArea

-- Cascading Creation & Relations Engine for WorldMapArea
---@field CreateRelated fun(self: dbc.row.WorldMapArea, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.WorldMapArea, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.WorldMapArea, child_table: string, child_field?: string): any[]

---Typed table handle for WorldMapArea.dbc.
---@class dbc.Table.WorldMapArea : DbcTable
---@field FindById fun(self: dbc.Table.WorldMapArea, id: integer): dbc.row.WorldMapArea|nil
---@field GetById fun(self: dbc.Table.WorldMapArea, id: integer): dbc.row.WorldMapArea|nil
---@field GetRow fun(self: dbc.Table.WorldMapArea, row: integer): dbc.row.WorldMapArea
---@field NewRow fun(self: dbc.Table.WorldMapArea, id?: integer): dbc.row.WorldMapArea
---@field Create fun(self: dbc.Table.WorldMapArea, id?: integer): dbc.row.WorldMapArea
---@field CreateNext fun(self: dbc.Table.WorldMapArea, data?: table): dbc.row.WorldMapArea
---@field CloneRow fun(self: dbc.Table.WorldMapArea, source: integer|dbc.row.WorldMapArea, new_id?: integer): dbc.row.WorldMapArea
---@field GetAllRows fun(self: dbc.Table.WorldMapArea): dbc.row.WorldMapArea[]
---@field Query fun(self: dbc.Table.WorldMapArea): dbc.Query<dbc.row.WorldMapArea>
---@field Rows fun(self: dbc.Table.WorldMapArea): fun(): integer, dbc.row.WorldMapArea
