---@meta
-- Generated LuaLS annotations for WorldStateUI.dbc. Do not edit.

---Row representation of WorldStateUI.dbc.
---@class dbc.row.WorldStateUI : RowProxy
---@field ID integer
---@field MapID integer
---@field AreaID integer
---@field PhaseShift integer
---@field Icon string
---@field String string
---@field Tooltip string
---@field StateVariable integer
---@field Type integer
---@field DynamicIcon string
---@field DynamicTooltip string
---@field ExtendedUI string
---@field ExtendedUIStateVariable integer[]

-- Fluent PascalCase Methods for WorldStateUI
---@field GetID fun(self: dbc.row.WorldStateUI): integer
---@field SetID fun(self: dbc.row.WorldStateUI, value: integer): dbc.row.WorldStateUI
---@field GetMapID fun(self: dbc.row.WorldStateUI): integer
---@field SetMapID fun(self: dbc.row.WorldStateUI, value: integer): dbc.row.WorldStateUI
---@field GetAreaID fun(self: dbc.row.WorldStateUI): integer
---@field SetAreaID fun(self: dbc.row.WorldStateUI, value: integer): dbc.row.WorldStateUI
---@field GetPhaseShift fun(self: dbc.row.WorldStateUI): integer
---@field SetPhaseShift fun(self: dbc.row.WorldStateUI, value: integer): dbc.row.WorldStateUI
---@field GetIcon fun(self: dbc.row.WorldStateUI): string
---@field SetIcon fun(self: dbc.row.WorldStateUI, value: string): dbc.row.WorldStateUI
---@field GetString fun(self: dbc.row.WorldStateUI, locale?: string|integer): string
---@field SetString fun(self: dbc.row.WorldStateUI, value: string, locale?: string|integer): dbc.row.WorldStateUI
---@field GetTooltip fun(self: dbc.row.WorldStateUI, locale?: string|integer): string
---@field SetTooltip fun(self: dbc.row.WorldStateUI, value: string, locale?: string|integer): dbc.row.WorldStateUI
---@field GetStateVariable fun(self: dbc.row.WorldStateUI): integer
---@field SetStateVariable fun(self: dbc.row.WorldStateUI, value: integer): dbc.row.WorldStateUI
---@field GetType fun(self: dbc.row.WorldStateUI): integer
---@field SetType fun(self: dbc.row.WorldStateUI, value: integer): dbc.row.WorldStateUI
---@field GetDynamicIcon fun(self: dbc.row.WorldStateUI): string
---@field SetDynamicIcon fun(self: dbc.row.WorldStateUI, value: string): dbc.row.WorldStateUI
---@field GetDynamicTooltip fun(self: dbc.row.WorldStateUI, locale?: string|integer): string
---@field SetDynamicTooltip fun(self: dbc.row.WorldStateUI, value: string, locale?: string|integer): dbc.row.WorldStateUI
---@field GetExtendedUI fun(self: dbc.row.WorldStateUI): string
---@field SetExtendedUI fun(self: dbc.row.WorldStateUI, value: string): dbc.row.WorldStateUI
---@field GetExtendedUIStateVariable fun(self: dbc.row.WorldStateUI, index?: integer): integer|integer[]
---@field SetExtendedUIStateVariable fun(self: dbc.row.WorldStateUI, value: integer|integer[], index?: integer): dbc.row.WorldStateUI

-- Inferred Cross-Table Relations for WorldStateUI
---@field GetMap fun(self: dbc.row.WorldStateUI): dbc.row.Map|nil
---@field SetMap fun(self: dbc.row.WorldStateUI, target: dbc.row.Map|integer): dbc.row.WorldStateUI
---@field GetAreaTable fun(self: dbc.row.WorldStateUI): dbc.row.AreaTable|nil
---@field SetAreaTable fun(self: dbc.row.WorldStateUI, target: dbc.row.AreaTable|integer): dbc.row.WorldStateUI

-- Cascading Creation & Relations Engine for WorldStateUI
---@field CreateRelated fun(self: dbc.row.WorldStateUI, target: string, data_or_id?: table|integer): any
---@field GetRelated fun(self: dbc.row.WorldStateUI, target_or_field: string): any
---@field GetChildren fun(self: dbc.row.WorldStateUI, child_table: string, child_field?: string): any[]

---Typed table handle for WorldStateUI.dbc.
---@class dbc.Table.WorldStateUI : DbcTable
---@field FindById fun(self: dbc.Table.WorldStateUI, id: integer): dbc.row.WorldStateUI|nil
---@field GetById fun(self: dbc.Table.WorldStateUI, id: integer): dbc.row.WorldStateUI|nil
---@field GetRow fun(self: dbc.Table.WorldStateUI, row: integer): dbc.row.WorldStateUI
---@field NewRow fun(self: dbc.Table.WorldStateUI, id?: integer): dbc.row.WorldStateUI
---@field Create fun(self: dbc.Table.WorldStateUI, id?: integer): dbc.row.WorldStateUI
---@field CreateNext fun(self: dbc.Table.WorldStateUI, data?: table): dbc.row.WorldStateUI
---@field CloneRow fun(self: dbc.Table.WorldStateUI, source: integer|dbc.row.WorldStateUI, new_id?: integer): dbc.row.WorldStateUI
---@field GetAllRows fun(self: dbc.Table.WorldStateUI): dbc.row.WorldStateUI[]
---@field Query fun(self: dbc.Table.WorldStateUI): dbc.Query<dbc.row.WorldStateUI>
---@field Rows fun(self: dbc.Table.WorldStateUI): fun(): integer, dbc.row.WorldStateUI
